import type { Translations } from './en';

const de: Translations = {
  meta: {
    home: {
      title: 'Beste iGaming Influencer-Marketing-Agentur 2026 | Octo Media',
      description: 'Führende iGaming-Influencer-Agentur für DACH. Verifizierte Streamer auf Twitch, YouTube & Kick. Nachgewiesener ROI für Krypto-Casino-Marken. Kostenloser Strategieaufruf.',
    },
    services: {
      title: 'iGaming Marketing-Dienstleistungen | Octo Media 2026',
      description: 'Expertenmarketing für Casino-Influencer, Glücksspiel-Streamer-Kampagnen und iGaming-Affiliate-Services. Bewährte Spielergewinnung für Krypto-Casino & Sportwetten-Marken.',
    },
    streamers: {
      title: 'Casino-Streamer auf Twitch, YouTube & Kick buchen | Octo Media',
      description: 'Treten Sie dem führenden iGaming-Streamer-Netzwerk bei. Konstante Glücksspiel-Sponsorings, bessere Konditionen und schnellere Zahlungen. Jetzt bewerben.',
    },
    whyUs: {
      title: 'iGaming-Marketingagentur — Gegründet von Casino-Insidern',
      description: 'Octo Media Group: 8 iGaming-Veteranen mit nachgewiesenen FTD-Ergebnissen, vollständiger ROI-Transparenz und Leistungsverantwortung.',
    },
    resources: {
      title: 'iGaming Marketing-Ressourcen & Leitfäden | Octo Media Group',
      description: 'Expertenleitfäden für iGaming-Influencer-Marketing: Compliance, ROI-Benchmarks, Twitch-Casino-Strategie, Krypto-Casino-Trends und mehr.',
    },
    privacy: {
      title: 'Datenschutzerklärung | Octo Media Group',
      description: 'Datenschutzerklärung der Octo Media Group. Erfahren Sie, wie wir Ihre personenbezogenen Daten erheben, verwenden und schützen.',
    },
    terms: {
      title: 'Nutzungsbedingungen | Octo Media Group',
      description: 'Nutzungsbedingungen der Octo Media Group. Lesen Sie die Bedingungen, die Ihre Nutzung unserer Website und Dienste regeln.',
    },
    cookies: {
      title: 'Cookie-Richtlinie | Octo Media Group',
      description: 'Cookie-Richtlinie der Octo Media Group. Erfahren Sie, wie wir Cookies und ähnliche Technologien auf unserer Website einsetzen.',
    },
  },
  nav: {
    home: 'Startseite',
    services: 'Leistungen',
    ourStory: 'Unsere Geschichte',
    forStreamers: 'Für Streamer',
    faq: 'FAQ',
    contact: 'Kontakt',
    blog: 'Blog',
    caseStudies: 'Fallstudien',
    whyJoin: 'Warum Beitreten',
    howItWorks: 'So Funktioniert Es',
    apply: 'Bewerben',
    ctaGrowthPlan: 'Kostenlosen Wachstumsplan Erhalten',
    ctaApplyNow: 'Jetzt Bewerben',
    ctaGetInTouch: 'Kontakt Aufnehmen',
  },
  footer: {
    description: 'Die führende iGaming-Influencer-Marketing-Agentur. Performance-getriebene Casino-Streamer-Kampagnen und Glücksspiel-Influencer-Marketing für Krypto-Casino, Online-Casino und Sportwetten-Marken weltweit.',
    quickLinks: 'Schnelllinks',
    ourServices: 'Unsere Leistungen',
    legal: 'Rechtliches',
    contact: 'Kontakt',
    links: {
      agency: 'iGaming Marketing-Agentur',
      services: 'iGaming Marketing-Leistungen',
      whyOcto: 'Warum Octo Media',
      hireStreamers: 'Casino-Streamer Buchen',
      faq: 'FAQ',
      contact: 'Kontakt',
    },
    serviceLinks: {
      streamer: 'Casino-Streamer-Marketing',
      affiliate: 'iGaming Affiliate-Marketing',
      influencer: 'Glücksspiel-Influencer-Marketing',
    },
    legalLinks: {
      privacy: 'Datenschutzerklärung',
      terms: 'Nutzungsbedingungen',
      cookies: 'Cookie-Richtlinie',
    },
    telegram: '@OctoMediaGroup auf Telegram',
    bottomText1: 'Octo Media Group ist eine spezialisierte iGaming-Influencer-Marketing-Agentur, die Casino-Streamer-Marketing, Glücksspiel-Influencer-Marketing und iGaming-Affiliate-Marketing für Krypto-Casino-, Online-Casino- und Sportwetten-Marken anbietet. Wir betreiben auch ein dediziertes Netzwerk für Twitch-, YouTube- und Kick-Casino-Streamer, die nach konstanten Glücksspiel-Sponsorings suchen.',
    bottomText2: 'Durch die Nutzung dieser Website stimmen Sie unseren Nutzungsbedingungen, unserer Datenschutzerklärung und unserer Cookie-Richtlinie zu. Die weitere Nutzung gilt als Akzeptanz dieser Richtlinien.',
    copyright: 'Alle Rechte vorbehalten. EU-DSGVO-konform.',
  },
  hero: {
    headline1: 'iGaming-Spielergewinnung',
    headline2: 'Optimiert für',
    headline3: 'Hohen LTV-Ertrag',
    subheadline: 'Die dedizierte Krypto-Casino-Streamer-Marketing-Agentur, der führende iGaming-Marken weltweit vertrauen. Performance-getriebenes Streamer- und Influencer-Marketing für iGaming und Krypto-Casinos.',
    stat1Value: '$10M+',
    stat1Label: 'Generierter Umsatz',
    stat2Value: 'Vollständige',
    stat2Label: 'Kampagnenumsetzung',
    stat3Value: 'Akquisition',
    stat3Label: 'und Retention',
    ctaPrimary: 'Kostenlose 30-Min-Beratung Vereinbaren',
    ctaSecondary: 'Leistungen Entdecken',
    badge: 'Aufgebaut von iGaming-Veteranen',
  },
  problem: {
    badge: 'Das Branchenproblem',
    title: 'Das iGaming-Influencer-Marketing-Problem,',
    titleHighlight: 'das Wir Lösen',
    subtitle: 'iGaming-Marken verschwenden Millionen für Influencer-Kampagnen, die Eitelkeitskennzahlen statt echter Spieler liefern. So sieht die Branche ohne uns aus:',
    items: [
      { stat: '70%', title: 'Verschwendetes Budget', description: 'der Influencer-Marketing-Budgets im iGaming werden für Creator mit gefälschten oder irrelevanten Zielgruppen ausgegeben' },
      { stat: '< 0,5%', title: 'Konversionsrate', description: 'ist die durchschnittliche Konversionsrate bei generischen Influencer-Kampagnen — kaum ein Rinnsal echter einzahlender Spieler' },
      { stat: 'KEINE', title: 'Rechenschaftspflicht', description: 'Keine Rechenschaftspflicht für Qualität und Quantität der Ergebnisse. Keine Vorhersehbarkeit. Die meisten Agenturen bieten null transparentes Tracking oder Garantien' },
    ],
    realityCheck: 'Realitätscheck',
    typicalMetrics: 'Typische Kampagnenkennzahlen',
    typicalSubtitle: 'Was passiert, wenn Sie mit Standardagenturen arbeiten',
    spent: 'Für Kampagne ausgegeben',
    signUps: 'Erhaltene Registrierungen',
    ftds: 'Konvertierte FTDs',
    costPerFtd: 'Kosten pro FTD',
    secondDepositors: 'Zweiteinzahler',
    noRetention: 'Keine Retention',
  },
  solution: {
    badge: 'Was Wir Am Besten Können',
    title: 'Unser iGaming-Marketing-',
    titleHighlight: 'Fachwissen',
    subtitle: 'Mit verifizierten Streamern in Dubai, Europa, LATAM, Nordamerika, Ozeanien und dem asiatisch-pazifischen Raum. Wir übernehmen sowohl Spielergewinnung als auch Retention für Casino- und Krypto-Casino-Marken.',
    services: [
      { title: 'Streamer-Marketing', description: 'Creator-Sourcing, KPI-basierte Umsetzung, Multi-Plattform-Abdeckung auf Twitch, YouTube und Kick für Neukundengewinnung und langfristige Retention', tag1: 'Akquisition', tag2: 'Retention', link: 'Mehr Erfahren' },
      { title: 'Affiliate-Marketing', description: 'Marktspezifische Creatives, Community-Aufbau und leistungsbasierte Affiliate-Partnerschaften für Spielergewinnung und Retention', tag1: 'Akquisition', tag2: 'Retention', link: 'Mehr Erfahren' },
      { title: 'Influencer-Marketing', description: 'Strategische Partnerschaften mit hochwirksamen Influencern für Markenbekanntheit, Spielergewinnung und laufendes Engagement durch authentische Inhalte', tag1: 'Akquisition', tag2: 'Retention', link: 'Mehr Erfahren' },
    ],
  },
  howWeSolve: {
    badge: 'Unser Prozess',
    title: 'Wie Unser iGaming-Streamer-Marketing',
    titleHighlight: 'Funktioniert',
    subtitle: 'Ein rigoroses Fünf-Stufen-System, das Influencer-Ausgaben in messbaren, skalierbaren Umsatz verwandelt',
    fiveStep: 'Fünf-Stufen-System',
    scalable: 'messbaren, skalierbaren Umsatz',
    cta: 'In Aktion Erleben',
    steps: [
      { title: 'Ausschließlich Handverlesene, Bewährte Streamer', description: 'Wir laden Streamer manuell ein und nehmen sie auf — ausschließlich aus iGaming-Nischen mit verifizierten Vorergebnissen, echten Zielgruppen und nachgewiesener Einzahlungsleistung.', highlight: 'Manuell Geprüft' },
      { title: 'Rigorose Prüfung & Marken-Matching', description: 'Jeder Streamer wird auf Engagement-Authentizität, Zielgruppendemografie und historische Leistung geprüft und nur mit Marken zusammengeführt, für die sie bereits konvertieren.', highlight: '100% Authentisch' },
      { title: 'Kontrollierte Live-Kampagnen mit Hoher Kaufbereitschaft', description: 'Streamer gehen live mit strukturiertem Gameplay, markensicherer Präsentation und authentischer Werbung — konzipiert für echte Spieler mit hoher Kaufbereitschaft, nicht für leere Aufrufe.', highlight: 'Nur Hohe Kaufbereitschaft' },
      { title: 'Vollständige ROI-Transparenz', description: 'Detaillierte wöchentliche Performance-Berichte mit Aufschlüsselung jedes ausgegebenen Euro — Streamer-Kosten, FTDs, Einzahlungen, Retention und ROI — klar und nachvollziehbar.', highlight: 'Wöchentliche Berichte' },
      { title: 'Skalieren Was Funktioniert, Halten Was Konvertiert', description: 'Wir verdoppeln bei erfolgreichen Streamern und aktivieren Retention-Mechaniken — Ranglisten, Boni und Community-Anreize — für Wiederholungseinzahlungen und höheren LTV.', highlight: 'Bewährte Skalierung' },
    ],
  },
  comparison: {
    badge: 'Der Unterschied',
    title: 'Warum iGaming-Marken Uns Standardagenturen',
    titleHighlight: 'Vorziehen',
    subtitle: 'Messbare Kennzahlen, die einen grundlegend anderen Ansatz im iGaming-Marketing belegen',
    standardAgency: 'Standardagentur',
    metrics: [
      { label: 'Retention' },
      { label: 'Konversionsrate' },
      { label: 'Zeit bis zu Ersten Ergebnissen' },
      { label: 'Budget-Transparenz & Effizienz' },
    ],
    features: [
      { category: 'Streamer-Prüfung', standard: 'Unverifiziert, gemischte Zielgruppen', octo: '100% bot-freie verifizierte Zielgruppen' },
      { category: 'Kampagnen-Support', standard: 'Monatliche PDF-Berichte', octo: 'Detaillierte Wochenberichte + dedizierter Manager' },
      { category: 'Marktabdeckung', standard: '1-2 Regionen', octo: '25+ Märkte, 15+ Sprachen' },
      { category: 'Retention-Strategie', standard: 'Nicht inbegriffen', octo: 'Vollständige Retention- und Community-Programme' },
      { category: 'Plattformabdeckung', standard: 'Fokus auf eine Plattform', octo: 'Twitch, YouTube, Kick & mehr' },
    ],
    highlights: ['Bessere Kontrolle', 'Hervorragende Umsetzung', 'Außergewöhnliche Ergebnisse'],
  },
  pricing: {
    title: 'Kampagnen-',
    titleHighlight: 'Pakete',
    subtitle: 'Von einer risikofreien Demo bis zur vollständigen Marktdominanz. Wählen Sie das Niveau, das Ihren Zielen entspricht.',
    mostPopular: 'Am Beliebtesten',
    footerNote: 'Alle Pakete beinhalten vollständiges Performance-Tracking, dedizierten Support und transparente Berichterstattung.',
    tiers: [
      { name: 'Demo-Kampagne', price: '$10.000', period: 'einmalig', tagline: 'Beweis vor Verpflichtung', cta: 'Demo Starten', features: ['5-10 verifizierte Streamer', '10-15 Stunden Live-Content', 'Vollständiges Performance-Tracking', 'Detaillierter ROI-Bericht', 'Skalierungsempfehlung'] },
      { name: 'Starter', price: '$25-50K', period: '/Monat', tagline: 'Für wachsende Marken, die neue Märkte erschließen', cta: 'Angebot Anfordern', features: ['15-20 große Streamer', '30-50 Stunden Content/Monat', 'Wöchentliche Performance-Berichte', 'Kampagnenoptimierung', 'Dedizierter Account-Manager'] },
      { name: 'Wachstum', price: '$50-75K', period: '/Monat', tagline: 'Für Marken, die aggressiv skalieren wollen', cta: 'Angebot Anfordern', features: ['50+ Mikro- und Makro-Streamer', '100+ Stunden Content/Monat', 'Echtzeit-Performance-Dashboard', 'Multi-Plattform-Abdeckung', 'Prioritäts-Support & Strategieberatung', 'Hochkonvertierendes SEO-Website-Partnerschaft'] },
      { name: 'Enterprise', price: '$100K+', period: '/Monat', tagline: 'Für große Betreiber, die Märkte dominieren', cta: 'Kontaktieren Sie Uns', features: ['100+ verifizierte Streamer', 'Unbegrenzte Live-Inhalte', 'Exklusive Streamer-Partnerschaften', 'White-Label-Optionen', 'Dediziertes Spezialistenteam', 'Individuelle Berichterstattung & Analytik', '5x SEO-Website-Partnerschaften'] },
    ],
  },
  socialProof: {
    badge: 'Weltweit Vertraut',
    title: 'Vertraut von Führenden',
    titleHighlight: 'iGaming',
    titleEnd: 'Marken',
    subtitle: 'Branchenführer vertrauen auf unser Netzwerk für Akquisition, Retention und Wachstum',
    stats: [
      { value: '15+', label: 'Markenpartner' },
      { value: '$2,5M', label: 'Investiertes Budget' },
      { value: '20+', label: 'Abgedeckte Märkte' },
      { value: '98%', label: 'Kundenbindung' },
    ],
    testimonials: [
      { quote: 'Die Streamer-Strategie von Octo Media hat uns geholfen, schnell in Schlüsselmärkten zu skalieren. Ihre Umsetzung und Transparenz sind erstklassig.', detail: 'Wir sahen eine sofortige Verbesserung des Zielgruppen-Engagements und der Konversionsraten über alle Streaming-Kanäle hinweg im ersten Monat.', role: 'Brand Manager', company: 'BC.GAME' },
      { quote: 'Die Zusammenarbeit mit Octo Media hat unsere Spielergewinnungs-Pipeline transformiert. Ihr tiefes Verständnis der iGaming-Zielgruppe lieferte von Tag eins an messbare Ergebnisse.', detail: 'Ihr gezielter Ansatz bei der Streamer-Auswahl und Content-Strategie führte zu qualitativ hochwertigeren Leads und besserem langfristigen Spielerwert.', role: 'Head of Marketing', company: 'BET365' },
      { quote: 'Die Qualität der Streamer und Inhalte, die Octo Media liefert, ist unübertroffen. Unsere Markensichtbarkeit in wettbewerbsintensiven Märkten wuchs innerhalb von Wochen erheblich.', detail: 'Von Anfang an hatten wir Zugang zu authentischen, engagierten Zielgruppen, die wirklich mit unserer Markenbotschaft verbunden waren.', role: 'Partnership Director', company: 'LEON' },
      { quote: 'Octo Media brachte einen datengestützten Ansatz für unsere Influencer-Kampagnen, den wir vorher nicht gesehen hatten. Retention-Kennzahlen verbesserten sich auf jedem Kanal, den sie verwalteten.', detail: 'Ihre strategischen Einblicke und kontinuierliche Optimierung hielten unsere Kampagnen das ganze Jahr über auf Spitzenleistung.', role: 'Growth Lead', company: 'MELBET' },
      { quote: 'Die Partnerschaft mit Octo Media gab uns Zugang zu einem kuratierten Netzwerk hochwirksamer Streamer. Die Kampagnenleistung übertraf konstant unsere Benchmarks.', detail: 'Wir erreichten ein Maß an Kampagnenleistungskonsistenz, das uns Vertrauen gab, das Budget zu erhöhen und in neue Märkte zu expandieren.', role: 'Acquisition Manager', company: 'STAKE' },
      { quote: 'Die nahtlose Integration und Professionalität, die Octo Media in unsere Kampagnen einbrachte, hebt sie hervor. Ihr Fokus auf Spieler-Retention lieferte außergewöhnlichen ROI.', detail: 'Im Gegensatz zu anderen Agenturen liegt ihnen wirklich der langfristige Partnerschaftserfolg und der Spieler-Lebenszeitwert am Herzen, nicht nur schnelle Gewinne.', role: 'Growth Lead', company: 'TRUSTDICE' },
    ],
  },
  markets: {
    items: [
      { title: 'Online-Casinos', description: 'Traditionelle Casinos, Krypto-Casinos, Bitcoin-Casinos, Live-Dealer-Casinos' },
      { title: 'Sportwetten', description: 'Fußballwetten, Esports-Wetten, Multi-Sport-Plattformen' },
      { title: 'Gaming-Glücksspiel', description: 'CS2-Glücksspiel, Rust-Glücksspiel, gaming-nahe Wetten' },
      { title: 'Poker-Räume', description: 'Online-Poker, Turniere' },
    ],
  },
  contact: {
    title: 'Kontakt',
    titleHighlight: 'Aufnehmen',
    subtitle: 'Bereit, Ihr Marketingbudget in echte einzahlende Spieler umzuwandeln? Senden Sie uns eine Nachricht oder buchen Sie eine kostenlose Beratung.',
    formTitle: 'Nachricht Senden',
    namePlaceholder: 'Ihr Name',
    emailPlaceholder: 'E-Mail-Adresse',
    messagePlaceholder: 'Ihre Nachricht',
    sendButton: 'Nachricht Senden',
    businessEmail: 'Geschäftliche E-Mail',
    businessEmailDesc: 'Für Partnerschaften und professionelle Anfragen',
    telegramSupport: 'Telegram-Support',
    telegramDesc: 'Schnelle Antworten und Echtzeit-Support',
    bookTitle: 'Kostenlose Beratung Buchen',
    bookDesc: 'Vereinbaren Sie ein 30-minütiges Gespräch, um Ihre Influencer-Marketing-Strategie zu besprechen.',
    discussLabel: 'Was wir besprechen werden',
    scheduleButton: 'Ihren Termin Vereinbaren',
    topics: [
      'Ihre aktuelle Spielergewinnungsstrategie',
      'Wie verifiziertes Influencer-Marketing Ihren Zielen dient',
      'Erwarteter ROI aus der Demo-Kampagne',
      'Individueller Kampagnenvorschlag für Ihre Marke',
    ],
    responseTime: 'Reaktionszeit',
    responseTimeValue: 'Antwortet normalerweise innerhalb von 15-30 Minuten',
    availability: 'Verfügbarkeit',
    availabilityValue: 'Aktiv: 7 Tage die Woche',
    supportType: 'Support-Art',
    supportTypeValue: 'Streamer-Anfragen, Kampagnenplanung, Partnerschaften',
  },
  finalCta: {
    badge: 'Begrenzte Verfügbarkeit',
    title1: 'Ihre Mitbewerber Skalieren Bereits',
    title2: 'Mit Uns',
    subtitle: 'Jeder Tag, den Sie warten, ist ein weiterer Tag verschwendeter Werbeausgaben für unverifizierten Influencer mit falschen Followern.',
    body: 'Wir nehmen pro Quartal nur eine begrenzte Anzahl von Marken auf, um qualitativ hochwertige Umsetzung zu gewährleisten. Sichern Sie sich Ihren Platz, bevor Ihre Mitbewerber es tun.',
    cta: 'Ihren Kostenlosen Wachstumsplan Erhalten',
    guarantees: ['Keine Langzeitverträge', '100% transparentes Tracking', 'Ergebnisse innerhalb von 2 Wochen', 'Dedizierter Account-Manager'],
  },
  demo: {
    badge: 'Null Risiko',
    title1: 'Noch Nicht Überzeugt?',
    title2: 'Erleben Sie Uns in Aktion',
    subtitle: 'Geben Sie uns $10.000 und zwei Wochen. Wenn wir keine messbaren Ergebnisse liefern, wissen Sie es, bevor Sie sich zu einem größeren Budget verpflichten.',
    steps: [
      { title: '$10.000 Investition', description: 'Fester Preis, keine versteckten Gebühren. Sie wissen genau, was Sie bezahlen.' },
      { title: '2-Wochen-Kampagne', description: '5-10 verifizierte Streamer gehen live und bewerben Ihre Marke.' },
      { title: 'Messbare Ergebnisse', description: 'Vollständiger Performance-Bericht mit ROI-Daten und Skalierungsplan.' },
    ],
    whatsIncluded: 'Was Inbegriffen Ist',
    includes: [
      'Handverlesene verifizierte Streamer, abgestimmt auf Ihre Marke',
      '10-15 Stunden Live-Streamer-Content',
      'Zugang zum Echtzeit-Tracking-Dashboard',
      'Detaillierter ROI & Performance-Bericht',
      'Skalierungsempfehlung ohne Verpflichtung',
    ],
    noContract: 'Kein Langzeitvertrag erforderlich. Die Ergebnisse sprechen für sich.',
    pilotLabel: '2-Wochen-Pilotkampagne',
    cta: 'Ihren Demo-Termin Vereinbaren',
  },
  streamersSection: {
    badge: 'Für Streamer',
    title: 'Ihre Streaming-',
    titleHighlight: 'Karriere Ausbauen',
    subtitle: 'Treten Sie unserem Netzwerk von 750+ verifizierten Streamern bei und werden Sie mit führenden iGaming-Marken zusammengeführt. Wir kümmern uns um die Geschäftsseite, damit Sie sich auf Content-Erstellung konzentrieren können.',
    benefits: [
      'Zugang zu Premium-iGaming-Marken',
      'Wettbewerbsfähige Provisionssätze',
      'Zuverlässige und pünktliche Zahlungen',
      'Dedizierter Partnerschaftsmanager',
      'Performance-Boni und Exklusivangebote',
      'Multi-Plattform-Support (Twitch, YouTube, Kick)',
    ],
    cta: 'Jetzt Bewerben',
    verifiedStreamers: 'Verifizierte Streamer',
    avgEarnings: 'Durchschnittliche monatliche Einnahmen',
    avgEarningsValue: '$2.000 - $15.000',
    platforms: 'Unterstützte Plattformen',
    platformsValue: 'Twitch, YT, Kick',
    paymentSchedule: 'Zahlungsplan',
    paymentScheduleValue: 'Zweiwöchentlich',
    markets: 'Verfügbare Märkte',
    marketsValue: '25+ Länder',
  },
  streamersPage: {
    hero: {
      badge: 'Für Streamer & Creator',
      title1: 'Aufhören, Deals zu Jagen.',
      title2: 'Anfangen,',
      titleHighlight: 'Bezahlt zu Werden',
      subtitle: 'Das iGaming-Streamer-Netzwerk, das verifizierte Creator mit führenden Casino- und Krypto-Marken für laufende Sponsorings verbindet.',
      subtitleSmall: 'Bessere Konditionen. Schnellere Zahlungen. Null Aufwand.',
      cta: 'Jetzt Bewerben',
    },
    benefits: {
      badge: 'Vollständiges Partnerschafts-Ökosystem',
      title: 'Warum',
      titleHighlight: 'Mit Uns Arbeiten',
      subtitle: 'Mehr als nur Marken-Deals. Ein vollständiges Ökosystem, das Ihr Einkommenspotenzial maximiert und Ihre Interessen bei jedem Schritt schützt.',
      commissionNote: '10% Provision auf Deals, die wir für Sie abschließen',
      commissionSub: 'Wird erst nach Zahlungseingang berechnet. Null Risiko, maximale Transparenz.',
      items: [
        { title: 'Persönlicher Manager 24/7', desc: 'Ihr dedizierter Account-Manager ist rund um die Uhr verfügbar, um alle Ihre Anfragen, Verhandlungen und Kampagnenkoordination zu bearbeiten.' },
        { title: 'Keine Exklusivität Erforderlich', desc: 'Selbst einen besseren Deal gefunden? Nur zu! Wir bieten kostenlose Beratung, damit Sie Ihren wahren Marktwert kennen.' },
        { title: 'Null Vorabkosten', desc: 'Keine Abonnementgebühren oder versteckten Kosten. Wir nehmen eine pauschale 10% erst nach Zahlungseingang für Ihre Kampagne. Einfach und transparent.' },
        { title: 'Nur Geprüfte Marken', desc: 'Kein Betrug oder verzögerte Zahlungen mehr. Heute arbeiten, heute bezahlt werden. Direkt auf Ihr Bankkonto oder Krypto-Wallet.' },
        { title: 'Flexible Deal-Strukturen', desc: 'Bevorzugen Sie Guthaben, feste Gebühren oder lebenslange Umsatzbeteiligung? Wir passen Deals an Ihre Präferenzen und Ihren Content-Stil an.' },
        { title: 'Keine Langzeitverträge', desc: 'Pause machen oder Probleme? Jederzeit aussteigen. Keine Strafen, keine Fragen. Wir haben Ihren Rücken.' },
        { title: 'Markenaufbau-Unterstützung', desc: 'Über Deals hinaus helfen wir Ihnen, Ihre persönliche Marke mit Website-Einrichtung, Social-Media-Strategie und professioneller Content-Beratung aufzubauen.' },
        { title: 'Exklusiver Event-Zugang', desc: 'Einladung zu Offline-Veranstaltungen weltweit. Wir fliegen Sie ein, alle Kosten übernommen. Vernetzen Sie sich mit Top-Streamern und Branchenführern.' },
        { title: 'Kontinuierliche Innovation', desc: 'Unsere Plattform entwickelt sich mit neuen Funktionen, Tools und Möglichkeiten weiter. Treten Sie bei, um die Zukunft der Creator-Monetarisierung zu gestalten.' },
      ],
    },
    howItWorks: {
      title: 'Wie Es',
      titleHighlight: 'Funktioniert',
      subtitle: 'Von der Bewerbung bis zur Auszahlung in vier einfachen Schritten',
      step: 'SCHRITT',
      steps: [
        { title: 'Bewerben', desc: 'Füllen Sie eine kurze Bewerbung mit Informationen zu Ihrem Kanal, Ihrer Plattform und Ihrer Zielgruppengröße aus.' },
        { title: 'Verifiziert Werden', desc: 'Unser Team überprüft Ihre Content-Qualität, Zielgruppen-Authentizität und Engagement-Kennzahlen.' },
        { title: 'Gematcht Werden', desc: 'Wir bringen Sie mit iGaming- und Krypto-Casino-Marken zusammen, die zu Ihrer Nische, Zielgruppe und Ihrem Content-Stil passen.' },
        { title: 'Erstellen & Bezahlt Werden', desc: 'Streamen Sie gesponserten iGaming-Content und erhalten Sie schnelle, zuverlässige Zahlungen direkt auf Ihr Konto.' },
      ],
    },
    faq: {
      title: 'Häufig Gestellte',
      titleHighlight: 'Fragen',
      subtitle: 'Häufige Fragen von Streamern, die unserem Netzwerk beitreten',
      items: [
        { q: 'Wie viel kann ich verdienen?', a: 'Die Einnahmen variieren je nach Ihrer Zielgruppengröße, Ihrem Engagement und Ihrer Content-Qualität. Unsere Streamer verdienen typischerweise zwischen $500 und $15.000+ pro Monat aus Marken-Deals über unser Netzwerk.' },
        { q: 'Welche Plattformen unterstützen Sie?', a: 'Wir arbeiten mit Streamern auf Twitch, YouTube, Kick und anderen großen Streaming-Plattformen. Wenn Sie eine aktive Zielgruppe auf einer Streaming-Plattform haben, möchten wir von Ihnen hören.' },
        { q: 'Was ist, wenn ich weniger als 5.000 Follower habe?', a: 'Wir arbeiten gelegentlich mit kleineren Creatorn zusammen, die außergewöhnliche Engagement-Raten aufweisen. Bewerben Sie sich trotzdem, und unser Team wird Ihr Profil prüfen. Die Qualität der Zielgruppe ist wichtiger als rohe Zahlen.' },
        { q: 'Was für Content muss ich erstellen?', a: 'Gesponserte Streams mit iGaming- und Krypto-Casino-Marken. Das spezifische Format und die Anforderungen variieren je nach Marke, aber wir arbeiten immer mit Ihnen zusammen, um sicherzustellen, dass der Content natürlich und authentisch wirkt.' },
        { q: 'Wie lange sind die Verträge?', a: 'Die meisten Deals laufen monatlich ohne langfristige Bindung. Einige Premium-Partnerschaften können 3-6 Monate laufen, aber Sie kennen die Bedingungen immer im Voraus, bevor Sie sich verpflichten.' },
        { q: 'Erheben Sie Provision?', a: 'Wir werden von den Marken bezahlt, nicht von Ihnen. Der Betrag, den wir für Sie aushandeln, ist das, was Sie erhalten. Es gibt keine versteckten Gebühren oder Abzüge von Ihren Einnahmen.' },
        { q: 'Kann ich gleichzeitig mit anderen Agenturen arbeiten?', a: 'Ja. Wir haben keine Exklusivitätsanforderungen. Sie können frei mit anderen Agenturen arbeiten und Direktverträge abschließen. Wir bitten nur darum, dass Sie aktive Kampagnenverpflichtungen einhalten.' },
        { q: 'Wie lange dauert der Bewerbungsprozess?', a: 'Typischerweise 2-5 Werktage. Wir überprüfen Ihren Kanal, verifizieren Ihre Zielgruppen-Kennzahlen, und wenn Sie genehmigt werden, könnten Sie innerhalb einer Woche Ihren ersten Marken-Deal erhalten.' },
      ],
    },
    form: {
      title: 'Jetzt',
      titleHighlight: 'Bewerben',
      subtitle: 'Füllen Sie das Formular aus und unser Team wird Ihre Bewerbung prüfen',
      fullName: 'Vollständiger Name *',
      emailAddress: 'E-Mail-Adresse *',
      primaryPlatform: 'Hauptplattform *',
      followerCount: 'Follower-Anzahl *',
      profileUrl: 'Profil / Kanal-URL *',
      telegramHandle: 'Telegram-Handle (optional)',
      describeContent: 'Beschreiben Sie Ihren Content *',
      selectPlatform: 'Plattform auswählen',
      selectRange: 'Bereich auswählen',
      namePlaceholder: 'Ihr Name',
      contentPlaceholder: 'Erzählen Sie uns von Ihrem Content, Ihrer Zielgruppe und welche Art von Marken-Deals Sie interessieren...',
      submitButton: 'Bewerbung Einreichen',
      successTitle: 'Bewerbung Gesendet',
      successBody: 'Ihr E-Mail-Client wurde mit Ihren Bewerbungsdetails geöffnet. Senden Sie die E-Mail, um Ihre Einreichung abzuschließen. Wir werden Ihr Profil prüfen und uns innerhalb von 2-5 Werktagen bei Ihnen melden.',
      submitAnother: 'Weitere Bewerbung Einreichen',
    },
    whyJoin: {
      title: 'Warum Unserem',
      titleHighlight: 'Netzwerk Beitreten',
      subtitle: 'Wir haben das für Creator aufgebaut, die unreliable Deals und niedrige Angebote satt haben',
      items: [
        { title: 'Kontinuierliche Deals', desc: 'Monatlich wiederkehrende iGaming-Sponsorings, damit Sie immer Casino-Marken-Deals haben. Keine Jagd nach Einzel-Kampagnen mehr.' },
        { title: 'Bessere Konditionen', desc: 'Wir verhandeln Premium-Konditionen in Ihrem Namen mit unserem Netzwerk-Hebel. Verdienen Sie mehr pro Stunde Content als alleine.' },
        { title: 'Wir Übernehmen das Geschäft', desc: 'Verträge, Rechnungsstellung, Verhandlungen, Compliance. Wir verwalten den Papierkram, damit Sie sich auf das Streamen konzentrieren können.' },
        { title: 'Schnelle Zahlungen', desc: 'Bezahlt werden in 7-14 Tagen. Keine monatelange Jagd nach Marken. Wir garantieren pünktliche, zuverlässige Auszahlungen.' },
        { title: 'Gaming-Freundliche Marken', desc: 'Arbeiten Sie mit seriösen iGaming- und Krypto-Casino-Marken, Sportwetten-Plattformen und Spielunternehmen, die zu Ihrer Zielgruppe passen.' },
        { title: 'Keine Bindung', desc: 'Arbeiten Sie mit uns zu Ihren Konditionen. Keine Exklusivitätsverträge. Sie können mit anderen Agenturen und Marken zusammenarbeiten.' },
      ],
    },
    whatYouGet: {
      badge: 'Kernfunktionen',
      title: 'Der',
      titleHighlight: 'Octo-Vorteil',
      subtitle: 'Alles, was Sie brauchen, um Ihren Content professionell zu monetarisieren und Ihr Creator-Business zu skalieren',
      items: [
        { title: 'Wiederkehrende Partnerschaften', desc: 'Langfristige Marken-Deals, die stabiles, vorhersehbares Einkommen Monat für Monat liefern.' },
        { title: 'Premium-Konditionen', desc: 'Unser Volumen und unsere Reputation ermöglichen es uns, höhere CPMs und Pauschalraten zu verhandeln als Sie es alleine könnten.' },
        { title: 'Vollständiger Service', desc: 'Dedizierter Partnerschaftsmanager, Vertragsabwicklung, kreative Briefings und Compliance-Unterstützung.' },
        { title: 'Schnelle Zahlungen', desc: '7-14 Tage Zahlungszyklen. Kein Warten 60-90 Tage. Wir zahlen pünktlich, jedes Mal.' },
        { title: 'Gezieltes Marken-Matching', desc: 'Werden Sie mit iGaming- und Krypto-Casino-Marken zusammengebracht, die bei Ihrer spezifischen Zielgruppe ankommen.' },
        { title: 'Flexibilität', desc: 'Keine Exklusivität. Arbeiten Sie mit mehreren Marken und Agenturen. Skalieren Sie nach oben oder unten zu Ihren Konditionen.' },
      ],
    },
    eligibility: {
      title: 'Eignungs-',
      titleHighlight: 'Anforderungen',
      subtitle: 'Stellen Sie sicher, dass Sie die Grundvoraussetzungen vor der Bewerbung erfüllen',
      items: [
        { title: '5.000+ Follower', desc: 'Mindest-Follower-Anzahl auf Ihrer primären Streaming-Plattform.' },
        { title: 'Gaming / Gambling Content', desc: 'Ihr Content sollte Gaming- oder Gambling-bezogen sein, um zu unseren Markenpartnern zu passen.' },
        { title: 'Präsenz auf Hauptplattform', desc: 'Aktiv auf Twitch, YouTube, Kick oder ähnlichen großen Streaming-Plattformen.' },
        { title: 'Authentisches Engagement', desc: 'Echte Zuschauer und echte Interaktion. Wir verifizieren Engagement-Qualität, nicht nur Zahlen.' },
        { title: 'Globale Verfügbarkeit', desc: 'Wir arbeiten mit Streamern weltweit. Alle Regionen und Sprachen sind willkommen.' },
        { title: 'Konsistenter Zeitplan', desc: 'Regelmäßiger Streaming-Zeitplan mit zuverlässiger Content-Produktion und Zielgruppen-Bindung.' },
      ],
    },
    comparison: {
      badge: 'Die Klare Wahl',
      title: 'Traditionelle Agenturen vs',
      titleHighlight: 'Octo Media',
      subtitle: 'Sehen Sie, warum Tausende von Streamern von traditionellen Talent-Agenturen zu unserer Creator-First-Plattform wechseln',
      traditionalLabel: 'Traditionell',
      traditionalAgency: 'Traditionelle Agentur',
      octoMedia: 'Octo Media',
      metrics: [
        { label: 'Provisionssatz', traditional: '20-40%', us: '10%' },
        { label: 'Zahlungszeitraum', traditional: '60-90 Tage', us: 'Gleicher Tag' },
        { label: 'Vertragslaufzeit', traditional: '12-24 Monate', us: 'Keine Bindung' },
        { label: 'Durchschnittlicher Deal-Wert', traditional: '$2-5K/Monat', us: '$8-15K/Monat' },
      ],
      features: [
        { category: 'Exklusivität', traditional: 'Erforderlich - Keine Arbeit mit anderen Agenturen', us: 'Optional - Frei mit mehreren Partnern arbeiten' },
        { category: 'Vorabkosten', traditional: 'Einrichtungsgebühren, monatliche Abonnements', us: 'Null Vorabkosten oder versteckte Gebühren' },
        { category: 'Marken-Überprüfung', traditional: 'Minimales Screening, Zahlungsverzögerungen üblich', us: '100% geprüfte Marken, garantierte Zahlungen' },
        { category: 'Persönliche Betreuung', traditional: 'Geteilter Manager für 50+ Creator', us: 'Dedizierter 24/7 persönlicher Manager' },
        { category: 'Deal-Flexibilität', traditional: 'Nur Standardpakete', us: 'Individuelle Deals nach Ihren Präferenzen' },
        { category: 'Vertragsausstieg', traditional: 'Strafen und Kündigungsfristen', us: 'Jederzeit aussteigen, keine Strafen' },
        { category: 'Karriere-Unterstützung', traditional: 'Beschränkt auf Deal-Vermittlung', us: 'Vollständige Markenaufbau- und Wachstumsunterstützung' },
      ],
      highlights: ['Niedrigere Provision', 'Schnellere Zahlungen', 'Höhere Einnahmen'],
    },
  },
  whyUsPage: {
    hero: {
      badge: 'WARUM OCTOMEDIA',
      title: 'Aufgebaut von Casino-Insidern,\nNicht von Marketing-Außenseitern',
      subtitle: 'OctoMedia wurde von acht iGaming-Veteranen gegründet, die Jahre in echten Casinos und Krypto-Casino-Plattformen verbracht haben — mit der Verwaltung von Akquisitionen, Retention, Launches und Compliance. Die einzige iGaming-Marketing-Agentur, die streamer-spezifischen Fokus, Krypto-Casino-Spezialisierung und ein Ex-Betreiber-Gründerteam kombiniert. Wir verstehen FTDs, LTV und Retention, weil wir daran gemessen wurden.',
      point1: 'Ex-Casino & Krypto-Casino-Fachleute',
      point2: 'iGaming Streamer-Marketing-Spezialisten',
      point3: 'Compliance-Bewusstes Skalieren',
    },
    differentiators: {
      title: 'Was Uns Unterscheidet',
      subtitle: 'OctoMedia ist nicht einfach eine weitere Marketing-Agentur. Wir sind anders aufgebaut, weil wir aus dem Inneren der Branche kommen.',
      items: [
        { title: 'Betreiber-Denkweise', description: 'Wir denken wie Casino-Betreiber, weil wir Casino-Betreiber waren. Jede Entscheidung wird durch reale KPIs und operative Einschränkungen gefiltert.' },
        { title: 'FTD-, LTV- & Retention-Fokus', description: 'Wir optimieren für Kennzahlen, die zählen: Ersteinzahlungen, Lebenszeitwert, Zweiteinzahlungsraten und langfristige Spieler-Retention.' },
        { title: 'Datengesteuertes Influencer-Marketing', description: 'Keine Eitelkeitskennzahlen. Wir tracken Konversionsraten, Kosten pro FTD und Zielgruppenqualität bei jedem Streamer und Content-Creator.' },
        { title: 'Compliance-Bewusstes Skalieren', description: 'Wachstumsstrategien mit regulatorischem Bewusstsein. Wir wissen, welche Märkte sorgfältige Kommunikation erfordern und welche Influencer Compliance-Risiken darstellen.' },
        { title: 'Zugang zum Branchennetzwerk', description: 'Direkte Beziehungen zu Top-Streamern, Affiliate-Netzwerken und Media-Buyern, die iGaming und Krypto-Casinos wirklich verstehen.' },
        { title: 'Langfristiger Markenwert', description: 'Wir balancieren aggressive Akquisition mit nachhaltigem Markenaufbau. Kurzfristige Gewinne ohne langfristigen Schaden.' },
      ],
    },
    foundingStory: {
      title: 'Wie Wir Gestartet Sind',
      body1: 'Wir trafen uns in verschiedenen Casino-Rollen — Akquisitionsleiter, Retention-Manager, Affiliate-Manager, Compliance-Strategen. Einige von uns haben Krypto-Casinos von Null an aufgebaut. Andere haben etablierte Marken in mehreren GEOs skaliert.',
      body2: 'Die gemeinsame Frustration? Marketing-Agenturen, die iGaming nicht wirklich verstanden.',
      body3: 'Sie verkauften "Bewusstsein" und "Engagement", während wir an Ersteinzahlungen, Zweiteinzahlungsraten und Lebenszeitwert gemessen wurden. Sie sprachen nicht die Sprache von CPA-Deals, Bonus-Missbrauch-Schutz oder regulatorischen Risiken.',
      body4: 'Also haben wir OctoMedia aufgebaut — eine Agentur, die von Menschen geführt wird, die bereits auf der Betreiberseite waren. Wir wissen, was funktioniert, weil wir Budgets eingesetzt, Influencer-Kampagnen verwaltet und Funnels unter echtem Druck optimiert haben.',
      closing: 'Wir raten nicht. Wir haben es bereits getan.',
      cards: [
        { heading: 'Woher Wir Kommen', text: 'Wir trafen uns in verschiedenen Casino-Rollen — Akquisitionsleiter, Retention-Manager, Affiliate-Manager, Compliance-Strategen. Einige von uns haben Krypto-Casinos von Null an aufgebaut.' },
        { heading: 'Die Frustration', text: 'Marketing-Agenturen, die iGaming nicht wirklich verstanden. Sie verkauften "Bewusstsein" und "Engagement", während wir an Ersteinzahlungen und Lebenszeitwert gemessen wurden.' },
        { heading: 'Die Lücke, Die Wir Sahen', text: 'Sie sprachen nicht die Sprache von CPA-Deals, Bonus-Missbrauch-Schutz oder regulatorischen Risiken. Niemand überbrückte die Lücke zwischen Influencer-Marketing und echten Betreiber-KPIs.' },
        { heading: 'Warum Wir OctoMedia Aufgebaut Haben', text: 'Eine Agentur, die von Menschen geführt wird, die bereits auf der Betreiberseite waren. Wir wissen, was funktioniert, weil wir Budgets eingesetzt und Funnels unter echtem Druck optimiert haben.' },
      ],
    },
    foundingTeam: {
      title: 'Das Gründerteam Kennenlernen',
      subtitle: 'Acht Casino-Veteranen, die ihre Karriere im Inneren der Branche aufgebaut haben, nicht außerhalb.',
      yearsLabel: 'Jahre',
      exLabel: 'Ehem.:',
      strengthLabel: 'Stärke:',
    },
    closing: {
      badge: 'DER UNTERSCHIED IST KLAR',
      title: 'Wir Waren Bereits\nIm Inneren von iGaming',
      subtitle: 'OctoMedia wurde von Menschen aufgebaut, die Casino- und Krypto-Casino-Akquisitionen geleitet, iGaming-Influencer-Kampagnen im Millionenbereich verwaltet und Retention-Funnels unter echtem Druck optimiert haben. Wir verstehen iGaming-Streamer-Marketing nicht nur — wir haben es gelebt.',
      cta1: 'Streamer-Partnerschaften Erkunden',
      cta2: 'Kontakt Aufnehmen',
      stat1Value: '8',
      stat1Label: 'Gründungsveteranen',
      stat2Value: '62',
      stat2Label: 'Kombinierte Jahre Erfahrung',
      stat3Value: '100%',
      stat3Label: 'Ex-Casino-Fachleute',
    },
  },
  servicesPage: {
    badge: 'UNSERE LEISTUNGEN',
    heroBadge: 'iGaming Marketing-Leistungen',
    heroTitle: 'Performance-Marketing Entwickelt für',
    heroTitleHighlight: 'iGaming-Betreiber',
    heroSubtitle: 'Drei bewährte Akquisitionskanäle — Streamer-Kampagnen, Affiliate-Programme und Influencer-Marketing — vollständig von erfahrenen Casino-Betreibern verwaltet.',
    tab1: 'Streamer-Marketing',
    tab2: 'Affiliate-Marketing',
    tab3: 'Influencer-Marketing',
    howItWorksLabel: 'Wie es Funktioniert',
    whatYouGetLabel: 'Was Sie Erhalten',
    inlineCta1: 'Möchten Sie Streamer-Ergebnisse sehen, bevor Sie ein volles Budget einsetzen?',
    inlineCta2: 'Bereit, ein compliant, hochkonvertierendes Affiliate-Programm aufzubauen?',
    inlineCtaNote: 'Keine langfristige Verpflichtung erforderlich. Ergebnisse sehen, bevor Sie skalieren.',
    inlineCtaBtn: 'Kostenlosen Strategie-Call Buchen',
    closingBadge: 'Null Langfristige Verpflichtung',
    trustSignals: ['Keine langfristigen Verträge', '100% Ausgabentransparenz', 'Ergebnisse in 2 Wochen', 'Dedizierter Account-Manager'],
    stats: [
      { value: '25+', label: 'Abgedeckte Märkte' },
      { value: '750+', label: 'Verifizierte Streamer' },
      { value: '3–5x', label: 'Durchschnittlicher ROI' },
      { value: '2 Wochen', label: 'Erste Ergebnisse' },
    ],
    streamerSection: {
      badge: 'Casino-Streamer-Marketing',
      title: 'Verifizierte Streamer.',
      titleHighlight: 'Bewährte Einzahlungen.',
      subtitle: 'Twitch · YouTube · Kick — 25+ Märkte',
      positioning: 'Jeder Streamer in unserem Netzwerk wird manuell aus iGaming-Nischen ausgewählt, auf echtes Zielgruppen-Engagement geprüft und nur mit Marken zusammengeführt, für die er bereits konvertiert. Wir übernehmen die End-to-End-Ausführung — vom Compliance-Briefing bis zu wöchentlichen ROI-Berichten.',
      accordion1Label: 'Was in einer Streamer-Kampagne enthalten ist',
      accordion1Items: [
        'Verifizierte Casino-Streamer auf Twitch, YouTube und Kick',
        'Compliance-konforme Kampagnen mit Standards für verantwortungsvolles Spielen',
        'KPI-basierte Ausführung: FTDs, Einzahlungen, Spieler-Retention & Cost-per-Acquisition',
        'Wöchentliche ROI-Berichte pro Streamer — vollständige Ausgaben- vs. Ergebnistransparenz',
        'Krypto-Casino-, Online-Casino- & Sportwetten-Markenexpertise',
        'Abdeckung auf 25+ Märkten — Europa, LATAM, Nordamerika, Ozeanien & APAC',
      ],
      accordion2Label: 'Plattformen & Compliance',
      accordion2Items: [
        'Live-Streaming-Kampagnen auf Twitch, YouTube Live & Kick gleichzeitig',
        'Geo-zielgerichtete Streamer-Auswahl für Ihre lizenzierten Märkte',
        'Verantwortungsvolles-Glücksspiel-Disclaimers in jeden Kampagnen-Brief eingebettet',
        'Altersverifizierungs-Zielgruppenfilter vor dem Go-Live angewendet',
        'Inhalte gegen UK, MGA, Curaçao & lokale Regulierungsstandards überprüft',
      ],
      steps: [
        { num: '01', title: 'Briefing & Marken-Match', desc: 'Wir analysieren Ihre Ziel-GEOs, Spielerprofil und Compliance-Anforderungen für ein präzises Creator-Briefing.' },
        { num: '02', title: 'Streamer-Sourcing', desc: 'Handverlesen aus unserem verifizierten Netzwerk — gematcht nach Nische, Zielgruppen-Geo und Einzahlungs-Konversionshistorie.' },
        { num: '03', title: 'Live-Kampagnen-Ausführung', desc: 'Streamer gehen live mit strukturiertem Gameplay, markengerechtem Content und authentischer Promotion für kaufbereite Spieler.' },
        { num: '04', title: 'Echtzeit-Tracking', desc: 'Dashboard-Zugang + wöchentliche Berichte: FTDs, Einzahlungen, Kosten pro Spieler, Retention und ROI-Aufschlüsselung.' },
        { num: '05', title: 'Skalieren & Binden', desc: 'Top-Performer verdoppeln, Retention-Mechanismen aktivieren und in angrenzende Märkte expandieren.' },
      ],
      featureTexts: [
        'Bot-freie Zielgruppen — manuell verifiziert vor Onboarding',
        'KPI-gesteuerte Ausführung: FTDs, Einzahlungen & Cost-per-Acquisition',
        'Wöchentliche ROI-Berichte pro Streamer, Ausgaben vs. Ergebnisse',
        '25+ Märkte — Europa, LATAM, Nordamerika, APAC & Ozeanien',
        'Compliance-first Briefing im Einklang mit Gesetzen zum verantwortungsvollen Spielen',
        'Multi-Plattform: Twitch, YouTube & Kick gleichzeitig',
      ],
    },
    affiliateSection: {
      badge: 'iGaming Affiliate-Marketing',
      title: 'Affiliate-Programme',
      titleHighlight: 'Die Wirklich Konvertieren.',
      subtitle: 'CPA · Umsatzbeteiligung · Hybrid — Betreiber-Gebaut',
      positioning: 'Entwickelt von Menschen, die Affiliate-Kanäle von der Betreiberseite aus verwaltet haben. Wir gestalten Provisionsstrukturen rund um reale Spielerökonomie — keine aufgeblähten Klickzahlen — und verwalten jede Partnerschaft mit Live-Tracking und transparenter Cost-per-FTD-Berichterstattung.',
      accordion1Label: 'Was im Affiliate-Management enthalten ist',
      accordion1Items: [
        'Leistungsbasierte CPA-, Umsatsbeteiligungs- & Hybrid-Provisionsmodelle',
        'Glücksspiel-konforme Kreativmaterialien und geo-zielgerichtete Landing Pages',
        'Community-Aufbau und Engagement-Strategien für langfristige Spieler-Retention',
        'Echtzeit-Affiliate-Tracking und transparentes Konversionsreporting',
        'Compliance-bewusstes iGaming-Affiliate-Programmmanagement',
        'Skalierbare Affiliate-Infrastruktur vom Startup bis zur Enterprise-Marke',
      ],
      accordion2Label: 'Reporting & Transparenz',
      accordion2Items: [
        'Echtzeit-Dashboard-Zugang für alle aktiven Affiliate-Partnerschaften',
        'Wöchentliche Aufschlüsselungen: Klicks, Registrierungen, FTDs, Einzahlungsvolumen & CPA',
        'Segmentierung nach Affiliate und GEO',
        'Betrugserkennung und Traffic-Qualitätsmonitoring',
        'Monatlicher Strategie-Review und Programm-Optimierungsgespräche',
      ],
      featureTexts: [
        'CPA-, Umsatsbeteiligungs- & Hybrid-Modelle um reale Betreiberökonomie herum entwickelt',
        'Compliance-konforme Kreativmaterialien und geo-zielgerichtete Landing Pages',
        'Echtzeit-Konversionstracking und transparente Berichterstattung',
        'Community-Aufbau-Strategien für langfristige Spieler-Retention',
        'Skalierbare Infrastruktur vom Frühstadium bis zum Enterprise-Betreiber',
        'Affiliate-Programmmanagement von erfahrenen Casino-Akquisitionsleitern',
      ],
    },
    influencerSection: {
      badge: 'Glücksspiel-Influencer-Marketing',
      title: 'High-LTV-Spieler',
      titleHighlight: 'Von Vertrauenswürdigen Creatorn.',
      subtitle: 'YouTube · TikTok · Twitch · Kick — Performance-First',
      positioning: 'Wir paaren iGaming- und Krypto-Casino-Marken mit verifizierten Glücksspiel-Influencern, deren Zielgruppen bereits mit Casino-Content interagieren. Jede Kampagne ist auf echte einzahlende Spieler ausgerichtet — nicht auf Vanity-Impressions — mit vollständigem Konversionstracking vom ersten Klick bis zur zweiten Einzahlung.',
      accordion1Label: 'Was in Influencer-Kampagnen enthalten ist',
      accordion1Items: [
        'Verifiziertes Glücksspiel-Influencer-Netzwerk auf YouTube, TikTok, Twitch & Kick',
        'End-to-End iGaming-Influencer-Kampagnenmanagement vom Briefing bis zum ROI-Bericht',
        'Markenbekanntheit und Spielergewinnungsmodelle für Casino & Sportwetten',
        'Zielgruppen-abgestimmte Creator-Auswahl nach Geo, Nische & iGaming-Content-Geschichte',
        'Compliance-konforme Influencer-Briefings gemäß Verantwortlichem-Glücksspiel-Regelungen',
        'Vollständiges Konversionstracking: FTDs, Einzahlungen, LTV & Cost-per-acquired-Player',
      ],
      accordion2Label: 'Creator-Vetting-Prozess',
      accordion2Items: [
        'Manuelle Prüfung von Zielgruppen-Demografie, Engagement-Raten & Geo-Verteilung',
        'Historische Leistungsüberprüfung: vergangene iGaming-Kampagnen-Konversionsdaten',
        'Bot- und Fake-Follower-Screening über Drittanbieter-Analysetools',
        'Marken-Alignment-Check: Content-Stil, Ton und Zielgruppen-Absicht',
        'Compliance-Geschichts-Review vor jeder Markenvorstellung',
      ],
      featureTexts: [
        'Verifiziertes Netzwerk auf YouTube, TikTok, Twitch & Kick',
        'Zielgruppen-abgestimmte Creator-Auswahl nach Geo, Nische & iGaming-Geschichte',
        'Compliance-konforme Influencer-Briefings gemäß Glücksspiel-Regelungen',
        'Vollständiges Konversionstracking: FTDs, LTV & Cost-per-Player',
        'Markenbekanntheit + direkte Akquisitionsmodelle verfügbar',
        'End-to-End-Management vom Brief bis zur Post-Kampagnen-Analyse',
      ],
    },
    title: 'iGaming Influencer-Marketing-Leistungen',
    subtitle: 'Performance-getriebenes Casino-Streamer-Marketing, Glücksspiel-Influencer-Kampagnen und iGaming-Affiliate-Programme — entwickelt von Branchenkennern für Krypto-Casino-, Online-Casino- und Sportwetten-Marken weltweit.',
    services: [
      {
        id: 'streamer-marketing',
        title: 'iGaming Streamer-Marketing',
        description: 'Unser Flagship-Casino-Streamer-Marketing-Service verbindet iGaming-, Krypto-Casino- und Sportwetten-Marken mit verifizierten, hochperformanten Glücksspiel-Streamern auf Twitch, YouTube und Kick. Im Gegensatz zu generischen Influencer-Agenturen wird jeder Streamer in unserem Netzwerk manuell auf echtes Zielgruppen-Engagement, geografisches Targeting und eine nachgewiesene Erfolgsbilanz bei der Gewinnung von Ersteinzahlungen (FTDs) im iGaming-Bereich geprüft. Wir übernehmen das End-to-End-Kampagnenmanagement — von Streamer-Sourcing und Compliance-Briefing bis hin zu Live-Content-Umsetzung und wöchentlichen ROI-Berichten.',
        cta: 'Kostenlosen Wachstumsplan Erhalten',
        features: ['Verifizierte Twitch-Casino-Streamer, YouTube-Glücksspiel-Influencer & Kick-Streamer', 'Compliance-konforme Casino-Influencer-Kampagnen mit Verantwortlichem-Glücksspiel-Standards', 'KPI-basierte Umsetzung: FTDs, Einzahlungen, Spieler-Retention & Cost-per-Acquisition', 'Wöchentliche ROI-Berichte pro Streamer — vollständige Ausgaben-vs-Ergebnis-Transparenz', 'Krypto-Casino-, Online-Casino- & Sportwetten-Marken-Expertise', 'Abdeckung auf 25+ Märkten — Europa, LATAM, Nordamerika, Ozeanien & APAC'],
      },
      {
        id: 'affiliate-marketing',
        title: 'iGaming Affiliate-Marketing',
        description: 'Wir entwickeln und verwalten leistungsbasierte Affiliate-Marketing-Programme für iGaming-Marken, einschließlich Krypto-Casinos, Online-Casinos und Sportwetten-Plattformen. Unser iGaming-Affiliate-Ansatz basiert auf echter Betreiberfahrung — wir entwerfen CPA-, Umsatzbeteiligungs- und Hybrid-Provisionsmodelle, die eine nachhaltige Spielergewinnung zu kontrollierten Kosten pro FTD ermöglichen. Jede Affiliate-Partnerschaft wird mit compliance-konformen Kreativmaterialien, Echtzeit-Konversionstracking und transparentem Reporting verwaltet.',
        cta: 'Affiliate-Strategie Besprechen',
        features: ['Leistungsbasierte CPA-, Umsatsbeteiligungs- & Hybrid-Provisionsmodelle', 'Glücksspiel-konforme Kreativmaterialien und geo-zielgerichtete Landing Pages', 'Community-Aufbau und Engagement-Strategien für langfristige Spieler-Retention', 'Echtzeit-Affiliate-Tracking und transparentes Konversionsreporting', 'Compliance-bewusstes iGaming-Affiliate-Programmmanagement', 'Skalierbare Affiliate-Infrastruktur vom Startup bis zur Enterprise-Casino-Marke'],
      },
      {
        id: 'influencer-marketing',
        title: 'iGaming Influencer-Marketing',
        description: 'Strategische Glücksspiel-Influencer-Marketing-Kampagnen, speziell entwickelt für iGaming- und Krypto-Casino-Plattformen. Wir verbinden Marken mit verifizierten Casino-Influencern, YouTube-Glücksspiel-Kanälen, TikTok-Casino-Creatorn und Kick-Streamern mit authentischen Zielgruppen im Online-Gaming- und Krypto-Bereich — für messbare Markenbekanntheit, Spielergewinnung und hohe LTV-Retention durch vertrauenswürdige Creator-Beziehungen. Unsere Strategie ist von Tag eins an leistungsorientiert: Jede Kampagne ist darauf ausgerichtet, echte einzahlende Spieler zu liefern.',
        cta: 'Influencer-Kampagne Planen',
        features: ['Verifiziertes Glücksspiel-Influencer-Netzwerk auf YouTube, TikTok, Twitch & Kick', 'End-to-End iGaming-Influencer-Kampagnenmanagement vom Briefing bis zum ROI-Bericht', 'Markenbekanntheit und Spielergewinnungsmodelle für Casino & Sportwetten', 'Zielgruppen-abgestimmte Creator-Auswahl nach Geo, Nische & iGaming-Content-Geschichte', 'Compliance-konforme Influencer-Briefings gemäß Verantwortlichem-Glücksspiel-Regelungen', 'Vollständiges Konversionstracking: FTDs, Einzahlungen, LTV & Cost-per-acquired-Player'],
      },
    ],
    whatsIncluded: 'Was Inbegriffen Ist:',
    closing: {
      title: 'Bereit, Ihre iGaming-Spielergewinnung zu Skalieren?',
      body: 'Buchen Sie einen kostenlosen 30-minütigen Strategie-Call. Wir werden Ihre aktuelle Spielergewinnungsstrategie prüfen und Ihnen genau zeigen, wie unser Casino-Influencer-Marketing und Glücksspiel-Streamer-Kampagnen echte einzahlende Spieler bei messbarem ROI liefern können.',
      cta1: 'Kostenlosen Strategie-Call Buchen',
      cta2: 'Casino-Streamer Buchen',
    },
  },
  resourcesPage: {
    badge: 'iGaming Marketing-Ressourcen',
    title: 'iGaming Influencer-Marketing-Leitfäden',
    subtitle: 'Ausführliche Ressourcen zur Casino-Influencer-Marketing-Strategie, Glücksspielwerbungs-Compliance, ROI-Messung und Krypto-Casino-Marketing-Trends — verfasst von iGaming-Branchenkennern.',
    readTime: 'Min. Lesen',
    ctaTitle: 'Bereit, Diese Strategien Anzuwenden?',
    ctaBody: 'Unser iGaming-Marketing-Team implementiert diese Strategien täglich für Krypto-Casino- und Online-Casino-Marken. Buchen Sie eine kostenlose 30-Minuten-Beratung.',
    ctaButton: 'Kostenlosen Strategie-Call Buchen',
    articles: [
      { badge: 'Strategie', title: 'ROI von iGaming Influencer-Marketing: Was Marken Tatsächlich Erhalten', description: 'Eine datengestützte Analyse echter ROI-Kennzahlen, Cost-per-FTD-Benchmarks und Kampagnenleistungsmessung für Casino-Influencer-Marketing.', readTime: 8 },
      { badge: 'Compliance', title: 'Glücksspiel-Influencer-Marketing-Compliance: UK, Malta, Curacao & USA', description: 'Region-für-Region-Übersicht der Casino-Werberegelungen, Verantwortliches-Glücksspiel-Anforderungen und konforme Kampagnenrahmen.', readTime: 10 },
      { badge: 'Vergleich', title: 'Affiliate vs. Influencer-Marketing für iGaming: Was Liefert Besseren ROI?', description: 'Ein direkter Vergleich von iGaming-Affiliate-Programmen vs. Influencer-Kampagnen — Kostenstrukturen, Konversionsraten und Einsatzszenarien.', readTime: 7 },
      { badge: 'Trends', title: 'Krypto-Casino Marketing-Trends 2026: Streamer, Web3 & Spielergewinnung', description: 'Die neuesten Trends im Krypto-Casino- und Blockchain-Glücksspiel-Marketing — von Twitch-Streamern bis zu Web3-nativen Influencer-Kampagnen.', readTime: 9 },
      { badge: 'Plattform-Leitfaden', title: 'Twitch Casino-Marketing: Der Vollständige Marken-Leitfaden für 2026', description: 'Effektive Twitch-Casino-Sponsorings — Glücksspiel-Streamer finden, Deals strukturieren, Compliance und ROI-Tracking.', readTime: 11 },
      { badge: 'Strategie', title: 'Esports-Wetten Influencer-Marketing-Strategie für Sportwetten-Anbieter', description: 'Wie Sportwetten- und Esports-Wetten-Marken Gaming-Influencer, Esports-Streamer und Content-Creator nutzen können.', readTime: 8 },
    ],
  },
  faq: {
    title: 'Häufig Gestellte',
    titleHighlight: 'Fragen',
    subtitle: 'Alles, was Sie über verifiziertes Influencer-Media-Buying wissen müssen',
    items: [
      { q: 'Was unterscheidet Sie von anderen Agenturen?', a: 'Die meisten Agenturen verkaufen Reichweite. Wir liefern verifizierte Streamer, echte Spieler und messbaren ROI. Jede Kampagne ist auf Einzahlungen, Retention und LTV ausgerichtet — keine Eitelkeitskennzahlen.' },
      { q: 'Wie verifizieren Sie Streamer?', a: 'Streamer werden manuell für echtes Engagement, Zielgruppen-Geo und frühere iGaming-Leistung handverlesen und geprüft. Wir arbeiten nur mit Creatorn, die bereits bewiesen haben, dass sie Einzahlungen generieren können.' },
      { q: 'Was ist in der $10.000-Demo enthalten?', a: 'Ein 2-Wochen-Pilot mit 5-10 verifizierten Streamern, 10-15 Stunden Live-Content und einem vollständigen ROI-Performance-Bericht. Sie erhalten Beweise vor der Skalierung — keine langfristigen Verpflichtungen.' },
      { q: 'Welche Märkte bedienen Sie?', a: 'Wir sind in Europa, LATAM, Nordamerika und Ozeanien tätig und decken 25+ Märkte und 15+ Sprachen ab. Streamer werden immer basierend auf Geo, Zielgruppenverhalten und Marken-Fit zusammengeführt.' },
      { q: 'Mit welchen Plattformen arbeiten Sie?', a: 'Wir führen Kampagnen auf Twitch, YouTube, Kick und plattformnativen Streaming-Umgebungen durch. Multi-Plattform-Umsetzung gewährleistet Reichweite, Frequenz und höhere Konversionseffizienz.' },
      { q: 'Wie tracken Sie Ergebnisse?', a: 'Jede Kampagne wird End-to-End mit wöchentlichen Performance-Berichten getrackt. Sie sehen Ausgaben, FTDs, Einzahlungen, Retention und ROI — aufgeschlüsselt nach Streamer.' },
      { q: 'Was ist Ihr Preismodell?', a: 'Wir bieten feste Demo-Pilots und skalierbare monatliche Retainer an, je nach Ihrer Wachstumsphase. Keine versteckten Gebühren, keine vagen Preise — alles ist auf Leistungserbringung ausgerichtet.' },
      { q: 'Wie fange ich an?', a: 'Buchen Sie eine kostenlose 30-Minuten-Beratung, um Ihre Ziele und aktuelle Akquisitionsstrategie zu besprechen. Bei einem guten Match starten wir eine Demo und beweisen Ergebnisse vor der Skalierung.' },
      { q: 'Wie funktioniert Krypto-Casino-Streamer-Marketing?', a: 'Wir verbinden Krypto-Casino-Marken mit verifizierten Streamern, die nachgewiesene Zielgruppen im iGaming-Bereich haben. Streamer erstellen authentischen Live-Content, der Ihre Plattform präsentiert und echte Spieler gewinnt.' },
      { q: 'Was ist der ROI von iGaming-Influencer-Marketing?', a: 'Unsere Kunden sehen typischerweise 3-5x ROI bei iGaming-Streamer-Kampagnen, mit deutlich niedrigeren Kosten pro FTD als traditionelle Akquisitionskanäle. Vollständige Transparenz mit wöchentlichen Berichten.' },
      { q: 'Wie finden und verifizieren Sie Casino-Streamer?', a: 'Jeder Streamer in unserem Netzwerk wird manuell auf Zielgruppen-Authentizität, Engagement-Qualität, geografische Reichweite und frühere iGaming-Konversionsleistung geprüft.' },
      { q: 'Arbeiten Sie mit Krypto-Casino-Marken?', a: 'Ja. Krypto-Casino und Bitcoin-Casino-Marken sind ein Kernfokus. Wir spezialisieren uns darauf, Krypto-Glücksspiel-Plattformen mit Streamern zu verbinden, die Zielgruppen haben, die bereits in Kryptowährungen und Online-Gaming engagiert sind.' },
      { q: 'Welche Märkte und Geos decken Sie ab?', a: 'Wir decken 25+ Märkte in Dubai, Europa (UK, Deutschland, Malta), Nordamerika (Kanada, USA), Ozeanien (Australien, Neuseeland), Asien-Pazifik (Taiwan) und aufstrebende LATAM-Märkte ab.' },
      { q: 'Was kostet iGaming-Streamer-Marketing?', a: 'Wir bieten einen $10.000-Demo-Pilot für Marken an, die unseren Ansatz ohne langfristige Verpflichtung testen möchten. Skalierbare monatliche Retainer beginnen ab diesem Niveau.' },
    ],
  },
  lang: {
    switcher: 'Sprache',
    en: 'English',
    ru: 'Русский',
    es: 'Español',
    uk: 'Українська',
    sv: 'Svenska',
    de: 'Deutsch',
    fr: 'Français',
  },
};

export default de;
