const en = {
  meta: {
    home: {
      title: 'Best iGaming Influencer Marketing Agency 2026 | Octo Media',
      description: 'Top-rated iGaming influencer & casino streamer marketing agency. Verified Twitch, YouTube & Kick streamers. Proven ROI for casino brands.',
    },
    services: {
      title: 'iGaming Influencer Marketing Services | Octo Media 2026',
      description: 'Expert casino influencer marketing, gambling streamer campaigns & iGaming affiliate services. Proven player acquisition for crypto casino & sportsbook brands worldwide.',
    },
    streamers: {
      title: 'Hire Casino Streamers on Twitch, YouTube & Kick | Octo Media',
      description: 'Join the top iGaming streamer network. Get consistent gambling sponsorships, higher rates & faster payments. Twitch, YouTube & Kick casino streamers — apply today.',
    },
    whyUs: {
      title: 'Expert iGaming Marketing Agency — Built by Casino Insiders',
      description: 'Octo Media Group: 8 iGaming veterans delivering compliant casino influencer marketing with proven FTD results, full ROI transparency & performance accountability.',
    },
    resources: {
      title: 'iGaming Marketing Resources & Guides | Octo Media Group',
      description: 'Expert iGaming influencer marketing guides: compliance, ROI benchmarks, Twitch casino strategy, crypto casino trends, affiliate vs influencer comparison, and more.',
    },
    privacy: {
      title: 'Privacy Policy | Octo Media Group',
      description: 'Octo Media Group privacy policy. Learn how we collect, use, and protect your personal information.',
    },
    terms: {
      title: 'Terms of Service | Octo Media Group',
      description: 'Octo Media Group terms of service. Read the terms and conditions governing your use of our website and services.',
    },
    cookies: {
      title: 'Cookie Policy | Octo Media Group',
      description: 'Octo Media Group cookie policy. Learn about how we use cookies and similar technologies on our website.',
    },
  },
  nav: {
    home: 'Home',
    services: 'Services',
    ourStory: 'Our Story',
    forStreamers: 'For Streamers',
    faq: 'FAQ',
    contact: 'Contact',
    blog: 'Blog',
    caseStudies: 'Case Studies',
    whyJoin: 'Why Join',
    howItWorks: 'How It Works',
    apply: 'Apply',
    ctaGrowthPlan: 'Get a Free Growth Plan',
    ctaApplyNow: 'Apply Now',
    ctaGetInTouch: 'Get In Touch',
  },
  footer: {
    description: 'The leading iGaming influencer marketing agency. Performance-driven casino streamer campaigns and gambling influencer marketing for crypto casino, online casino, and sportsbook brands worldwide.',
    quickLinks: 'Quick Links',
    ourServices: 'Our Services',
    legal: 'Legal',
    contact: 'Contact',
    links: {
      agency: 'iGaming Marketing Agency',
      services: 'iGaming Marketing Services',
      whyOcto: 'Why Octo Media',
      hireStreamers: 'Hire Casino Streamers',
      faq: 'FAQ',
      contact: 'Contact',
    },
    serviceLinks: {
      streamer: 'Casino Streamer Marketing',
      affiliate: 'iGaming Affiliate Marketing',
      influencer: 'Gambling Influencer Marketing',
    },
    legalLinks: {
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      cookies: 'Cookie Policy',
    },
    telegram: '@OctoMediaGroup on Telegram',
    bottomText1: 'Octo Media Group is a specialist iGaming influencer marketing agency offering casino streamer marketing, gambling influencer marketing, and iGaming affiliate marketing for crypto casino, online casino, and sportsbook brands. We also operate a dedicated network for Twitch, YouTube & Kick casino streamers seeking consistent gambling sponsorships.',
    bottomText2: 'By using this website, you agree to our Terms of Service, Privacy Policy, and Cookie Policy. Your continued use constitutes acceptance of these policies.',
    copyright: 'All rights reserved. EU GDPR Compliant.',
  },
  hero: {
    headline1: 'iGaming Acquisition',
    headline2: 'Optimized for',
    headline3: 'High-LTV Yield',
    subheadline: 'The dedicated crypto casino streamer marketing agency trusted by leading iGaming brands worldwide. Performance-driven streamer & influencer marketing for iGaming and crypto casinos.',
    stat1Value: '$10M+',
    stat1Label: 'Revenue Generated',
    stat2Value: 'End-to-End',
    stat2Label: 'Campaign Execution',
    stat3Value: 'Acquisition',
    stat3Label: '& Retention',
    ctaPrimary: 'Schedule Free 30-Min Consultation',
    ctaSecondary: 'Explore Services',
    badge: 'Built By iGaming Veterans',
  },
  problem: {
    badge: 'The Industry Problem',
    title: 'The iGaming Influencer Marketing Problem',
    titleHighlight: 'We Solve',
    subtitle: 'iGaming brands waste millions on influencer campaigns that deliver vanity metrics instead of real players. Here\'s what the industry looks like without us:',
    items: [
      { stat: '70%', title: 'Wasted Budget', description: 'of influencer marketing budgets in iGaming are spent on creators with fake or irrelevant audiences' },
      { stat: '< 0.5%', title: 'Conversion Rate', description: 'is the average conversion rate from generic influencer campaigns -- barely a trickle of real depositing players' },
      { stat: 'NO', title: 'Accountability', description: 'No accountability about quality and quantity of results. No predictability. Most agencies offer zero transparent tracking or guarantees' },
    ],
    realityCheck: 'Reality Check',
    typicalMetrics: 'Typical Campaign Metrics',
    typicalSubtitle: 'What happens when you work with standard agencies',
    spent: 'Spent on campaign',
    signUps: 'Sign-ups received',
    ftds: 'FTDs converted',
    costPerFtd: 'Cost per FTD',
    secondDepositors: 'Second-time depositors',
    noRetention: 'No retention',
  },
  solution: {
    badge: 'What We Do Best',
    title: 'Our iGaming Marketing',
    titleHighlight: 'Expertise',
    subtitle: 'Covering Dubai, Europe, LATAM, North America, Oceania, and Asia-Pacific with verified streamers. We handle both player acquisition and retention for casino and crypto casino brands.',
    services: [
      { title: 'Streamer Marketing', description: 'Creator sourcing, KPI-based execution, multi-platform coverage across Twitch, YouTube, and Kick for both new player acquisition and long-term retention', tag1: 'Acquisition', tag2: 'Retention', link: 'Learn More' },
      { title: 'Affiliate Marketing', description: 'Market-targeted creatives, community building, and performance-based affiliate partnerships driving both player acquisition and retention', tag1: 'Acquisition', tag2: 'Retention', link: 'Learn More' },
      { title: 'Influencer Marketing', description: 'Strategic partnerships with high-impact influencers for brand awareness, player acquisition, and ongoing engagement through authentic content and campaigns', tag1: 'Acquisition', tag2: 'Retention', link: 'Learn More' },
    ],
  },
  howWeSolve: {
    badge: 'Our Process',
    title: 'How Our iGaming Streamer Marketing',
    titleHighlight: 'Works',
    subtitle: 'A rigorous five-step system that turns influencer spend into measurable, scalable revenue',
    fiveStep: 'five-step system',
    scalable: 'measurable, scalable revenue',
    cta: 'See It In Action',
    steps: [
      { title: 'Handpicked, Proven Streamers Only', description: 'We invite and onboard streamers manually — only from iGaming niches with verified past results, real audiences, and proven deposit performance.', highlight: 'Manually Vetted' },
      { title: 'Rigorous Vetting & Brand Matching', description: 'Every streamer is audited for engagement authenticity, audience demographics, and historical performance, then matched only with the type of brands they already convert for.', highlight: '100% Authentic' },
      { title: 'Controlled, High-Intent Live Campaigns', description: 'Streamers go live with structured gameplay, brand-safe presentation, and authentic promotion — designed to attract real, high-intent players, not vanity views.', highlight: 'High-Intent Only' },
      { title: 'Full ROI Transparency', description: 'Detailed weekly performance reports breaking down every dollar spent — streamer costs, FTDs, deposits, retention, and ROI — so results are clear and accountable.', highlight: 'Weekly Reports' },
      { title: 'Scale What Works, Retain What Converts', description: 'We double down on winning streamers and activate retention mechanics — leaderboards, bonuses, and community incentives — to drive repeat deposits and higher LTV.', highlight: 'Proven Scaling' },
    ],
  },
  comparison: {
    badge: 'The Difference',
    title: 'Why iGaming Brands Choose Us Over',
    titleHighlight: 'Standard Marketing Agencies',
    subtitle: 'Measurable metrics that prove a fundamentally different approach to iGaming marketing',
    standardAgency: 'Standard Agency',
    metrics: [
      { label: 'Retention' },
      { label: 'Conversion Rate' },
      { label: 'Time to First Results' },
      { label: 'Spend Transparency & Efficiency' },
    ],
    features: [
      { category: 'Streamer Vetting', standard: 'Unverified, mixed audiences', octo: '100% bot-free verified audiences' },
      { category: 'Campaign Support', standard: 'Monthly PDF reports', octo: 'Detailed weekly performance reports + dedicated manager' },
      { category: 'Market Coverage', standard: '1-2 regions', octo: '25+ markets, 15+ languages' },
      { category: 'Retention Strategy', standard: 'Not included', octo: 'Full retention & community programs' },
      { category: 'Platform Coverage', standard: 'Single platform focus', octo: 'Twitch, YouTube, Kick & more' },
    ],
    highlights: ['Better Control', 'Great Execution', 'Exceptional Results'],
  },
  pricing: {
    title: 'Campaign',
    titleHighlight: 'Packages',
    subtitle: 'From a risk-free demo to full-scale market domination. Choose the level that matches your goals.',
    mostPopular: 'Most Popular',
    footerNote: 'All packages include full performance tracking, dedicated support, and transparent reporting.',
    tiers: [
      { name: 'Demo Campaign', price: '$10,000', period: 'one-time', tagline: 'Proof before commitment', cta: 'Start Demo', features: ['5-10 verified streamers', '10-15 hours of live content', 'Full performance tracking', 'Detailed ROI report', 'Scaling recommendation'] },
      { name: 'Starter', price: '$25-50K', period: '/month', tagline: 'For growing brands entering new markets', cta: 'Get Quote', features: ['15-20 big streamers', '30-50 hours of content/month', 'Weekly performance reports', 'Campaign optimization', 'Dedicated account manager'] },
      { name: 'Growth', price: '$50-75K', period: '/month', tagline: 'For brands ready to scale aggressively', cta: 'Get Quote', features: ['50+ micro & macro streamers', '100+ hours of content/month', 'Real-time performance dashboard', 'Multi-platform coverage', 'Priority support & strategy consulting', 'High-converting SEO website partnership'] },
      { name: 'Enterprise', price: '$100K+', period: '/month', tagline: 'For major operators dominating markets', cta: 'Contact Us', features: ['100+ verified streamers', 'Unlimited live content', 'Exclusive streamer partnerships', 'White-label options', 'Dedicated team of specialists', 'Custom reporting & analytics', '5x SEO website partnerships'] },
    ],
  },
  socialProof: {
    badge: 'Trusted Worldwide',
    title: 'Trusted by Leading',
    titleHighlight: 'iGaming',
    titleEnd: 'Brands',
    subtitle: 'Industry leaders rely on our network to drive acquisition, retention, and growth',
    stats: [
      { value: '50+', label: 'Brand Partners' },
      { value: '$5M+', label: 'Budget Spent' },
      { value: '20+', label: 'Markets Covered' },
      { value: '95%', label: 'Client Retention' },
    ],
    testimonials: [
      { quote: "Octo Media's streamer strategy helped us scale quickly in key markets. Their execution and transparency are top-tier.", detail: 'We saw immediate improvement in audience engagement and conversion rates across all streaming channels within the first month.', role: 'Influencer Marketing Lead', company: 'BC.GAME' },
      { quote: 'Working with Octo Media transformed our player acquisition pipeline. Their deep understanding of the iGaming audience delivered measurable results from day one.', detail: 'Their targeted approach to streamer selection and content strategy resulted in higher-quality leads and better long-term player value.', role: 'Affiliate Manager', company: 'BET365' },
      { quote: 'The quality of streamers and content Octo Media sources is unmatched. Our brand visibility in competitive markets grew significantly within weeks.', detail: 'From day one, we had access to authentic, engaged audiences that genuinely connected with our brand message and values.', role: 'Streamer Marketing Head', company: 'LEON' },
      { quote: 'Octo Media brought a data-driven approach to our influencer campaigns that we hadn\'t seen before. Retention metrics improved across every channel they managed.', detail: 'Their strategic insights and continuous optimization kept our campaigns performing at peak efficiency throughout the year.', role: 'Growth Lead', company: 'MELBET' },
      { quote: 'Partnering with Octo Media gave us access to a curated network of high-impact streamers. The campaign performance consistently exceeded our benchmarks.', detail: 'We achieved a level of campaign performance consistency that gave us confidence to scale budget and expand into new markets.', role: 'Acquisition Manager', company: 'STAKE' },
      { quote: 'The seamless integration and professionalism Octo Media brought to our campaigns set them apart. Their player retention focus delivered exceptional ROI.', detail: 'Unlike other agencies, they genuinely care about long-term partnership success and player lifetime value, not just quick wins.', role: 'Growth Lead', company: 'TRUSTDICE' },
    ],
  },
  markets: {
    items: [
      { title: 'Online Casinos', description: 'Traditional casinos, crypto casinos, Bitcoin casinos, live dealer casinos' },
      { title: 'Sports Betting', description: 'Football betting, esports betting, multi-sport platforms' },
      { title: 'Gaming Gambling', description: 'CS2 gambling, Rust gambling, gaming-adjacent betting' },
      { title: 'Poker Rooms', description: 'Online poker, tournaments' },
    ],
  },
  contact: {
    title: 'Get In',
    titleHighlight: 'Touch',
    subtitle: 'Ready to turn your marketing budget into real depositing players? Send us a message or book a free consultation.',
    formTitle: 'Send a Message',
    namePlaceholder: 'Your Name',
    emailPlaceholder: 'Email Address',
    messagePlaceholder: 'Your Message',
    sendButton: 'Send Message',
    businessEmail: 'Business Email',
    businessEmailDesc: 'For partnerships and professional inquiries',
    telegramSupport: 'Telegram Support',
    telegramDesc: 'Quick responses and real-time support',
    bookTitle: 'Book a Free Consultation',
    bookDesc: 'Schedule a 30-minute call to discuss your influencer marketing strategy.',
    discussLabel: "What we'll discuss",
    scheduleButton: 'Schedule Your Call',
    topics: [
      'Your current player acquisition strategy',
      'How verified influencer marketing fits your goals',
      'Expected ROI from demo campaign',
      'Custom campaign proposal for your brand',
    ],
    responseTime: 'Response Time',
    responseTimeValue: 'Usually replies within 15-30 minutes',
    availability: 'Availability',
    availabilityValue: 'Active: 7 days a week',
    supportType: 'Support Type',
    supportTypeValue: 'Streamer inquiries, campaign planning, partnerships',
  },
  finalCta: {
    badge: 'Limited Availability',
    title1: 'Your Competitors Are Already',
    title2: 'Scaling With Us',
    subtitle: 'Every day you wait is another day of wasted ad spend on unverified influencers with fake followers.',
    body: 'We only take on a limited number of brands per quarter to ensure quality execution. Secure your slot before your competitors do.',
    cta: 'Get Your Free Growth Plan',
    guarantees: ['No long-term contracts', '100% transparent tracking', 'Results within 2 weeks', 'Dedicated account manager'],
  },
  demo: {
    badge: 'Zero Risk',
    title1: "Not Convinced?",
    title2: 'See Us in Action',
    subtitle: "Give us $10,000 and two weeks. If we don't deliver measurable results, you'll know before committing a larger budget.",
    steps: [
      { title: '$10,000 Investment', description: 'Fixed cost, no hidden fees. You know exactly what you pay.' },
      { title: '2-Week Campaign', description: '5-10 verified streamers go live promoting your brand.' },
      { title: 'Measurable Results', description: 'Full performance report with ROI data and scaling plan.' },
    ],
    whatsIncluded: "What's Included",
    includes: [
      'Handpicked verified streamers matched to your brand',
      '10-15 hours of live streamer content',
      'Real-time tracking dashboard access',
      'Detailed ROI & performance report',
      'No-obligation scaling recommendation',
    ],
    noContract: 'No long-term contract required. Results speak for themselves.',
    pilotLabel: '2-week pilot campaign',
    cta: 'Schedule Your Demo Call',
  },
  streamersSection: {
    badge: 'For Streamers',
    title: 'Grow Your',
    titleHighlight: 'Streaming Career',
    subtitle: 'Join our network of 750+ verified streamers and get matched with top iGaming brands. We handle the business side so you can focus on creating content.',
    benefits: [
      'Access to premium iGaming brands',
      'Competitive commission rates',
      'Reliable and on-time payments',
      'Dedicated partnership manager',
      'Performance bonuses and exclusives',
      'Multi-platform support (Twitch, YouTube, Kick)',
    ],
    cta: 'Apply Now',
    verifiedStreamers: 'Verified Streamers',
    avgEarnings: 'Average monthly earnings',
    avgEarningsValue: '$2,000 - $15,000',
    platforms: 'Platforms supported',
    platformsValue: 'Twitch, YT, Kick',
    paymentSchedule: 'Payment schedule',
    paymentScheduleValue: 'Bi-weekly',
    markets: 'Markets available',
    marketsValue: '25+ countries',
  },
  streamersPage: {
    hero: {
      badge: 'For Streamers & Creators',
      title1: 'Stop Chasing Deals.',
      title2: 'Start Getting',
      titleHighlight: 'Paid',
      subtitle: 'The iGaming streamer network that connects verified creators with top casino and crypto brands for ongoing sponsorships.',
      subtitleSmall: 'Better rates. Faster payments. Zero hassle.',
      cta: 'Apply Now',
    },
    benefits: {
      badge: 'Complete Partnership Ecosystem',
      title: 'Why',
      titleHighlight: 'Work With Us',
      subtitle: 'More than just brand deals. A complete ecosystem designed to maximize your earning potential and protect your interests at every step.',
      commissionNote: '10% commission on deals we close for you',
      commissionSub: 'Only charged after you receive payment. Zero risk, maximum transparency.',
      items: [
        { title: 'Personal Manager 24/7', desc: 'Your dedicated account manager is available around the clock to handle all your queries, negotiations, and campaign coordination.' },
        { title: 'No Exclusivity Required', desc: 'Found a better deal yourself? Go for it! We provide free consultation so you know your true worth in the market.' },
        { title: 'Zero Upfront Costs', desc: 'No subscription fees or hidden charges. We take a flat 10% only after you receive your campaign payment. Simple and transparent.' },
        { title: 'Vetted Brands Only', desc: 'No more fraud or delayed payments. Work today, get paid today. Direct to your bank account or crypto wallet.' },
        { title: 'Flexible Deal Structures', desc: 'Prefer raw balance, fixed fees, or lifetime revenue share? We tailor deals according to your preferences and content style.' },
        { title: 'No Long-Term Contracts', desc: 'Taking a break or facing issues? Walk away anytime. No penalties, no questions asked. We have got your back.' },
        { title: 'Brand Building Support', desc: 'Beyond deals, we help build your personal brand with website setup, social media strategy, and professional content guidance.' },
        { title: 'Exclusive Event Access', desc: 'Invitation to offline gatherings worldwide. We fly you out, all expenses paid. Network with top streamers and industry leaders.' },
        { title: 'Continuous Innovation', desc: 'Our platform evolves with new features, tools, and opportunities. Join us to shape the future of creator monetization.' },
      ],
    },
    howItWorks: {
      title: 'How It',
      titleHighlight: 'Works',
      subtitle: 'From application to payday in four simple steps',
      step: 'STEP',
      steps: [
        { title: 'Apply', desc: 'Fill out a quick application with your channel info, platform, and audience size.' },
        { title: 'Get Verified', desc: 'Our team reviews your content quality, audience authenticity, and engagement metrics.' },
        { title: 'Get Matched', desc: 'We pair you with iGaming and crypto casino brands that fit your niche, audience, and content style for maximum results.' },
        { title: 'Create & Get Paid', desc: 'Stream sponsored iGaming content and receive fast, reliable payments directly to your account.' },
      ],
    },
    faq: {
      title: 'Frequently Asked',
      titleHighlight: 'Questions',
      subtitle: 'Common questions from streamers joining our network',
      items: [
        { q: 'How much can I earn?', a: 'Earnings vary based on your audience size, engagement, and content quality. Our streamers typically earn between $500 and $15,000+ per month from brand deals placed through our network.' },
        { q: 'Which platforms do you support?', a: 'We work with streamers on Twitch, YouTube, Kick, and other major streaming platforms. If you have an active audience on any streaming platform, we want to hear from you.' },
        { q: 'What if I have fewer than 5,000 followers?', a: 'We occasionally work with smaller creators who have exceptional engagement rates. Apply anyway and our team will review your profile. Quality of audience matters more than raw numbers.' },
        { q: 'What kind of content will I need to create?', a: 'Sponsored streams featuring iGaming and crypto casino brands. The specific format and requirements vary by brand, but we always work with you to ensure the content feels natural and authentic for your audience.' },
        { q: 'How long are the contracts?', a: 'Most deals are month-to-month with no long-term lock-in. Some premium partnerships may run for 3-6 months, but you will always know the terms upfront before committing.' },
        { q: 'Do you take a commission?', a: 'We are paid by the brands, not by you. The rate we negotiate on your behalf is what you receive. There are no hidden fees or deductions from your earnings.' },
        { q: 'Can I work with other agencies at the same time?', a: 'Yes. We have no exclusivity requirements. You are free to work with other agencies and take direct deals. We just ask that you honor active campaign commitments.' },
        { q: 'How long does the application process take?', a: 'Typically 2-5 business days. We review your channel, verify your audience metrics, and if approved, you could receive your first brand deal within a week.' },
      ],
    },
    form: {
      title: 'Apply',
      titleHighlight: 'Now',
      subtitle: 'Fill out the form below and our team will review your application',
      fullName: 'Full Name *',
      emailAddress: 'Email Address *',
      primaryPlatform: 'Primary Platform *',
      followerCount: 'Follower Count *',
      profileUrl: 'Profile / Channel URL *',
      telegramHandle: 'Telegram Handle (optional)',
      describeContent: 'Describe Your Content *',
      selectPlatform: 'Select platform',
      selectRange: 'Select range',
      namePlaceholder: 'Your name',
      contentPlaceholder: "Tell us about your content, audience, and what kind of brand deals you're interested in...",
      submitButton: 'Submit Application',
      successTitle: 'Application Sent',
      successBody: 'Your email client has been opened with your application details. Send the email to complete your submission. We will review your profile and get back to you within 2-5 business days.',
      submitAnother: 'Submit Another Application',
    },
    whyJoin: {
      title: 'Why Join Our',
      titleHighlight: 'Network',
      subtitle: 'We built this for creators who are tired of unreliable deals and lowball offers',
      items: [
        { title: 'Consistent Deals', desc: 'Monthly recurring iGaming sponsorships so you always have casino brand deals lined up. No more hunting for one-off campaigns.' },
        { title: 'Better Rates', desc: 'We negotiate premium rates on your behalf using our network leverage. Earn more per hour of content than going solo.' },
        { title: 'We Handle the Business', desc: 'Contracts, invoicing, negotiations, compliance. We manage the paperwork so you can focus on streaming.' },
        { title: 'Fast Payments', desc: 'Get paid within 7-14 days. No chasing brands for months. We guarantee timely, reliable payouts every time.' },
        { title: 'Gaming-Friendly Brands', desc: 'Work with reputable iGaming and crypto casino brands, sports betting platforms, and gaming companies that align with your audience and content style.' },
        { title: 'No Lock-In', desc: 'Work with us on your terms. No exclusivity contracts. You are free to collaborate with other agencies and brands.' },
      ],
    },
    whatYouGet: {
      badge: 'Core Features',
      title: 'The',
      titleHighlight: 'Octo Advantage',
      subtitle: 'Everything you need to monetize your content professionally and scale your creator business',
      items: [
        { title: 'Recurring Partnerships', desc: 'Long-term brand deals that provide stable, predictable income month after month.' },
        { title: 'Premium Rates', desc: 'Our volume and reputation let us negotiate higher CPMs and flat rates than you could alone.' },
        { title: 'Full Service Support', desc: 'Dedicated partnership manager, contract handling, creative briefs, and compliance support.' },
        { title: 'Fast Payments', desc: '7-14 day payment cycles. No waiting 60-90 days. We pay on time, every time.' },
        { title: 'Targeted Brand Matching', desc: 'Get matched with iGaming and crypto casino brands that resonate with your specific audience for authentic sponsorships.' },
        { title: 'Flexibility', desc: 'No exclusivity. Work with multiple brands and agencies. Scale up or down on your terms.' },
      ],
    },
    eligibility: {
      title: 'Eligibility',
      titleHighlight: 'Requirements',
      subtitle: 'Make sure you meet the basics before applying',
      items: [
        { title: '5,000+ Followers', desc: 'Minimum follower count across your primary streaming platform.' },
        { title: 'Gaming / Gambling Content', desc: 'Your content should be gaming or gambling-adjacent to align with our brand partners.' },
        { title: 'Major Platform Presence', desc: 'Active on Twitch, YouTube, Kick, or similar major streaming platforms.' },
        { title: 'Authentic Engagement', desc: 'Real viewers and genuine interaction. We verify engagement quality, not just numbers.' },
        { title: 'Global Availability', desc: 'We work with streamers worldwide. All regions and languages are welcome.' },
        { title: 'Consistent Schedule', desc: 'Regular streaming schedule with reliable content output and audience retention.' },
      ],
    },
    comparison: {
      badge: 'The Clear Choice',
      title: 'Traditional Agencies vs',
      titleHighlight: 'Octo Media',
      subtitle: 'See why thousands of streamers are switching from traditional talent agencies to our creator-first platform',
      traditionalLabel: 'Traditional',
      traditionalAgency: 'Traditional Agency',
      octoMedia: 'Octo Media',
      metrics: [
        { label: 'Commission Rate', traditional: '20-40%', us: '10%' },
        { label: 'Payment Timeline', traditional: '60-90 days', us: 'Same day' },
        { label: 'Contract Length', traditional: '12-24 months', us: 'No lock-in' },
        { label: 'Average Deal Value', traditional: '$2-5K/month', us: '$8-15K/month' },
      ],
      features: [
        { category: 'Exclusivity', traditional: 'Required - Cannot work with other agencies', us: 'Optional - Work with multiple partners freely' },
        { category: 'Upfront Costs', traditional: 'Setup fees, monthly subscriptions', us: 'Zero upfront costs or hidden fees' },
        { category: 'Brand Vetting', traditional: 'Minimal screening, payment delays common', us: '100% vetted brands, guaranteed payments' },
        { category: 'Personal Support', traditional: 'Shared manager for 50+ creators', us: 'Dedicated 24/7 personal manager' },
        { category: 'Deal Flexibility', traditional: 'Standard packages only', us: 'Custom deals matching your preferences' },
        { category: 'Contract Exit', traditional: 'Penalties and notice periods', us: 'Walk away anytime, no penalties' },
        { category: 'Career Support', traditional: 'Limited to deal brokering', us: 'Full brand building and growth support' },
      ],
      highlights: ['Lower Commission', 'Faster Payments', 'Higher Earnings'],
    },
  },
  whyUsPage: {
    hero: {
      badge: 'WHY OCTOMEDIA',
      title: 'Built by Casino Insiders,\nNot Marketing Outsiders',
      subtitle: "OctoMedia was founded by eight iGaming veterans who spent years inside real casinos and crypto casino platforms — managing acquisitions, retention, launches, and compliance. The only iGaming marketing agency that combines streamer-specific focus, crypto casino specialization, and an ex-operator founding team. We understand FTDs, LTV, and retention because we've been measured on them.",
      point1: 'Ex-Casino & Crypto Casino Professionals',
      point2: 'iGaming Streamer Marketing Specialists',
      point3: 'Compliance-Aware Scaling',
    },
    differentiators: {
      title: 'What Makes Us Different',
      subtitle: "OctoMedia isn't just another marketing agency. We're built differently because we come from inside the industry.",
      items: [
        { title: 'Ex-Operator Mindset', description: 'We think like casino operators because we were casino operators. Every decision is filtered through real-world KPIs and operational constraints.' },
        { title: 'FTD, LTV & Retention Focus', description: 'We optimize for metrics that matter: first-time deposits, lifetime value, second-deposit rates, and long-term player retention.' },
        { title: 'Data-Driven Influencer Marketing', description: 'No vanity metrics. We track conversion rates, cost per FTD, and audience quality across every streamer and content creator.' },
        { title: 'Compliance-Aware Scaling', description: 'Growth strategies built with regulatory awareness. We know which markets require careful messaging and which influencers pose compliance risk.' },
        { title: 'Industry Network Access', description: 'Direct relationships with top-tier streamers, affiliate networks, and media buyers who actually understand iGaming and crypto casinos.' },
        { title: 'Long-Term Brand Value', description: 'We balance aggressive acquisition with sustainable brand building. Short-term wins without long-term damage.' },
      ],
    },
    foundingStory: {
      title: 'How We Started',
      body1: 'We met across different casino roles -- acquisition heads, retention leads, affiliate managers, compliance strategists. Some of us launched crypto casinos from zero. Others scaled established brands across multiple GEOs.',
      body2: "The common frustration? Marketing agencies that didn't truly understand iGaming.",
      body3: "They pitched \"awareness\" and \"engagement\" while we were measured on first-time deposits, second-deposit rates, and lifetime value. They couldn't speak the language of CPA deals, bonus abuse protection, or regulatory risk.",
      body4: "So we built OctoMedia -- an agency run by people who've already been on the operator side. We know what works because we've deployed budgets, managed influencer campaigns, and optimized funnels under real pressure.",
      closing: "We're not guessing. We've already done it.",
      cards: [
        { heading: 'Where We Came From', text: 'We met across different casino roles -- acquisition heads, retention leads, affiliate managers, compliance strategists. Some of us launched crypto casinos from zero. Others scaled established brands across multiple GEOs.' },
        { heading: 'The Frustration', text: "Marketing agencies that didn't truly understand iGaming. They pitched \"awareness\" and \"engagement\" while we were measured on first-time deposits, second-deposit rates, and lifetime value." },
        { heading: 'The Gap We Saw', text: "They couldn't speak the language of CPA deals, bonus abuse protection, or regulatory risk. Nobody was bridging the gap between influencer marketing and real operator KPIs." },
        { heading: 'Why We Built OctoMedia', text: "An agency run by people who've already been on the operator side. We know what works because we've deployed budgets, managed influencer campaigns, and optimized funnels under real pressure." },
      ],
    },
    foundingTeam: {
      title: 'Meet The Founding Team',
      subtitle: 'Eight casino veterans who built their careers inside the industry, not outside of it.',
      yearsLabel: 'Years',
      exLabel: 'Ex:',
      strengthLabel: 'Strength:',
    },
    closing: {
      badge: 'THE DIFFERENCE IS CLEAR',
      title: "We've Already Been\non the Inside of iGaming",
      subtitle: "OctoMedia was built by people who've run casino and crypto casino acquisitions, managed million-dollar iGaming influencer campaigns, and optimized retention funnels under real pressure. We don't just understand iGaming streamer marketing — we've lived it.",
      cta1: 'Explore Streamer Partnerships',
      cta2: 'Get In Touch',
      stat1Value: '8',
      stat1Label: 'Founding Veterans',
      stat2Value: '62',
      stat2Label: 'Combined Years Experience',
      stat3Value: '100%',
      stat3Label: 'Ex-Casino Professionals',
    },
  },
  servicesPage: {
    badge: 'OUR SERVICES',
    heroBadge: 'iGaming Marketing Services',
    heroTitle: 'Performance Marketing Built for',
    heroTitleHighlight: 'iGaming Operators',
    heroSubtitle: 'Three proven acquisition channels — streamer campaigns, affiliate programmes, and influencer marketing — managed end-to-end by ex-casino operators who understand FTDs, LTV, and retention.',
    tab1: 'Streamer Marketing',
    tab2: 'Affiliate Marketing',
    tab3: 'Influencer Marketing',
    howItWorksLabel: 'How It Works',
    whatYouGetLabel: 'What You Get',
    inlineCta1: 'Want to see streamer results before committing a full budget?',
    inlineCta2: 'Ready to build a compliant, high-converting affiliate programme?',
    inlineCtaNote: 'No long-term commitment required. See results before scaling.',
    inlineCtaBtn: 'Book a Free Strategy Call',
    closingBadge: 'Zero Long-Term Commitment',
    trustSignals: ['No long-term contracts', '100% spend transparency', 'Results within 2 weeks', 'Dedicated account manager'],
    streamerSection: {
      badge: 'Casino Streamer Marketing',
      title: 'Verified Streamers.',
      titleHighlight: 'Proven Deposits.',
      subtitle: 'Twitch · YouTube · Kick — 25+ Markets',
      positioning: 'Every streamer in our network is handpicked from iGaming niches, audited for real audience engagement, and matched only with brands they already convert for. We own end-to-end execution — from compliance briefing to weekly ROI reports — so you see exactly what your budget delivers.',
      accordion1Label: "What's included in a Streamer Campaign",
      accordion1Items: [
        'Verified Twitch casino streamers, YouTube gambling influencers & Kick streamers',
        'Compliant casino influencer campaigns with responsible gambling standards',
        'KPI-based execution: FTDs, deposits, player retention & cost-per-acquisition',
        'Weekly ROI reports per streamer — full spend vs. results transparency',
        'Crypto casino, online casino & sportsbook brand expertise',
        'Coverage across 25+ markets — Europe, LATAM, North America, Oceania & APAC',
      ],
      accordion2Label: 'Platforms & Compliance',
      accordion2Items: [
        'Live streaming campaigns on Twitch, YouTube Live & Kick simultaneously',
        'Geo-targeted streamer selection to match your licensed markets',
        'Responsible gambling disclaimers embedded in every campaign brief',
        'Age-verification audience filters applied before go-live',
        'Content reviewed against UK, MGA, Curaçao & local regulatory standards',
      ],
      steps: [
        { num: '01', title: 'Briefing & Brand Match', desc: 'We map your target GEOs, player profile, and compliance requirements to build a precise creator brief.' },
        { num: '02', title: 'Streamer Sourcing', desc: 'Handpicked from our vetted network — matched by niche, audience geography, and deposit-conversion history.' },
        { num: '03', title: 'Live Campaign Execution', desc: 'Streamers go live with structured gameplay, brand-safe content, and authentic promotion to high-intent players.' },
        { num: '04', title: 'Real-Time Tracking', desc: 'Dashboard access + weekly reports: FTDs, deposits, cost-per-player, retention, and full ROI breakdown.' },
        { num: '05', title: 'Scale & Retain', desc: 'Double down on top performers, activate retention mechanics, and expand into adjacent markets.' },
      ],
      featureTexts: [
        'Bot-free audiences — manually verified before onboarding',
        'KPI-driven execution: FTDs, deposits & cost-per-acquisition',
        'Weekly ROI reports per streamer, spend vs. results',
        '25+ markets — Europe, LATAM, North America, APAC & Oceania',
        'Compliance-first briefing aligned with responsible gambling laws',
        'Multi-platform: Twitch, YouTube & Kick simultaneously',
      ],
    },
    affiliateSection: {
      badge: 'iGaming Affiliate Marketing',
      title: 'Affiliate Programmes',
      titleHighlight: 'That Actually Convert.',
      subtitle: 'CPA · Revenue Share · Hybrid — Operator-Built',
      positioning: "Built by people who've managed affiliate channels from the operator side. We design commission structures around real player economics — not inflated click counts — and manage every partnership with live tracking, geo-targeted creatives, and transparent cost-per-FTD reporting.",
      accordion1Label: "What's included in Affiliate Management",
      accordion1Items: [
        'Performance-based CPA, revenue share & hybrid affiliate commission models',
        'Gambling-compliant creative assets and geo-targeted landing pages',
        'Community building and engagement strategies for long-term player retention',
        'Real-time affiliate tracking and transparent conversion reporting',
        'Compliance-aware iGaming affiliate program management',
        'Scalable affiliate infrastructure from startup to enterprise casino brands',
      ],
      accordion2Label: 'Reporting & Transparency',
      accordion2Items: [
        'Real-time dashboard access for all active affiliate partnerships',
        'Weekly breakdowns: clicks, registrations, FTDs, deposit volume & CPA',
        'Per-affiliate and per-GEO performance segmentation',
        'Fraud detection and traffic quality monitoring',
        'Monthly strategy review and programme optimisation calls',
      ],
      featureTexts: [
        'CPA, revenue share & hybrid models designed around real operator economics',
        'Compliance-aware creatives and geo-targeted landing pages',
        'Real-time conversion tracking and transparent reporting',
        'Community building strategies for long-term player retention',
        'Scalable infrastructure from early-stage to enterprise operators',
        'Affiliate programme management by ex-casino acquisition leads',
      ],
    },
    influencerSection: {
      badge: 'Gambling Influencer Marketing',
      title: 'High-LTV Players',
      titleHighlight: 'From Trusted Creators.',
      subtitle: 'YouTube · TikTok · Twitch · Kick — Performance-First',
      positioning: 'We pair iGaming and crypto casino brands with verified gambling influencers whose audiences already engage with casino content. Every campaign is scoped for real depositing players — not vanity impressions — with full conversion tracking from first click to second deposit.',
      accordion1Label: "What's included in Influencer Campaigns",
      accordion1Items: [
        'Verified gambling influencer network across YouTube, TikTok, Twitch & Kick',
        'End-to-end iGaming influencer campaign management from briefing to ROI reporting',
        'Brand awareness and player acquisition models for casino & sportsbook brands',
        'Audience-matched creator selection by geo, niche & iGaming content history',
        'Compliant influencer briefings aligned with responsible gambling regulations',
        'Full conversion tracking: FTDs, deposits, LTV & cost-per-player acquired',
      ],
      accordion2Label: 'Creator Vetting Process',
      accordion2Items: [
        'Manual audit of audience demographics, engagement rates & geo distribution',
        'Historical performance review: past iGaming campaign conversion data',
        'Bot and fake-follower screening via third-party analytics tools',
        'Brand alignment check: content style, tone, and audience intent',
        'Compliance history review before any brand introduction',
      ],
      featureTexts: [
        'Verified network across YouTube, TikTok, Twitch & Kick',
        'Audience-matched creator selection by geo, niche & iGaming history',
        'Compliant influencer briefs aligned with gambling regulations',
        'Full conversion tracking: FTDs, LTV & cost-per-player',
        'Brand awareness + direct acquisition models available',
        'End-to-end management from brief to post-campaign analysis',
      ],
    },
    stats: [
      { value: '25+', label: 'Markets Covered' },
      { value: '750+', label: 'Verified Streamers' },
      { value: '3–5x', label: 'Average ROI' },
      { value: '2 Weeks', label: 'First Results' },
    ],
    title: 'iGaming Influencer Marketing Services',
    subtitle: 'Performance-driven casino streamer marketing, gambling influencer campaigns, and iGaming affiliate programs — built by industry insiders for crypto casino, online casino, and sportsbook brands worldwide.',
    services: [
      {
        id: 'streamer-marketing',
        title: 'iGaming Streamer Marketing',
        description: 'Our flagship casino streamer marketing service connects iGaming, crypto casino, and sportsbook brands with verified, high-performing gambling streamers on Twitch, YouTube, and Kick. Unlike generic influencer agencies, every streamer in our network is manually vetted for real audience engagement, geographic targeting, and a proven track record of driving first-time deposits (FTDs) in the iGaming space. We handle end-to-end campaign management — from streamer sourcing and compliance briefing to live content execution and weekly ROI reporting.',
        cta: 'Get a Free Growth Plan',
        features: ['Verified Twitch casino streamers, YouTube gambling influencers & Kick streamers', 'Compliant casino influencer campaigns with responsible gambling standards', 'KPI-based execution: FTDs, deposits, player retention & cost-per-acquisition', 'Weekly ROI reports per streamer — full spend vs. results transparency', 'Crypto casino, online casino & sportsbook brand expertise', 'Coverage across 25+ markets — Europe, LATAM, North America, Oceania & APAC'],
      },
      {
        id: 'affiliate-marketing',
        title: 'iGaming Affiliate Marketing',
        description: 'We build and manage performance-based affiliate marketing programs for iGaming brands including crypto casinos, online casinos, and sports betting platforms. Our iGaming affiliate approach is grounded in real operator experience — we design CPA, revenue share, and hybrid commission models that drive sustained player acquisition at controlled cost-per-FTD. Every affiliate partnership is managed with compliance-aware creative assets, real-time conversion tracking, and transparent reporting tailored to gambling industry standards.',
        cta: 'Discuss Affiliate Strategy',
        features: ['Performance-based CPA, revenue share & hybrid affiliate commission models', 'Gambling-compliant creative assets and geo-targeted landing pages', 'Community building and engagement strategies for long-term player retention', 'Real-time affiliate tracking and transparent conversion reporting', 'Compliance-aware iGaming affiliate program management', 'Scalable affiliate infrastructure from startup to enterprise casino brands'],
      },
      {
        id: 'influencer-marketing',
        title: 'iGaming Influencer Marketing',
        description: 'Strategic gambling influencer marketing campaigns purpose-built for iGaming and crypto casino platforms. We connect brands with verified casino influencers, YouTube gambling channels, TikTok casino creators, and Kick streamers who have authentic audiences engaged in online gaming and crypto — delivering measurable brand awareness, player acquisition, and high-LTV retention through trusted creator relationships. Our gambling influencer marketing strategy is performance-driven from day one: every campaign is scoped to deliver real depositing players, not vanity impressions.',
        cta: 'Plan an Influencer Campaign',
        features: ['Verified gambling influencer network across YouTube, TikTok, Twitch & Kick', 'End-to-end iGaming influencer campaign management from briefing to ROI reporting', 'Brand awareness and player acquisition models for casino & sportsbook brands', 'Audience-matched creator selection by geo, niche & iGaming content history', 'Compliant influencer briefings aligned with responsible gambling regulations', 'Full conversion tracking: FTDs, deposits, LTV & cost-per-player acquired'],
      },
    ],
    whatsIncluded: "What's Included:",
    closing: {
      title: 'Ready to Scale Your iGaming Player Acquisition?',
      body: 'Book a free 30-minute strategy call. We will review your current player acquisition strategy and show you exactly how our casino influencer marketing and gambling streamer campaigns can drive real depositing players at measurable ROI.',
      cta1: 'Schedule Free Strategy Call',
      cta2: 'Hire Casino Streamers',
    },
  },
  resourcesPage: {
    badge: 'iGaming Marketing Resources',
    title: 'iGaming Influencer Marketing Guides',
    subtitle: 'In-depth resources on casino influencer marketing strategy, gambling advertising compliance, ROI measurement, and crypto casino marketing trends — written by iGaming industry insiders.',
    readTime: 'min read',
    ctaTitle: 'Ready to Apply These Strategies?',
    ctaBody: 'Our iGaming marketing team implements these strategies every day for crypto casino and online casino brands. Book a free 30-minute consultation.',
    ctaButton: 'Book Free Strategy Call',
    articles: [
      { badge: 'Strategy', title: 'ROI of iGaming Influencer Marketing: What Brands Actually Get', description: 'A data-driven breakdown of real ROI metrics, cost-per-FTD benchmarks, and how to measure campaign performance for casino influencer marketing.', readTime: 8 },
      { badge: 'Compliance', title: 'Gambling Influencer Marketing Compliance: UK, Malta, Curacao & USA', description: 'Region-by-region breakdown of casino advertising regulations, responsible gambling requirements, and compliant influencer campaign frameworks.', readTime: 10 },
      { badge: 'Comparison', title: 'Affiliate vs Influencer Marketing for iGaming: Which Drives Better ROI?', description: 'A direct comparison of iGaming affiliate programs vs influencer marketing campaigns — cost structures, conversion rates, and when to use each.', readTime: 7 },
      { badge: 'Trends', title: 'Crypto Casino Marketing Trends 2026: Streamers, Web3 & Player Acquisition', description: 'The latest trends shaping crypto casino and blockchain gambling marketing — from Twitch streamers to Web3-native influencer campaigns.', readTime: 9 },
      { badge: 'Platform Guide', title: 'Twitch Casino Marketing: The Complete Brand Guide for 2026', description: 'How to run effective Twitch casino sponsorships — finding gambling streamers, structuring deals, compliance considerations, and tracking ROI.', readTime: 11 },
      { badge: 'Strategy', title: 'Esports Betting Influencer Marketing Strategy for Sportsbooks', description: 'How sportsbook and esports betting brands can leverage gaming influencers, esports streamers, and content creators to drive depositing players.', readTime: 8 },
    ],
  },
  faq: {
    title: 'Frequently Asked',
    titleHighlight: 'Questions',
    subtitle: 'Everything you need to know about verified influencer media buying',
    items: [
      { q: 'What makes you different from other agencies?', a: 'Most agencies sell reach. We deliver verified streamers, real players, and measurable ROI. Every campaign is built around deposits, retention, and LTV—not vanity metrics.' },
      { q: 'How do you verify streamers?', a: "Streamers are handpicked and vetted manually for real engagement, audience geo, and past iGaming performance. We only work with creators who've already proven they can drive deposits." },
      { q: "What's included in the $10,000 demo?", a: 'A 2-week pilot with 5–10 verified streamers, 10–15 hours of live content, and a full ROI performance report. You get proof before scaling—no long-term commitment required.' },
      { q: 'Which markets do you serve?', a: 'We operate across Europe, LATAM, North America, and Oceania, covering 25+ markets and 15+ languages. Streamers are always matched based on geo, audience behavior, and brand fit.' },
      { q: 'What platforms do you work with?', a: 'We run campaigns on Twitch, YouTube, Kick, and platform-native streaming environments. Multi-platform execution ensures reach, frequency, and higher conversion efficiency.' },
      { q: 'How do you track results?', a: 'Every campaign is tracked end-to-end with weekly performance reports. You see spend, FTDs, deposits, retention, and ROI—broken down streamer by streamer.' },
      { q: "What's your pricing model?", a: 'We offer fixed demo pilots and scalable monthly retainers, depending on your growth stage. No hidden fees, no vague pricing—everything is aligned to performance delivery.' },
      { q: 'How do I get started?', a: "Book a free 30-minute consultation to review your goals and current acquisition strategy. If there's a fit, we launch a demo and prove results before scaling." },
      { q: 'How does crypto casino streamer marketing work?', a: 'We connect crypto casino brands with verified streamers who have proven audiences in the iGaming space. Streamers create authentic live content showcasing your platform, driving real player sign-ups, first-time deposits, and long-term retention through trusted creator relationships.' },
      { q: 'What is the ROI of iGaming influencer marketing?', a: 'Our clients typically see 3-5x ROI on iGaming streamer campaigns, with cost-per-FTD significantly lower than traditional acquisition channels. We provide full transparency with weekly reports tracking spend, FTDs, deposits, retention, and ROI per streamer.' },
      { q: 'How do you find and verify casino streamers?', a: 'Every streamer in our network is manually vetted for audience authenticity, engagement quality, geographic reach, and past iGaming conversion performance. We reject creators with bot-inflated metrics and only onboard those with proven deposit-driving track records.' },
      { q: 'Do you work with crypto casino brands?', a: 'Yes. Crypto casino and Bitcoin casino brands are a core focus. We specialize in connecting crypto gambling platforms with streamers who have audiences already engaged in cryptocurrency and online gaming.' },
      { q: 'What markets and geos do you cover for iGaming marketing?', a: 'We cover 25+ markets across Dubai, Europe (UK, Germany, Malta), North America (Canada, US), Oceania (Australia, New Zealand), Asia-Pacific (Taiwan), and emerging LATAM markets. Streamers are matched to specific geos for maximum conversion relevance.' },
      { q: 'How much does iGaming streamer marketing cost?', a: 'We offer a $10,000 demo pilot for brands looking to test our approach with zero long-term commitment. Scalable monthly retainers start from there, with pricing aligned to your campaign scope, target markets, and growth objectives.' },
    ],
  },
  lang: {
    switcher: 'Language',
    en: 'English',
    ru: 'Русский',
    es: 'Español',
    uk: 'Українська',
    sv: 'Svenska',
    de: 'Deutsch',
    fr: 'Français',
  },
} as const;

export default en;
export type Translations = typeof en;
