import type { Translations } from './en';

const es: Translations = {
  meta: {
    home: {
      title: 'Mejor Agencia de Marketing iGaming 2026 | Octo Media',
      description: 'Agencia líder de marketing para iGaming. Streamers verificados de Twitch, YouTube y Kick. ROI probado para marcas de casino cripto. Reserva una llamada estratégica gratis.',
    },
    services: {
      title: 'Servicios de Marketing iGaming | Octo Media 2026',
      description: 'Marketing experto para influencers de casino, campañas con streamers de juego y servicios de afiliados iGaming. Captación de jugadores para marcas de casino cripto y apuestas.',
    },
    streamers: {
      title: 'Contratar Streamers de Casino en Twitch, YouTube y Kick | Octo Media',
      description: 'Únete a la red líder de streamers iGaming. Patrocinios consistentes, mejores tarifas y pagos más rápidos. Streamers de casino en Twitch, YouTube y Kick — aplica hoy.',
    },
    whyUs: {
      title: 'Agencia Experta en iGaming — Creada por Insiders del Casino',
      description: 'Octo Media Group: 8 veteranos de iGaming con resultados FTD comprobados, transparencia total de ROI y responsabilidad de rendimiento.',
    },
    resources: {
      title: 'Recursos y Guías de Marketing iGaming | Octo Media Group',
      description: 'Guías expertas de marketing para influencers de iGaming: cumplimiento normativo, referencias de ROI, estrategia de casino en Twitch, tendencias cripto y más.',
    },
    privacy: {
      title: 'Política de Privacidad | Octo Media Group',
      description: 'Política de privacidad de Octo Media Group. Descubre cómo recopilamos, usamos y protegemos tu información personal.',
    },
    terms: {
      title: 'Términos de Servicio | Octo Media Group',
      description: 'Términos de servicio de Octo Media Group. Lee los términos que rigen el uso de nuestro sitio web y servicios.',
    },
    cookies: {
      title: 'Política de Cookies | Octo Media Group',
      description: 'Política de cookies de Octo Media Group. Aprende cómo usamos cookies y tecnologías similares en nuestro sitio web.',
    },
  },
  nav: {
    home: 'Inicio',
    services: 'Servicios',
    ourStory: 'Nuestra Historia',
    forStreamers: 'Para Streamers',
    faq: 'Preguntas',
    contact: 'Contacto',
    blog: 'Blog',
    caseStudies: 'Casos de Estudio',
    whyJoin: 'Por Qué Unirse',
    howItWorks: 'Cómo Funciona',
    apply: 'Aplicar',
    ctaGrowthPlan: 'Plan de Crecimiento Gratis',
    ctaApplyNow: 'Aplicar Ahora',
    ctaGetInTouch: 'Contáctanos',
  },
  footer: {
    description: 'La agencia líder de marketing para influencers de iGaming. Campañas con streamers de casino orientadas al rendimiento y marketing de influencers de juego para marcas de casino cripto, casino online y apuestas deportivas en todo el mundo.',
    quickLinks: 'Accesos Rápidos',
    ourServices: 'Nuestros Servicios',
    legal: 'Legal',
    contact: 'Contacto',
    links: {
      agency: 'Agencia de Marketing iGaming',
      services: 'Servicios de Marketing iGaming',
      whyOcto: 'Por Qué Octo Media',
      hireStreamers: 'Contratar Streamers de Casino',
      faq: 'Preguntas',
      contact: 'Contacto',
    },
    serviceLinks: {
      streamer: 'Marketing de Streamers de Casino',
      affiliate: 'Marketing de Afiliados iGaming',
      influencer: 'Marketing de Influencers de Juego',
    },
    legalLinks: {
      privacy: 'Política de Privacidad',
      terms: 'Términos de Servicio',
      cookies: 'Política de Cookies',
    },
    telegram: '@OctoMediaGroup en Telegram',
    bottomText1: 'Octo Media Group es una agencia especializada en marketing de influencers para iGaming que ofrece marketing de streamers de casino, marketing de influencers de juego y marketing de afiliados iGaming para marcas de casino cripto, casino online y apuestas deportivas. También operamos una red dedicada para streamers de casino de Twitch, YouTube y Kick que buscan patrocinios consistentes.',
    bottomText2: 'Al usar este sitio web, aceptas nuestros Términos de Servicio, Política de Privacidad y Política de Cookies. El uso continuado implica la aceptación de estas políticas.',
    copyright: 'Todos los derechos reservados. Cumplimiento RGPD de la UE.',
  },
  hero: {
    headline1: 'Captación iGaming',
    headline2: 'Optimizada para',
    headline3: 'Alto Rendimiento LTV',
    subheadline: 'La agencia dedicada al marketing de streamers de casino cripto en la que confían las principales marcas de iGaming del mundo. Marketing de streamers e influencers orientado al rendimiento para iGaming y casinos cripto.',
    stat1Value: '$10M+',
    stat1Label: 'Ingresos Generados',
    stat2Value: 'Ciclo Completo',
    stat2Label: 'Gestión de Campañas',
    stat3Value: 'Captación',
    stat3Label: 'y Retención',
    ctaPrimary: 'Consulta Gratuita de 30 Min',
    ctaSecondary: 'Explorar Servicios',
    badge: 'Creado por Veteranos de iGaming',
  },
  problem: {
    badge: 'El Problema del Sector',
    title: 'El Problema del Marketing de Influencers en iGaming',
    titleHighlight: 'que Resolvemos',
    subtitle: 'Las marcas de iGaming desperdician millones en campañas con influencers que entregan métricas vacías en lugar de jugadores reales. Así luce el sector sin nosotros:',
    items: [
      { stat: '70%', title: 'Presupuesto Desperdiciado', description: 'del presupuesto de marketing de influencers en iGaming se gasta en creadores con audiencias falsas o irrelevantes' },
      { stat: '< 0.5%', title: 'Tasa de Conversión', description: 'es la tasa de conversión promedio de las campañas genéricas con influencers — apenas un hilo de jugadores reales que depositan' },
      { stat: 'CERO', title: 'Responsabilidad', description: 'Sin rendición de cuentas sobre la calidad y cantidad de resultados. Sin previsibilidad. La mayoría de las agencias no ofrecen seguimiento transparente ni garantías' },
    ],
    realityCheck: 'Verificación de Realidad',
    typicalMetrics: 'Métricas Típicas de Campaña',
    typicalSubtitle: 'Lo que sucede cuando trabajas con agencias estándar',
    spent: 'Gastado en campaña',
    signUps: 'Registros recibidos',
    ftds: 'FTDs convertidos',
    costPerFtd: 'Costo por FTD',
    secondDepositors: 'Depositantes por segunda vez',
    noRetention: 'Sin retención',
  },
  solution: {
    badge: 'Nuestra Especialidad',
    title: 'Nuestra Experiencia en',
    titleHighlight: 'Marketing iGaming',
    subtitle: 'Cubriendo Dubái, Europa, LATAM, América del Norte, Oceanía y Asia-Pacífico con streamers verificados. Gestionamos tanto la captación como la retención de jugadores para marcas de casino y casino cripto.',
    services: [
      { title: 'Marketing de Streamers', description: 'Búsqueda de creadores, ejecución basada en KPI y cobertura multiplataforma en Twitch, YouTube y Kick para captación de nuevos jugadores y retención a largo plazo', tag1: 'Captación', tag2: 'Retención', link: 'Saber Más' },
      { title: 'Marketing de Afiliados', description: 'Creatividades dirigidas al mercado, construcción de comunidad y asociaciones de afiliados basadas en rendimiento que impulsan tanto la captación como la retención de jugadores', tag1: 'Captación', tag2: 'Retención', link: 'Saber Más' },
      { title: 'Marketing de Influencers', description: 'Asociaciones estratégicas con influencers de alto impacto para notoriedad de marca, captación de jugadores y compromiso continuo a través de contenido auténtico', tag1: 'Captación', tag2: 'Retención', link: 'Saber Más' },
    ],
  },
  howWeSolve: {
    badge: 'Nuestro Proceso',
    title: 'Cómo Funciona Nuestro Marketing de',
    titleHighlight: 'Streamers iGaming',
    subtitle: 'Un riguroso sistema de cinco pasos que convierte el gasto en influencers en ingresos medibles y escalables',
    fiveStep: 'sistema de cinco pasos',
    scalable: 'ingresos medibles y escalables',
    cta: 'Véalo en Acción',
    steps: [
      { title: 'Solo Streamers Seleccionados y Verificados', description: 'Invitamos e incorporamos streamers manualmente — solo de nichos de iGaming con resultados pasados verificados, audiencias reales y rendimiento probado en depósitos.', highlight: 'Verificación Manual' },
      { title: 'Selección Rigurosa y Coincidencia de Marca', description: 'Cada streamer es auditado por autenticidad de engagement, demografía de audiencia y rendimiento histórico, y luego emparejado solo con las marcas para las que ya convierte.', highlight: '100% Auténtico' },
      { title: 'Campañas en Vivo Controladas de Alta Intención', description: 'Los streamers van en vivo con juego estructurado, presentación segura para la marca y promoción auténtica — diseñada para atraer jugadores reales de alta intención, no vistas vacías.', highlight: 'Solo Alta Intención' },
      { title: 'Transparencia Total de ROI', description: 'Informes de rendimiento semanales detallados que desglosan cada dólar gastado — costos de streamers, FTDs, depósitos, retención y ROI — claros y responsables.', highlight: 'Informes Semanales' },
      { title: 'Escala lo que Funciona, Retén lo que Convierte', description: 'Duplicamos la apuesta por los streamers ganadores y activamos mecánicas de retención — tablas de clasificación, bonos e incentivos de comunidad — para impulsar depósitos repetidos y mayor LTV.', highlight: 'Escalado Probado' },
    ],
  },
  comparison: {
    badge: 'La Diferencia',
    title: 'Por Qué las Marcas de iGaming nos Eligen en Lugar de',
    titleHighlight: 'Agencias de Marketing Estándar',
    subtitle: 'Métricas medibles que prueban un enfoque fundamentalmente diferente al marketing iGaming',
    standardAgency: 'Agencia Estándar',
    metrics: [
      { label: 'Retención' },
      { label: 'Tasa de Conversión' },
      { label: 'Tiempo hasta Primeros Resultados' },
      { label: 'Transparencia y Eficiencia del Gasto' },
    ],
    features: [
      { category: 'Verificación de Streamers', standard: 'Audiencias no verificadas y mixtas', octo: 'Audiencias verificadas 100% libres de bots' },
      { category: 'Soporte de Campaña', standard: 'Informes PDF mensuales', octo: 'Informes semanales detallados + gestor dedicado' },
      { category: 'Cobertura de Mercado', standard: '1-2 regiones', octo: '25+ mercados, 15+ idiomas' },
      { category: 'Estrategia de Retención', standard: 'No incluida', octo: 'Programas completos de retención y comunidad' },
      { category: 'Cobertura de Plataforma', standard: 'Enfoque en una sola plataforma', octo: 'Twitch, YouTube, Kick y más' },
    ],
    highlights: ['Mejor Control', 'Gran Ejecución', 'Resultados Excepcionales'],
  },
  pricing: {
    title: 'Paquetes de',
    titleHighlight: 'Campaña',
    subtitle: 'Desde una demostración sin riesgo hasta la dominación total del mercado. Elige el nivel que se adapta a tus objetivos.',
    mostPopular: 'Más Popular',
    footerNote: 'Todos los paquetes incluyen seguimiento completo del rendimiento, soporte dedicado e informes transparentes.',
    tiers: [
      { name: 'Campaña Demo', price: '$10,000', period: 'único', tagline: 'Prueba antes de comprometerte', cta: 'Iniciar Demo', features: ['5-10 streamers verificados', '10-15 horas de contenido en vivo', 'Seguimiento completo del rendimiento', 'Informe detallado de ROI', 'Recomendación de escalado'] },
      { name: 'Inicio', price: '$25-50K', period: '/mes', tagline: 'Para marcas en crecimiento que entran en nuevos mercados', cta: 'Solicitar Precio', features: ['15-20 streamers importantes', '30-50 horas de contenido/mes', 'Informes de rendimiento semanales', 'Optimización de campañas', 'Gestor de cuenta dedicado'] },
      { name: 'Crecimiento', price: '$50-75K', period: '/mes', tagline: 'Para marcas listas para escalar agresivamente', cta: 'Solicitar Precio', features: ['50+ streamers micro y macro', '100+ horas de contenido/mes', 'Dashboard de rendimiento en tiempo real', 'Cobertura multiplataforma', 'Soporte prioritario y consultoría estratégica', 'Asociación con sitio web SEO de alta conversión'] },
      { name: 'Empresarial', price: '$100K+', period: '/mes', tagline: 'Para grandes operadores que dominan mercados', cta: 'Contáctanos', features: ['100+ streamers verificados', 'Contenido en vivo ilimitado', 'Asociaciones exclusivas con streamers', 'Opciones white-label', 'Equipo dedicado de especialistas', 'Informes y análisis personalizados', '5 asociaciones con sitios web SEO'] },
    ],
  },
  socialProof: {
    badge: 'Confianza Mundial',
    title: 'La confianza de las principales',
    titleHighlight: 'iGaming',
    titleEnd: 'marcas',
    subtitle: 'Los líderes del sector confían en nuestra red para impulsar la captación, retención y crecimiento',
    stats: [
      { value: '15+', label: 'Marcas Asociadas' },
      { value: '$2.5M', label: 'Presupuesto Gestionado' },
      { value: '20+', label: 'Mercados Cubiertos' },
      { value: '98%', label: 'Retención de Clientes' },
    ],
    testimonials: [
      { quote: 'La estrategia de streamers de Octo Media nos ayudó a escalar rápidamente en mercados clave. Su ejecución y transparencia son de primer nivel.', detail: 'Vimos una mejora inmediata en el engagement de la audiencia y las tasas de conversión en todos los canales de streaming durante el primer mes.', role: 'Brand Manager', company: 'BC.GAME' },
      { quote: 'Trabajar con Octo Media transformó nuestro proceso de captación de jugadores. Su profundo conocimiento de la audiencia iGaming entregó resultados medibles desde el primer día.', detail: 'Su enfoque dirigido en la selección de streamers y la estrategia de contenido resultó en leads de mayor calidad y mejor valor de jugador a largo plazo.', role: 'Jefe de Marketing', company: 'BET365' },
      { quote: 'La calidad de los streamers y el contenido que obtiene Octo Media no tiene igual. La visibilidad de nuestra marca en mercados competitivos creció significativamente en semanas.', detail: 'Desde el primer día, tuvimos acceso a audiencias auténticas y comprometidas que conectaron genuinamente con el mensaje y los valores de nuestra marca.', role: 'Director de Asociaciones', company: 'LEON' },
      { quote: 'Octo Media aportó un enfoque basado en datos a nuestras campañas de influencers que no habíamos visto antes. Las métricas de retención mejoraron en todos los canales que gestionaron.', detail: 'Sus perspectivas estratégicas y optimización continua mantuvieron nuestras campañas funcionando con máxima eficiencia a lo largo del año.', role: 'Líder de Crecimiento', company: 'MELBET' },
      { quote: 'Asociarnos con Octo Media nos dio acceso a una red curada de streamers de alto impacto. El rendimiento de las campañas superó consistentemente nuestros puntos de referencia.', detail: 'Logramos un nivel de consistencia en el rendimiento de las campañas que nos dio confianza para escalar el presupuesto y expandirnos a nuevos mercados.', role: 'Gerente de Captación', company: 'STAKE' },
      { quote: 'La integración sin problemas y el profesionalismo que Octo Media aportó a nuestras campañas los distingue. Su enfoque en la retención de jugadores entregó un ROI excepcional.', detail: 'A diferencia de otras agencias, se preocupan genuinamente por el éxito a largo plazo de la asociación y el valor de vida del jugador, no solo por victorias rápidas.', role: 'Líder de Crecimiento', company: 'TRUSTDICE' },
    ],
  },
  markets: {
    items: [
      { title: 'Casinos Online', description: 'Casinos tradicionales, casinos cripto, casinos Bitcoin, casinos con dealer en vivo' },
      { title: 'Apuestas Deportivas', description: 'Apuestas de fútbol, apuestas de esports, plataformas multideportivas' },
      { title: 'Juegos de Azar Gaming', description: 'Apuestas en CS2, apuestas en Rust, apuestas adyacentes al gaming' },
      { title: 'Salas de Póker', description: 'Póker online, torneos' },
    ],
  },
  contact: {
    title: 'Ponte en',
    titleHighlight: 'Contacto',
    subtitle: '¿Listo para convertir tu presupuesto de marketing en jugadores reales que depositan? Envíanos un mensaje o reserva una consulta gratuita.',
    formTitle: 'Enviar un Mensaje',
    namePlaceholder: 'Tu Nombre',
    emailPlaceholder: 'Dirección de Email',
    messagePlaceholder: 'Tu Mensaje',
    sendButton: 'Enviar Mensaje',
    businessEmail: 'Email de Negocios',
    businessEmailDesc: 'Para asociaciones e inquietudes profesionales',
    telegramSupport: 'Soporte en Telegram',
    telegramDesc: 'Respuestas rápidas y soporte en tiempo real',
    bookTitle: 'Reservar una Consulta Gratuita',
    bookDesc: 'Programa una llamada de 30 minutos para discutir tu estrategia de marketing de influencers.',
    discussLabel: 'Lo que discutiremos',
    scheduleButton: 'Programar tu Llamada',
    topics: [
      'Tu estrategia actual de captación de jugadores',
      'Cómo el marketing verificado de influencers se adapta a tus objetivos',
      'ROI esperado de la campaña demo',
      'Propuesta de campaña personalizada para tu marca',
    ],
    responseTime: 'Tiempo de Respuesta',
    responseTimeValue: 'Normalmente responde en 15-30 minutos',
    availability: 'Disponibilidad',
    availabilityValue: 'Activo: 7 días a la semana',
    supportType: 'Tipo de Soporte',
    supportTypeValue: 'Consultas de streamers, planificación de campañas, asociaciones',
  },
  finalCta: {
    badge: 'Disponibilidad Limitada',
    title1: 'Tus Competidores Ya Están',
    title2: 'Escalando con Nosotros',
    subtitle: 'Cada día que esperas es otro día de gasto publicitario desperdiciado en influencers no verificados con seguidores falsos.',
    body: 'Solo aceptamos un número limitado de marcas por trimestre para garantizar una ejecución de calidad. Asegura tu lugar antes de que lo hagan tus competidores.',
    cta: 'Obtener tu Plan de Crecimiento Gratis',
    guarantees: ['Sin contratos a largo plazo', 'Seguimiento 100% transparente', 'Resultados en 2 semanas', 'Gestor de cuenta dedicado'],
  },
  demo: {
    badge: 'Riesgo Cero',
    title1: '¿No estás convencido?',
    title2: 'Véenos en Acción',
    subtitle: 'Danos $10,000 y dos semanas. Si no entregamos resultados medibles, lo sabrás antes de comprometer un presupuesto mayor.',
    steps: [
      { title: 'Inversión de $10,000', description: 'Costo fijo, sin tarifas ocultas. Sabes exactamente lo que pagas.' },
      { title: 'Campaña de 2 Semanas', description: '5-10 streamers verificados van en vivo promoviendo tu marca.' },
      { title: 'Resultados Medibles', description: 'Informe completo de rendimiento con datos de ROI y plan de escalado.' },
    ],
    whatsIncluded: 'Qué Incluye',
    includes: [
      'Streamers verificados seleccionados para tu marca',
      '10-15 horas de contenido de streamer en vivo',
      'Acceso al dashboard de seguimiento en tiempo real',
      'Informe detallado de ROI y rendimiento',
      'Recomendación de escalado sin compromiso',
    ],
    noContract: 'No se requiere contrato a largo plazo. Los resultados hablan por sí solos.',
    pilotLabel: 'Campaña piloto de 2 semanas',
    cta: 'Programar tu Llamada Demo',
  },
  streamersSection: {
    badge: 'Para Streamers',
    title: 'Haz Crecer tu',
    titleHighlight: 'Carrera en Streaming',
    subtitle: 'Únete a nuestra red de 750+ streamers verificados y conéctate con las principales marcas de iGaming. Nosotros gestionamos el lado comercial para que puedas enfocarte en crear contenido.',
    benefits: [
      'Acceso a marcas premium de iGaming',
      'Tarifas de comisión competitivas',
      'Pagos confiables y puntuales',
      'Gestor de asociaciones dedicado',
      'Bonos de rendimiento y exclusivos',
      'Soporte multiplataforma (Twitch, YouTube, Kick)',
    ],
    cta: 'Aplicar Ahora',
    verifiedStreamers: 'Streamers Verificados',
    avgEarnings: 'Ganancias mensuales promedio',
    avgEarningsValue: '$2,000 - $15,000',
    platforms: 'Plataformas soportadas',
    platformsValue: 'Twitch, YT, Kick',
    paymentSchedule: 'Calendario de pagos',
    paymentScheduleValue: 'Quincenal',
    markets: 'Mercados disponibles',
    marketsValue: '25+ países',
  },
  streamersPage: {
    hero: {
      badge: 'Para Streamers y Creadores',
      title1: 'Deja de Perseguir Acuerdos.',
      title2: 'Empieza a',
      titleHighlight: 'Ganar',
      subtitle: 'La red de streamers de iGaming que conecta creadores verificados con las mejores marcas de casino y cripto para patrocinios continuos.',
      subtitleSmall: 'Mejores tarifas. Pagos más rápidos. Sin complicaciones.',
      cta: 'Aplicar Ahora',
    },
    benefits: {
      badge: 'Ecosistema Completo de Asociación',
      title: 'Por Qué',
      titleHighlight: 'Trabajar con Nosotros',
      subtitle: 'Más que simples acuerdos de marca. Un ecosistema completo diseñado para maximizar tu potencial de ingresos y proteger tus intereses en cada paso.',
      commissionNote: '10% de comisión sobre los acuerdos que cerramos para ti',
      commissionSub: 'Solo se cobra después de que recibas el pago. Riesgo cero, máxima transparencia.',
      items: [
        { title: 'Gestor Personal 24/7', desc: 'Tu gestor de cuenta dedicado está disponible las 24 horas para manejar todas tus consultas, negociaciones y coordinación de campañas.' },
        { title: 'Sin Exclusividad Requerida', desc: '¿Encontraste un mejor acuerdo tú mismo? ¡Adelante! Proporcionamos consulta gratuita para que conozcas tu verdadero valor en el mercado.' },
        { title: 'Sin Costos Iniciales', desc: 'Sin cuotas de suscripción ni cargos ocultos. Tomamos un 10% fijo solo después de que recibas el pago de tu campaña. Simple y transparente.' },
        { title: 'Solo Marcas Verificadas', desc: 'No más fraudes ni pagos retrasados. Trabaja hoy, cobra hoy. Directamente a tu cuenta bancaria o billetera cripto.' },
        { title: 'Estructuras de Acuerdos Flexibles', desc: '¿Prefieres saldo directo, tarifas fijas o participación en ingresos de por vida? Personalizamos los acuerdos según tus preferencias y estilo de contenido.' },
        { title: 'Sin Contratos a Largo Plazo', desc: '¿Necesitas un descanso o tienes problemas? Retírate en cualquier momento. Sin penalizaciones, sin preguntas. Te respaldamos.' },
        { title: 'Soporte para Construir tu Marca', desc: 'Más allá de los acuerdos, te ayudamos a construir tu marca personal con configuración de sitio web, estrategia en redes sociales y orientación profesional de contenido.' },
        { title: 'Acceso a Eventos Exclusivos', desc: 'Invitaciones a reuniones presenciales en todo el mundo. Te costeamos el viaje, todos los gastos pagados. Conecta con los mejores streamers y líderes de la industria.' },
        { title: 'Innovación Continua', desc: 'Nuestra plataforma evoluciona con nuevas funciones, herramientas y oportunidades. Únete para dar forma al futuro de la monetización de creadores.' },
      ],
    },
    howItWorks: {
      title: 'Cómo',
      titleHighlight: 'Funciona',
      subtitle: 'De la solicitud al pago en cuatro pasos simples',
      step: 'PASO',
      steps: [
        { title: 'Aplicar', desc: 'Completa una solicitud rápida con información de tu canal, plataforma y tamaño de audiencia.' },
        { title: 'Ser Verificado', desc: 'Nuestro equipo revisa la calidad de tu contenido, la autenticidad de tu audiencia y tus métricas de engagement.' },
        { title: 'Ser Emparejado', desc: 'Te emparejamos con marcas de iGaming y casino cripto que se adaptan a tu nicho, audiencia y estilo de contenido para máximos resultados.' },
        { title: 'Crea y Cobra', desc: 'Transmite contenido de iGaming patrocinado y recibe pagos rápidos y confiables directamente en tu cuenta.' },
      ],
    },
    faq: {
      title: 'Preguntas',
      titleHighlight: 'Frecuentes',
      subtitle: 'Preguntas comunes de streamers que se unen a nuestra red',
      items: [
        { q: '¿Cuánto puedo ganar?', a: 'Las ganancias varían según el tamaño de tu audiencia, engagement y calidad del contenido. Nuestros streamers típicamente ganan entre $500 y $15,000+ por mes en acuerdos de marca a través de nuestra red.' },
        { q: '¿Qué plataformas soportan?', a: 'Trabajamos con streamers en Twitch, YouTube, Kick y otras plataformas de streaming principales. Si tienes una audiencia activa en cualquier plataforma de streaming, queremos saber de ti.' },
        { q: '¿Qué pasa si tengo menos de 5,000 seguidores?', a: 'Ocasionalmente trabajamos con creadores más pequeños que tienen tasas de engagement excepcionales. Aplica de todos modos y nuestro equipo revisará tu perfil. La calidad de la audiencia importa más que los números brutos.' },
        { q: '¿Qué tipo de contenido necesitaré crear?', a: 'Streams patrocinados con marcas de iGaming y casino cripto. El formato específico y los requisitos varían según la marca, pero siempre trabajamos contigo para que el contenido se sienta natural y auténtico.' },
        { q: '¿Cuánto duran los contratos?', a: 'La mayoría de los acuerdos son mes a mes sin compromisos a largo plazo. Algunas asociaciones premium pueden durar 3-6 meses, pero siempre conocerás los términos de antemano antes de comprometerte.' },
        { q: '¿Cobran comisión?', a: 'Las marcas nos pagan a nosotros, no tú. La tarifa que negociamos en tu nombre es lo que recibes. No hay tarifas ocultas ni deducciones de tus ganancias.' },
        { q: '¿Puedo trabajar con otras agencias al mismo tiempo?', a: 'Sí. No tenemos requisitos de exclusividad. Eres libre de trabajar con otras agencias y tomar acuerdos directos. Solo pedimos que honres los compromisos de campañas activas.' },
        { q: '¿Cuánto tiempo toma el proceso de solicitud?', a: 'Típicamente 2-5 días hábiles. Revisamos tu canal, verificamos tus métricas de audiencia y, si eres aprobado, podrías recibir tu primer acuerdo de marca en una semana.' },
      ],
    },
    form: {
      title: 'Aplicar',
      titleHighlight: 'Ahora',
      subtitle: 'Completa el formulario a continuación y nuestro equipo revisará tu solicitud',
      fullName: 'Nombre Completo *',
      emailAddress: 'Dirección de Email *',
      primaryPlatform: 'Plataforma Principal *',
      followerCount: 'Número de Seguidores *',
      profileUrl: 'URL de Perfil / Canal *',
      telegramHandle: 'Usuario de Telegram (opcional)',
      describeContent: 'Describe tu Contenido *',
      selectPlatform: 'Seleccionar plataforma',
      selectRange: 'Seleccionar rango',
      namePlaceholder: 'Tu nombre',
      contentPlaceholder: 'Cuéntanos sobre tu contenido, audiencia y qué tipo de acuerdos de marca te interesan...',
      submitButton: 'Enviar Solicitud',
      successTitle: 'Solicitud Enviada',
      successBody: 'Tu cliente de email se ha abierto con los detalles de tu solicitud. Envía el email para completar tu envío. Revisaremos tu perfil y te responderemos en 2-5 días hábiles.',
      submitAnother: 'Enviar Otra Solicitud',
    },
    whyJoin: {
      title: 'Por Qué Unirte a Nuestra',
      titleHighlight: 'Red',
      subtitle: 'Lo construimos para creadores cansados de acuerdos poco confiables y ofertas bajas',
      items: [
        { title: 'Acuerdos Constantes', desc: 'Patrocinios mensuales recurrentes de iGaming para que siempre tengas deals de marca casino listos. No más búsqueda de campañas únicas.' },
        { title: 'Mejores Tarifas', desc: 'Negociamos tarifas premium en tu nombre usando nuestro apalancamiento de red. Gana más por hora de contenido que en solitario.' },
        { title: 'Manejamos el Negocio', desc: 'Contratos, facturación, negociaciones, cumplimiento. Gestionamos el papeleo para que puedas centrarte en transmitir.' },
        { title: 'Pagos Rápidos', desc: 'Recibe el pago en 7-14 días. Sin perseguir marcas durante meses. Garantizamos pagos puntuales y confiables.' },
        { title: 'Marcas Gaming-Friendly', desc: 'Trabaja con marcas reputadas de iGaming y casino cripto, plataformas de apuestas y empresas de juegos que se alinean con tu audiencia.' },
        { title: 'Sin Ataduras', desc: 'Trabaja con nosotros en tus términos. Sin contratos de exclusividad. Eres libre de colaborar con otras agencias y marcas.' },
      ],
    },
    whatYouGet: {
      badge: 'Características Principales',
      title: 'La',
      titleHighlight: 'Ventaja Octo',
      subtitle: 'Todo lo que necesitas para monetizar tu contenido profesionalmente y escalar tu negocio de creador',
      items: [
        { title: 'Asociaciones Recurrentes', desc: 'Acuerdos de marca a largo plazo que proporcionan ingresos estables y predecibles mes a mes.' },
        { title: 'Tarifas Premium', desc: 'Nuestro volumen y reputación nos permiten negociar CPMs y tarifas fijas más altas de lo que podrías obtener solo.' },
        { title: 'Soporte Completo', desc: 'Gerente de asociación dedicado, manejo de contratos, briefs creativos y soporte de cumplimiento.' },
        { title: 'Pagos Rápidos', desc: 'Ciclos de pago de 7-14 días. Sin esperar 60-90 días. Pagamos a tiempo, siempre.' },
        { title: 'Emparejamiento Dirigido de Marcas', desc: 'Emparéjate con marcas de iGaming y casino cripto que resuenen con tu audiencia específica para patrocinios auténticos.' },
        { title: 'Flexibilidad', desc: 'Sin exclusividad. Trabaja con múltiples marcas y agencias. Escala hacia arriba o abajo en tus términos.' },
      ],
    },
    eligibility: {
      title: 'Requisitos de',
      titleHighlight: 'Elegibilidad',
      subtitle: 'Asegúrate de cumplir los requisitos básicos antes de aplicar',
      items: [
        { title: '5,000+ Seguidores', desc: 'Número mínimo de seguidores en tu plataforma de streaming principal.' },
        { title: 'Contenido Gaming / Gambling', desc: 'Tu contenido debe ser de gaming o relacionado con gambling para alinearse con nuestros socios de marca.' },
        { title: 'Presencia en Plataforma Principal', desc: 'Activo en Twitch, YouTube, Kick u otras plataformas de streaming principales.' },
        { title: 'Engagement Auténtico', desc: 'Espectadores reales e interacción genuina. Verificamos la calidad del engagement, no solo los números.' },
        { title: 'Disponibilidad Global', desc: 'Trabajamos con streamers de todo el mundo. Todas las regiones e idiomas son bienvenidos.' },
        { title: 'Horario Consistente', desc: 'Horario de streaming regular con producción de contenido confiable y retención de audiencia.' },
      ],
    },
    comparison: {
      badge: 'La Elección Clara',
      title: 'Agencias Tradicionales vs',
      titleHighlight: 'Octo Media',
      subtitle: 'Descubre por qué miles de streamers están cambiando de agencias tradicionales a nuestra plataforma',
      traditionalLabel: 'Tradicional',
      traditionalAgency: 'Agencia Tradicional',
      octoMedia: 'Octo Media',
      metrics: [
        { label: 'Tasa de Comisión', traditional: '20-40%', us: '10%' },
        { label: 'Plazo de Pago', traditional: '60-90 días', us: 'Mismo día' },
        { label: 'Duración del Contrato', traditional: '12-24 meses', us: 'Sin ataduras' },
        { label: 'Valor Promedio del Deal', traditional: '$2-5K/mes', us: '$8-15K/mes' },
      ],
      features: [
        { category: 'Exclusividad', traditional: 'Requerida - No puedes trabajar con otras agencias', us: 'Opcional - Trabaja con múltiples socios libremente' },
        { category: 'Costos Iniciales', traditional: 'Tarifas de configuración, suscripciones mensuales', us: 'Cero costos iniciales o tarifas ocultas' },
        { category: 'Verificación de Marcas', traditional: 'Screening mínimo, retrasos de pago comunes', us: '100% marcas verificadas, pagos garantizados' },
        { category: 'Soporte Personal', traditional: 'Gerente compartido para 50+ creadores', us: 'Gerente personal dedicado 24/7' },
        { category: 'Flexibilidad de Deals', traditional: 'Solo paquetes estándar', us: 'Deals personalizados según tus preferencias' },
        { category: 'Salida del Contrato', traditional: 'Penalizaciones y períodos de aviso', us: 'Retírate cuando quieras, sin penalizaciones' },
        { category: 'Soporte de Carrera', traditional: 'Limitado a corretaje de deals', us: 'Soporte completo de construcción de marca y crecimiento' },
      ],
      highlights: ['Menor Comisión', 'Pagos Más Rápidos', 'Mayores Ganancias'],
    },
  },
  whyUsPage: {
    hero: {
      badge: 'POR QUÉ OCTOMEDIA',
      title: 'Creado por Insiders del Casino,\nNo por Foráneos del Marketing',
      subtitle: 'OctoMedia fue fundada por ocho veteranos de iGaming que pasaron años dentro de casinos reales y plataformas de casino cripto — gestionando captaciones, retención, lanzamientos y cumplimiento normativo. La única agencia de marketing iGaming que combina enfoque específico en streamers, especialización en casino cripto y un equipo fundador de ex operadores. Entendemos FTDs, LTV y retención porque hemos sido medidos por ellos.',
      point1: 'Ex Profesionales de Casino y Casino Cripto',
      point2: 'Especialistas en Marketing de Streamers iGaming',
      point3: 'Escalado con Conciencia Normativa',
    },
    differentiators: {
      title: 'Qué Nos Hace Diferentes',
      subtitle: 'OctoMedia no es solo otra agencia de marketing. Estamos construidos de manera diferente porque venimos del interior de la industria.',
      items: [
        { title: 'Mentalidad de Operador', description: 'Pensamos como operadores de casino porque fuimos operadores de casino. Cada decisión se filtra a través de KPIs del mundo real y restricciones operativas.' },
        { title: 'Enfoque en FTD, LTV y Retención', description: 'Optimizamos las métricas que importan: depósitos por primera vez, valor de por vida, tasas de segundo depósito y retención de jugadores a largo plazo.' },
        { title: 'Marketing de Influencers Basado en Datos', description: 'Sin métricas vacías. Rastreamos tasas de conversión, costo por FTD y calidad de audiencia en cada streamer y creador de contenido.' },
        { title: 'Escalado con Conciencia Normativa', description: 'Estrategias de crecimiento construidas con conciencia regulatoria. Sabemos qué mercados requieren mensajes cuidadosos y qué influencers presentan riesgo de cumplimiento.' },
        { title: 'Acceso a Red de la Industria', description: 'Relaciones directas con streamers de primer nivel, redes de afiliados y compradores de medios que realmente entienden iGaming y casino cripto.' },
        { title: 'Valor de Marca a Largo Plazo', description: 'Equilibramos la captación agresiva con la construcción sostenible de marca. Victorias a corto plazo sin daño a largo plazo.' },
      ],
    },
    foundingStory: {
      title: 'Cómo Empezamos',
      body1: 'Nos conocimos en diferentes roles de casino — jefes de captación, líderes de retención, gestores de afiliados, estrategas de cumplimiento. Algunos de nosotros lanzamos casinos cripto desde cero. Otros escalamos marcas establecidas en múltiples GEOs.',
      body2: '¿La frustración común? Agencias de marketing que no entendían verdaderamente iGaming.',
      body3: 'Vendían "conciencia" e "engagement" mientras nosotros éramos medidos en depósitos por primera vez, tasas de segundo depósito y valor de por vida. No podían hablar el idioma de los acuerdos CPA, protección contra abuso de bonos o riesgo regulatorio.',
      body4: 'Así que construimos OctoMedia — una agencia dirigida por personas que ya han estado del lado del operador. Sabemos lo que funciona porque hemos gestionado presupuestos, dirigido campañas de influencers y optimizado embudos bajo presión real.',
      closing: 'No estamos adivinando. Ya lo hemos hecho.',
      cards: [
        { heading: 'De Dónde Venimos', text: 'Nos conocimos en diferentes roles de casino — jefes de captación, líderes de retención, gestores de afiliados, estrategas de cumplimiento. Algunos de nosotros lanzamos casinos cripto desde cero.' },
        { heading: 'La Frustración', text: 'Agencias de marketing que no entendían verdaderamente iGaming. Vendían "conciencia" e "engagement" mientras éramos medidos en depósitos por primera vez, tasas de segundo depósito y valor de por vida.' },
        { heading: 'El Vacío que Vimos', text: 'No podían hablar el idioma de los acuerdos CPA, protección contra abuso de bonos o riesgo regulatorio. Nadie cerraba la brecha entre el marketing de influencers y los KPIs reales del operador.' },
        { heading: 'Por Qué Construimos OctoMedia', text: 'Una agencia dirigida por personas que ya han estado del lado del operador. Sabemos lo que funciona porque hemos gestionado presupuestos, dirigido campañas y optimizado embudos bajo presión real.' },
      ],
    },
    foundingTeam: {
      title: 'Conoce al Equipo Fundador',
      subtitle: 'Ocho veteranos del casino que construyeron sus carreras dentro de la industria, no fuera de ella.',
      yearsLabel: 'Años',
      exLabel: 'Ex:',
      strengthLabel: 'Fortaleza:',
    },
    closing: {
      badge: 'LA DIFERENCIA ES CLARA',
      title: 'Ya Hemos Estado\nen el Interior de iGaming',
      subtitle: 'OctoMedia fue construida por personas que han dirigido captaciones de casino y casino cripto, gestionado campañas de influencers de iGaming de millones de dólares y optimizado embudos de retención bajo presión real. No solo entendemos el marketing de streamers iGaming — lo hemos vivido.',
      cta1: 'Explorar Asociaciones con Streamers',
      cta2: 'Contáctanos',
      stat1Value: '8',
      stat1Label: 'Veteranos Fundadores',
      stat2Value: '62',
      stat2Label: 'Años de Experiencia Combinados',
      stat3Value: '100%',
      stat3Label: 'Ex Profesionales de Casino',
    },
  },
  servicesPage: {
    badge: 'NUESTROS SERVICIOS',
    heroBadge: 'Servicios de Marketing iGaming',
    heroTitle: 'Marketing de Performance para',
    heroTitleHighlight: 'Operadores iGaming',
    heroSubtitle: 'Tres canales de captación probados — campañas con streamers, programas de afiliados y marketing de influencers — gestionados de extremo a extremo por ex-operadores de casino.',
    tab1: 'Marketing de Streamers',
    tab2: 'Marketing de Afiliados',
    tab3: 'Marketing de Influencers',
    howItWorksLabel: 'Cómo Funciona',
    whatYouGetLabel: 'Qué Obtienes',
    inlineCta1: '¿Quieres ver resultados de streamers antes de comprometer un presupuesto completo?',
    inlineCta2: '¿Listo para crear un programa de afiliados compliant y de alta conversión?',
    inlineCtaNote: 'Sin compromiso a largo plazo. Mira los resultados antes de escalar.',
    inlineCtaBtn: 'Reservar una Llamada Estratégica Gratis',
    closingBadge: 'Cero Compromiso a Largo Plazo',
    trustSignals: ['Sin contratos a largo plazo', '100% transparencia de gasto', 'Resultados en 2 semanas', 'Gestor de cuenta dedicado'],
    stats: [
      { value: '25+', label: 'Mercados Cubiertos' },
      { value: '750+', label: 'Streamers Verificados' },
      { value: '3–5x', label: 'ROI Promedio' },
      { value: '2 Semanas', label: 'Primeros Resultados' },
    ],
    streamerSection: {
      badge: 'Marketing de Streamers de Casino',
      title: 'Streamers Verificados.',
      titleHighlight: 'Depósitos Probados.',
      subtitle: 'Twitch · YouTube · Kick — 25+ Mercados',
      positioning: 'Cada streamer en nuestra red es seleccionado manualmente de nichos de iGaming, auditado por engagement real de audiencia y emparejado solo con marcas para las que ya convierte. Gestionamos la ejecución de extremo a extremo — desde el briefing de cumplimiento hasta los informes ROI semanales.',
      accordion1Label: 'Qué incluye una Campaña con Streamers',
      accordion1Items: [
        'Streamers verificados de casino en Twitch, YouTube y Kick',
        'Campañas de influencers de casino conformes con estándares de juego responsable',
        'Ejecución basada en KPI: FTDs, depósitos, retención de jugadores y costo por adquisición',
        'Informes ROI semanales por streamer — transparencia total de gastos vs. resultados',
        'Experiencia en casino cripto, casino online y marcas de apuestas deportivas',
        'Cobertura en 25+ mercados — Europa, LATAM, América del Norte, Oceanía y APAC',
      ],
      accordion2Label: 'Plataformas y Cumplimiento',
      accordion2Items: [
        'Campañas de streaming en vivo en Twitch, YouTube Live y Kick simultáneamente',
        'Selección de streamers geo-dirigida para tus mercados con licencia',
        'Disclaimers de juego responsable integrados en cada brief de campaña',
        'Filtros de verificación de edad de audiencia aplicados antes del lanzamiento',
        'Contenido revisado contra estándares regulatorios de UK, MGA, Curaçao y locales',
      ],
      steps: [
        { num: '01', title: 'Brief y Ajuste de Marca', desc: 'Analizamos tus GEOs objetivo, perfil de jugador y requisitos de cumplimiento para crear un brief preciso.' },
        { num: '02', title: 'Búsqueda de Streamers', desc: 'Seleccionados a mano de nuestra red verificada — emparejados por nicho, geografía de audiencia e historial de conversión de depósitos.' },
        { num: '03', title: 'Ejecución de Campaña en Vivo', desc: 'Los streamers van en vivo con gameplay estructurado, contenido seguro para la marca y promoción auténtica a jugadores de alta intención.' },
        { num: '04', title: 'Seguimiento en Tiempo Real', desc: 'Acceso al dashboard + informes semanales: FTDs, depósitos, costo por jugador, retención y desglose completo de ROI.' },
        { num: '05', title: 'Escalar y Retener', desc: 'Apostar doble por los mejores, activar mecánicas de retención y expandirse a mercados adyacentes.' },
      ],
      featureTexts: [
        'Audiencias sin bots — verificadas manualmente antes del onboarding',
        'Ejecución orientada a KPIs: FTDs, depósitos y costo por adquisición',
        'Informes ROI semanales por streamer, gastos vs. resultados',
        '25+ mercados — Europa, LATAM, América del Norte, APAC y Oceanía',
        'Briefing compliance-first alineado con leyes de juego responsable',
        'Multiplataforma: Twitch, YouTube y Kick simultáneamente',
      ],
    },
    affiliateSection: {
      badge: 'Marketing de Afiliados iGaming',
      title: 'Programas de Afiliados',
      titleHighlight: 'que Realmente Convierten.',
      subtitle: 'CPA · Revenue Share · Híbrido — Construido por Operadores',
      positioning: 'Creados por personas que han gestionado canales de afiliados desde el lado del operador. Diseñamos estructuras de comisiones en torno a la economía real del jugador — no recuentos de clics inflados — y gestionamos cada asociación con seguimiento en vivo y reportes transparentes de costo por FTD.',
      accordion1Label: 'Qué incluye la Gestión de Afiliados',
      accordion1Items: [
        'Modelos de comisión CPA, revenue share e híbridos basados en rendimiento',
        'Creatividades conformes con el juego y páginas de destino geo-dirigidas',
        'Construcción de comunidad y estrategias de engagement para retención a largo plazo',
        'Seguimiento de afiliados en tiempo real e informes de conversión transparentes',
        'Gestión de programas de afiliados iGaming con conciencia normativa',
        'Infraestructura de afiliados escalable desde startups hasta marcas enterprise',
      ],
      accordion2Label: 'Reporting y Transparencia',
      accordion2Items: [
        'Acceso al dashboard en tiempo real para todas las asociaciones de afiliados activas',
        'Desglose semanal: clics, registros, FTDs, volumen de depósitos y CPA',
        'Segmentación por afiliado y por GEO',
        'Detección de fraude y monitoreo de calidad de tráfico',
        'Revisión estratégica mensual y llamadas de optimización del programa',
      ],
      featureTexts: [
        'Modelos CPA, revenue share e híbridos diseñados en torno a la economía real del operador',
        'Creatividades conformes y páginas de destino geo-dirigidas',
        'Seguimiento de conversiones en tiempo real y reportes transparentes',
        'Estrategias de construcción de comunidad para retención a largo plazo',
        'Infraestructura escalable desde operadores tempranos hasta enterprise',
        'Gestión de programas de afiliados por ex-líderes de captación de casino',
      ],
    },
    influencerSection: {
      badge: 'Marketing de Influencers de Juego',
      title: 'Jugadores de Alto LTV',
      titleHighlight: 'de Creadores de Confianza.',
      subtitle: 'YouTube · TikTok · Twitch · Kick — Performance-First',
      positioning: 'Emparejamos marcas de iGaming y casino cripto con influencers de juego verificados cuyas audiencias ya interactúan con contenido de casino. Cada campaña está orientada a jugadores que depositan realmente — no a impresiones vacías — con seguimiento completo de conversiones desde el primer clic hasta el segundo depósito.',
      accordion1Label: 'Qué incluye en Campañas de Influencers',
      accordion1Items: [
        'Red verificada de influencers de juego en YouTube, TikTok, Twitch y Kick',
        'Gestión de campañas iGaming de extremo a extremo desde el brief hasta el informe ROI',
        'Modelos de notoriedad de marca y captación de jugadores para casino y apuestas deportivas',
        'Selección de creadores por geo, nicho e historial de contenido iGaming',
        'Briefings de influencers conformes alineados con regulaciones de juego responsable',
        'Seguimiento completo de conversiones: FTDs, depósitos, LTV y costo por jugador captado',
      ],
      accordion2Label: 'Proceso de Vetting de Creadores',
      accordion2Items: [
        'Auditoría manual de demografía de audiencia, tasas de engagement y distribución geo',
        'Revisión de rendimiento histórico: datos de conversión de campañas iGaming pasadas',
        'Detección de bots y seguidores falsos a través de herramientas de análisis de terceros',
        'Verificación de alineación de marca: estilo de contenido, tono e intención de audiencia',
        'Revisión del historial de cumplimiento antes de cualquier presentación de marca',
      ],
      featureTexts: [
        'Red verificada en YouTube, TikTok, Twitch y Kick',
        'Selección de creadores por geo, nicho e historial iGaming',
        'Briefings de influencers conformes alineados con regulaciones de juego',
        'Seguimiento completo de conversiones: FTDs, LTV y costo por jugador',
        'Modelos de notoriedad de marca y adquisición directa disponibles',
        'Gestión de extremo a extremo desde el brief hasta el análisis post-campaña',
      ],
    },
    title: 'Servicios de Marketing de Influencers iGaming',
    subtitle: 'Marketing de streamers de casino orientado al rendimiento, campañas de influencers de juego y programas de afiliados iGaming — creados por insiders de la industria para marcas de casino cripto, casino online y apuestas deportivas en todo el mundo.',
    services: [
      {
        id: 'streamer-marketing',
        title: 'Marketing de Streamers iGaming',
        description: 'Nuestro servicio insignia de marketing de streamers de casino conecta marcas de iGaming, casino cripto y apuestas deportivas con streamers de juego verificados y de alto rendimiento en Twitch, YouTube y Kick. A diferencia de las agencias genéricas de influencers, cada streamer en nuestra red es verificado manualmente por engagement real de audiencia, segmentación geográfica y un historial probado de impulsar depósitos por primera vez (FTDs) en el espacio iGaming. Gestionamos la campaña de principio a fin — desde la búsqueda de streamers y briefing de cumplimiento hasta la ejecución de contenido en vivo e informes de ROI semanales.',
        cta: 'Obtener Plan de Crecimiento Gratis',
        features: ['Streamers verificados de casino en Twitch, YouTube y Kick', 'Campañas de influencers de casino conformes con estándares de juego responsable', 'Ejecución basada en KPIs: FTDs, depósitos, retención de jugadores y costo por captación', 'Informes de ROI semanales por streamer — transparencia completa de gasto vs. resultados', 'Experiencia en casino cripto, casino online y marcas de apuestas deportivas', 'Cobertura en 25+ mercados — Europa, LATAM, América del Norte, Oceanía y APAC'],
      },
      {
        id: 'affiliate-marketing',
        title: 'Marketing de Afiliados iGaming',
        description: 'Construimos y gestionamos programas de marketing de afiliados basados en rendimiento para marcas de iGaming, incluyendo casinos cripto, casinos online y plataformas de apuestas deportivas. Nuestro enfoque de afiliados iGaming está fundamentado en experiencia real de operador — diseñamos modelos de comisión CPA, participación en ingresos e híbridos que impulsan una captación sostenida de jugadores a un costo por FTD controlado. Cada asociación de afiliados se gestiona con activos creativos conformes, seguimiento de conversiones en tiempo real e informes transparentes.',
        cta: 'Discutir Estrategia de Afiliados',
        features: ['Modelos de comisión CPA, participación en ingresos e híbridos basados en rendimiento', 'Activos creativos conformes con el juego e páginas de destino geo-segmentadas', 'Estrategias de construcción de comunidad y engagement para retención de jugadores a largo plazo', 'Seguimiento de afiliados en tiempo real e informes de conversión transparentes', 'Gestión de programas de afiliados iGaming con conciencia normativa', 'Infraestructura de afiliados escalable desde startups hasta marcas de casino empresariales'],
      },
      {
        id: 'influencer-marketing',
        title: 'Marketing de Influencers iGaming',
        description: 'Campañas estratégicas de marketing de influencers de juego diseñadas específicamente para plataformas de iGaming y casino cripto. Conectamos marcas con influencers verificados de casino, canales de YouTube sobre juego, creadores de casino en TikTok y streamers de Kick que tienen audiencias auténticas comprometidas con el gaming online y cripto — entregando notoriedad de marca medible, captación de jugadores y retención de alto LTV. Nuestra estrategia está orientada al rendimiento desde el primer día: cada campaña está diseñada para entregar jugadores que depositan realmente, no impresiones vacías.',
        cta: 'Planificar una Campaña de Influencers',
        features: ['Red verificada de influencers de juego en YouTube, TikTok, Twitch y Kick', 'Gestión completa de campañas de influencers iGaming desde el briefing hasta el informe de ROI', 'Modelos de notoriedad de marca y captación de jugadores para casinos y apuestas deportivas', 'Selección de creadores por geo, nicho e historial de contenido iGaming', 'Briefings conformes de influencers alineados con regulaciones de juego responsable', 'Seguimiento completo de conversiones: FTDs, depósitos, LTV y costo por jugador captado'],
      },
    ],
    whatsIncluded: 'Qué Incluye:',
    closing: {
      title: '¿Listo para Escalar tu Captación de Jugadores iGaming?',
      body: 'Reserva una llamada estratégica gratuita de 30 minutos. Revisaremos tu estrategia actual de captación de jugadores y te mostraremos exactamente cómo nuestro marketing de influencers de casino y las campañas con streamers de juego pueden impulsar jugadores reales que depositan con ROI medible.',
      cta1: 'Programar Llamada Estratégica Gratis',
      cta2: 'Contratar Streamers de Casino',
    },
  },
  resourcesPage: {
    badge: 'Recursos de Marketing iGaming',
    title: 'Guías de Marketing de Influencers iGaming',
    subtitle: 'Recursos detallados sobre estrategia de marketing de influencers de casino, cumplimiento de publicidad en juego, medición de ROI y tendencias de marketing de casino cripto — escritos por insiders de la industria iGaming.',
    readTime: 'min de lectura',
    ctaTitle: '¿Listo para Aplicar estas Estrategias?',
    ctaBody: 'Nuestro equipo de marketing iGaming implementa estas estrategias cada día para marcas de casino cripto y casino online. Reserva una consulta gratuita de 30 minutos.',
    ctaButton: 'Reservar Llamada Estratégica Gratis',
    articles: [
      { badge: 'Estrategia', title: 'ROI del Marketing de Influencers iGaming: Lo que las Marcas Realmente Obtienen', description: 'Un análisis basado en datos de métricas reales de ROI, referencias de costo por FTD y cómo medir el rendimiento de las campañas.', readTime: 8 },
      { badge: 'Cumplimiento', title: 'Cumplimiento del Marketing de Influencers de Juego: UK, Malta, Curazao y EE.UU.', description: 'Desglose región por región de las regulaciones de publicidad de casino, requisitos de juego responsable y marcos de campañas conformes.', readTime: 10 },
      { badge: 'Comparación', title: 'Afiliados vs. Influencers para iGaming: ¿Cuál Genera Mejor ROI?', description: 'Una comparación directa de programas de afiliados iGaming vs. campañas de influencers — estructuras de costos, tasas de conversión y cuándo usar cada uno.', readTime: 7 },
      { badge: 'Tendencias', title: 'Tendencias de Marketing de Casino Cripto 2026: Streamers, Web3 y Captación', description: 'Las últimas tendencias que dan forma al marketing de casino cripto y juego blockchain — desde streamers de Twitch hasta campañas de influencers nativas de Web3.', readTime: 9 },
      { badge: 'Guía de Plataforma', title: 'Marketing de Casino en Twitch: La Guía Completa de Marca para 2026', description: 'Cómo ejecutar patrocinios efectivos de casino en Twitch — encontrar streamers de juego, estructurar acuerdos, consideraciones de cumplimiento y seguimiento de ROI.', readTime: 11 },
      { badge: 'Estrategia', title: 'Estrategia de Marketing de Influencers de Apuestas de Esports para Casas de Apuestas', description: 'Cómo las marcas de apuestas deportivas y esports pueden aprovechar influencers de gaming, streamers de esports y creadores de contenido para impulsar jugadores que depositan.', readTime: 8 },
    ],
  },
  faq: {
    title: 'Preguntas',
    titleHighlight: 'Frecuentes',
    subtitle: 'Todo lo que necesitas saber sobre la compra de medios con influencers verificados',
    items: [
      { q: '¿Qué te hace diferente de otras agencias?', a: 'La mayoría de las agencias venden alcance. Nosotros entregamos streamers verificados, jugadores reales y ROI medible. Cada campaña está construida en torno a depósitos, retención y LTV — no métricas vacías.' },
      { q: '¿Cómo verifican a los streamers?', a: 'Los streamers son seleccionados y verificados manualmente por engagement real, geo de audiencia y rendimiento pasado en iGaming. Solo trabajamos con creadores que ya han demostrado que pueden impulsar depósitos.' },
      { q: '¿Qué incluye la demo de $10,000?', a: 'Un piloto de 2 semanas con 5-10 streamers verificados, 10-15 horas de contenido en vivo y un informe completo de ROI. Obtienes prueba antes de escalar — sin compromiso a largo plazo.' },
      { q: '¿Qué mercados atienden?', a: 'Operamos en Europa, LATAM, América del Norte y Oceanía, cubriendo 25+ mercados y 15+ idiomas. Los streamers siempre se emparejan según geo, comportamiento de audiencia y ajuste de marca.' },
      { q: '¿Con qué plataformas trabajan?', a: 'Ejecutamos campañas en Twitch, YouTube, Kick y entornos de streaming nativos de plataforma. La ejecución multiplataforma garantiza alcance, frecuencia y mayor eficiencia de conversión.' },
      { q: '¿Cómo rastrean los resultados?', a: 'Cada campaña se rastrea de principio a fin con informes de rendimiento semanales. Ves gasto, FTDs, depósitos, retención y ROI — desglosados streamer por streamer.' },
      { q: '¿Cuál es su modelo de precios?', a: 'Ofrecemos pilotos demo fijos y retenciones mensuales escalables, según tu etapa de crecimiento. Sin tarifas ocultas, sin precios vagos — todo alineado con la entrega de rendimiento.' },
      { q: '¿Cómo empiezo?', a: 'Reserva una consulta gratuita de 30 minutos para revisar tus objetivos y estrategia de captación actual. Si hay ajuste, lanzamos una demo y probamos resultados antes de escalar.' },
      { q: '¿Cómo funciona el marketing de streamers de casino cripto?', a: 'Conectamos marcas de casino cripto con streamers verificados que tienen audiencias probadas en el espacio iGaming. Los streamers crean contenido en vivo auténtico mostrando tu plataforma, impulsando registros reales de jugadores, depósitos por primera vez y retención a largo plazo.' },
      { q: '¿Cuál es el ROI del marketing de influencers iGaming?', a: 'Nuestros clientes típicamente ven 3-5x de ROI en campañas de streamers iGaming, con costo por FTD significativamente menor que los canales de captación tradicionales. Proporcionamos transparencia completa con informes semanales.' },
      { q: '¿Cómo encuentran y verifican streamers de casino?', a: 'Cada streamer en nuestra red es verificado manualmente por autenticidad de audiencia, calidad de engagement, alcance geográfico y rendimiento de conversión pasado en iGaming.' },
      { q: '¿Trabajan con marcas de casino cripto?', a: 'Sí. Las marcas de casino cripto y Bitcoin casino son un enfoque central. Nos especializamos en conectar plataformas de juego cripto con streamers que tienen audiencias ya comprometidas con criptomonedas y gaming online.' },
      { q: '¿Qué mercados y geos cubren?', a: 'Cubrimos 25+ mercados en Dubái, Europa (UK, Alemania, Malta), América del Norte (Canadá, EE.UU.), Oceanía (Australia, Nueva Zelanda), Asia-Pacífico (Taiwán) y mercados emergentes de LATAM.' },
      { q: '¿Cuánto cuesta el marketing de streamers iGaming?', a: 'Ofrecemos un piloto demo de $10,000 para marcas que quieren probar nuestro enfoque sin compromiso a largo plazo. Las retenciones mensuales escalables comienzan desde ahí.' },
    ],
  },
  lang: {
    switcher: 'Idioma',
    en: 'English',
    ru: 'Русский',
    es: 'Español',
    uk: 'Українська',
    sv: 'Svenska',
    de: 'Deutsch',
    fr: 'Français',
  },
};

export default es;
