import type { Translations } from './en';

const fr: Translations = {
  meta: {
    home: {
      title: 'Meilleure Agence Marketing iGaming Influenceur 2026 | Octo Media',
      description: 'Agence iGaming influenceur de premier plan. Streamers vérifiés sur Twitch, YouTube & Kick. ROI prouvé pour les marques de crypto-casino. Appelez gratuitement.',
    },
    services: {
      title: 'Services Marketing iGaming | Octo Media 2026',
      description: 'Marketing expert pour influenceurs casino, campagnes streamers jeux et services affiliés iGaming. Acquisition de joueurs prouvée pour crypto-casino et paris sportifs.',
    },
    streamers: {
      title: 'Engager des Streamers Casino Twitch, YouTube & Kick | Octo Media',
      description: 'Rejoignez le premier réseau de streamers iGaming. Sponsorings de jeux constants, meilleurs tarifs et paiements rapides. Streamers casino Twitch, YouTube & Kick — postulez.',
    },
    whyUs: {
      title: 'Agence Marketing iGaming Expert — Fondée par des Initiés Casino',
      description: 'Octo Media Group : 8 vétérans iGaming avec résultats FTD prouvés, transparence ROI totale et responsabilité de performance.',
    },
    resources: {
      title: 'Ressources & Guides Marketing iGaming | Octo Media Group',
      description: 'Guides experts marketing influenceurs iGaming : conformité, benchmarks ROI, stratégie casino Twitch, tendances crypto-casino et plus encore.',
    },
    privacy: {
      title: 'Politique de Confidentialité | Octo Media Group',
      description: 'Politique de confidentialité d\'Octo Media Group. Découvrez comment nous collectons, utilisons et protégeons vos données personnelles.',
    },
    terms: {
      title: 'Conditions d\'Utilisation | Octo Media Group',
      description: 'Conditions d\'utilisation d\'Octo Media Group. Lisez les termes et conditions régissant votre utilisation de notre site web et services.',
    },
    cookies: {
      title: 'Politique de Cookies | Octo Media Group',
      description: 'Politique de cookies d\'Octo Media Group. Découvrez comment nous utilisons les cookies et technologies similaires sur notre site web.',
    },
  },
  nav: {
    home: 'Accueil',
    services: 'Services',
    ourStory: 'Notre Histoire',
    forStreamers: 'Pour les Streamers',
    faq: 'FAQ',
    contact: 'Contact',
    blog: 'Blog',
    caseStudies: 'Études de Cas',
    whyJoin: 'Pourquoi Rejoindre',
    howItWorks: 'Comment Ça Marche',
    apply: 'Postuler',
    ctaGrowthPlan: 'Obtenir un Plan de Croissance Gratuit',
    ctaApplyNow: 'Postuler Maintenant',
    ctaGetInTouch: 'Prendre Contact',
  },
  footer: {
    description: 'La première agence marketing influenceurs iGaming. Campagnes streamers casino orientées performance et marketing influenceurs jeux de hasard pour marques crypto-casino, casino en ligne et paris sportifs dans le monde entier.',
    quickLinks: 'Liens Rapides',
    ourServices: 'Nos Services',
    legal: 'Mentions Légales',
    contact: 'Contact',
    links: {
      agency: 'Agence Marketing iGaming',
      services: 'Services Marketing iGaming',
      whyOcto: 'Pourquoi Octo Media',
      hireStreamers: 'Engager des Streamers Casino',
      faq: 'FAQ',
      contact: 'Contact',
    },
    serviceLinks: {
      streamer: 'Marketing Streamers Casino',
      affiliate: 'Marketing Affiliés iGaming',
      influencer: 'Marketing Influenceurs Jeux',
    },
    legalLinks: {
      privacy: 'Politique de Confidentialité',
      terms: 'Conditions d\'Utilisation',
      cookies: 'Politique de Cookies',
    },
    telegram: '@OctoMediaGroup sur Telegram',
    bottomText1: 'Octo Media Group est une agence spécialisée en marketing influenceurs iGaming proposant le marketing streamers casino, le marketing influenceurs jeux de hasard et le marketing affiliés iGaming pour les marques crypto-casino, casino en ligne et paris sportifs. Nous gérons également un réseau dédié aux streamers casino Twitch, YouTube & Kick recherchant des sponsorings constants.',
    bottomText2: 'En utilisant ce site web, vous acceptez nos Conditions d\'Utilisation, notre Politique de Confidentialité et notre Politique de Cookies. L\'utilisation continue constitue une acceptation de ces politiques.',
    copyright: 'Tous droits réservés. Conforme au RGPD européen.',
  },
  hero: {
    headline1: 'Acquisition Joueurs iGaming',
    headline2: 'Optimisée pour un',
    headline3: 'Rendement LTV Élevé',
    subheadline: 'L\'agence dédiée au marketing streamers crypto-casino à laquelle font confiance les principales marques iGaming du monde entier. Marketing streamer et influenceur orienté performance pour l\'iGaming et les crypto-casinos.',
    stat1Value: '$10M+',
    stat1Label: 'Chiffre d\'Affaires Généré',
    stat2Value: 'Exécution',
    stat2Label: 'de Bout en Bout',
    stat3Value: 'Acquisition',
    stat3Label: 'et Rétention',
    ctaPrimary: 'Consultation Gratuite de 30 Min',
    ctaSecondary: 'Découvrir les Services',
    badge: 'Fondé par des Vétérans iGaming',
  },
  problem: {
    badge: 'Le Problème du Secteur',
    title: 'Le Problème du Marketing Influenceurs iGaming',
    titleHighlight: 'que Nous Résolvons',
    subtitle: 'Les marques iGaming gaspillent des millions en campagnes influenceurs qui livrent des métriques de vanité plutôt que de vrais joueurs. Voici à quoi ressemble le secteur sans nous :',
    items: [
      { stat: '70%', title: 'Budget Gaspillé', description: 'des budgets marketing influenceurs en iGaming sont dépensés sur des créateurs avec des audiences fausses ou non pertinentes' },
      { stat: '< 0,5%', title: 'Taux de Conversion', description: 'est le taux de conversion moyen des campagnes influenceurs génériques — à peine un filet de vrais joueurs déposants' },
      { stat: 'AUCUNE', title: 'Responsabilité', description: 'Aucune responsabilité sur la qualité et la quantité des résultats. Aucune prévisibilité. La plupart des agences offrent zéro suivi transparent ou garanties' },
    ],
    realityCheck: 'Vérification de Réalité',
    typicalMetrics: 'Métriques de Campagne Typiques',
    typicalSubtitle: 'Ce qui se passe quand vous travaillez avec des agences standard',
    spent: 'Dépensé en campagne',
    signUps: 'Inscriptions reçues',
    ftds: 'FTD convertis',
    costPerFtd: 'Coût par FTD',
    secondDepositors: 'Seconds déposants',
    noRetention: 'Aucune rétention',
  },
  solution: {
    badge: 'Notre Domaine d\'Excellence',
    title: 'Notre',
    titleHighlight: 'Expertise Marketing iGaming',
    subtitle: 'Couvrant Dubaï, l\'Europe, l\'Amérique latine, l\'Amérique du Nord, l\'Océanie et l\'Asie-Pacifique avec des streamers vérifiés. Nous gérons l\'acquisition et la rétention de joueurs pour les marques casino et crypto-casino.',
    services: [
      { title: 'Marketing Streamers', description: 'Sourcing de créateurs, exécution basée sur les KPI, couverture multi-plateforme sur Twitch, YouTube et Kick pour l\'acquisition et la rétention de joueurs', tag1: 'Acquisition', tag2: 'Rétention', link: 'En Savoir Plus' },
      { title: 'Marketing Affiliés', description: 'Créatifs ciblés par marché, développement de communauté et partenariats affiliés basés sur la performance pour l\'acquisition et la rétention de joueurs', tag1: 'Acquisition', tag2: 'Rétention', link: 'En Savoir Plus' },
      { title: 'Marketing Influenceurs', description: 'Partenariats stratégiques avec des influenceurs à fort impact pour la notoriété de marque, l\'acquisition de joueurs et l\'engagement continu via du contenu authentique', tag1: 'Acquisition', tag2: 'Rétention', link: 'En Savoir Plus' },
    ],
  },
  howWeSolve: {
    badge: 'Notre Processus',
    title: 'Comment Notre Marketing Streamers iGaming',
    titleHighlight: 'Fonctionne',
    subtitle: 'Un système rigoureux en cinq étapes qui transforme les dépenses influenceurs en revenus mesurables et évolutifs',
    fiveStep: 'système en cinq étapes',
    scalable: 'revenus mesurables et évolutifs',
    cta: 'Voir en Action',
    steps: [
      { title: 'Uniquement des Streamers Triés sur le Volet', description: 'Nous invitons et intégrons les streamers manuellement — uniquement depuis des niches iGaming avec des résultats antérieurs vérifiés, de vraies audiences et des performances de dépôt prouvées.', highlight: 'Vérifiés Manuellement' },
      { title: 'Vérification Rigoureuse & Correspondance de Marque', description: 'Chaque streamer est audité pour l\'authenticité de l\'engagement, les données démographiques de l\'audience et les performances historiques, puis mis en relation uniquement avec les types de marques pour lesquelles ils convertissent déjà.', highlight: '100% Authentique' },
      { title: 'Campagnes Live Contrôlées à Haute Intention', description: 'Les streamers passent en direct avec un gameplay structuré, une présentation conforme à la marque et une promotion authentique — conçue pour attirer de vrais joueurs à haute intention, pas des vues de vanité.', highlight: 'Haute Intention Uniquement' },
      { title: 'Transparence ROI Totale', description: 'Rapports de performance hebdomadaires détaillés décomposant chaque euro dépensé — coûts streamers, FTD, dépôts, rétention et ROI — clairs et responsables.', highlight: 'Rapports Hebdomadaires' },
      { title: 'Scaler Ce qui Marche, Retenir Ce qui Convertit', description: 'Nous doublons sur les streamers gagnants et activons les mécaniques de rétention — classements, bonus et incitations communautaires — pour générer des dépôts répétés et un LTV plus élevé.', highlight: 'Scaling Prouvé' },
    ],
  },
  comparison: {
    badge: 'La Différence',
    title: 'Pourquoi les Marques iGaming Nous Choisissent plutôt que les',
    titleHighlight: 'Agences Marketing Standard',
    subtitle: 'Des métriques mesurables qui prouvent une approche fondamentalement différente du marketing iGaming',
    standardAgency: 'Agence Standard',
    metrics: [
      { label: 'Rétention' },
      { label: 'Taux de Conversion' },
      { label: 'Délai avant Premiers Résultats' },
      { label: 'Transparence & Efficacité des Dépenses' },
    ],
    features: [
      { category: 'Vérification des Streamers', standard: 'Non vérifiés, audiences mixtes', octo: 'Audiences vérifiées 100% sans bots' },
      { category: 'Support Campagne', standard: 'Rapports PDF mensuels', octo: 'Rapports de performance hebdomadaires détaillés + manager dédié' },
      { category: 'Couverture Marchés', standard: '1-2 régions', octo: '25+ marchés, 15+ langues' },
      { category: 'Stratégie de Rétention', standard: 'Non inclus', octo: 'Programmes complets de rétention et communauté' },
      { category: 'Couverture Plateformes', standard: 'Focus plateforme unique', octo: 'Twitch, YouTube, Kick & plus' },
    ],
    highlights: ['Meilleur Contrôle', 'Excellente Exécution', 'Résultats Exceptionnels'],
  },
  pricing: {
    title: 'Forfaits',
    titleHighlight: 'Campagne',
    subtitle: 'D\'une démo sans risque à la domination totale du marché. Choisissez le niveau qui correspond à vos objectifs.',
    mostPopular: 'Le Plus Populaire',
    footerNote: 'Tous les forfaits incluent un suivi de performance complet, un support dédié et des rapports transparents.',
    tiers: [
      { name: 'Campagne Démo', price: '10 000$', period: 'unique', tagline: 'Preuve avant engagement', cta: 'Démarrer la Démo', features: ['5-10 streamers vérifiés', '10-15 heures de contenu live', 'Suivi de performance complet', 'Rapport ROI détaillé', 'Recommandation de scaling'] },
      { name: 'Starter', price: '25-50K$', period: '/mois', tagline: 'Pour les marques en croissance entrant sur de nouveaux marchés', cta: 'Obtenir un Devis', features: ['15-20 grands streamers', '30-50 heures de contenu/mois', 'Rapports de performance hebdomadaires', 'Optimisation de campagne', 'Account manager dédié'] },
      { name: 'Croissance', price: '50-75K$', period: '/mois', tagline: 'Pour les marques prêtes à scaler agressivement', cta: 'Obtenir un Devis', features: ['50+ micro & macro streamers', '100+ heures de contenu/mois', 'Dashboard de performance en temps réel', 'Couverture multi-plateforme', 'Support prioritaire & conseil stratégique', 'Partenariat site SEO haute conversion'] },
      { name: 'Enterprise', price: '100K$+', period: '/mois', tagline: 'Pour les grands opérateurs dominant les marchés', cta: 'Nous Contacter', features: ['100+ streamers vérifiés', 'Contenu live illimité', 'Partenariats streamers exclusifs', 'Options white-label', 'Équipe de spécialistes dédiée', 'Reporting & analytics personnalisés', '5x partenariats sites SEO'] },
    ],
  },
  socialProof: {
    badge: 'Confiance Mondiale',
    title: 'Approuvé par les Principales',
    titleHighlight: 'Marques',
    titleEnd: 'iGaming',
    subtitle: 'Les leaders du secteur s\'appuient sur notre réseau pour l\'acquisition, la rétention et la croissance',
    stats: [
      { value: '15+', label: 'Partenaires Marques' },
      { value: '2,5M$', label: 'Budget Investi' },
      { value: '20+', label: 'Marchés Couverts' },
      { value: '98%', label: 'Fidélisation Clients' },
    ],
    testimonials: [
      { quote: 'La stratégie streamer d\'Octo Media nous a aidés à nous développer rapidement sur des marchés clés. Leur exécution et transparence sont de premier ordre.', detail: 'Nous avons constaté une amélioration immédiate de l\'engagement des audiences et des taux de conversion sur tous les canaux de streaming dès le premier mois.', role: 'Brand Manager', company: 'BC.GAME' },
      { quote: 'Travailler avec Octo Media a transformé notre pipeline d\'acquisition de joueurs. Leur compréhension approfondie de l\'audience iGaming a livré des résultats mesurables dès le premier jour.', detail: 'Leur approche ciblée de la sélection de streamers et de la stratégie de contenu a généré des leads de meilleure qualité et une meilleure valeur joueur à long terme.', role: 'Responsable Marketing', company: 'BET365' },
      { quote: 'La qualité des streamers et du contenu qu\'Octo Media source est inégalée. Notre visibilité de marque sur des marchés concurrentiels a considérablement augmenté en quelques semaines.', detail: 'Dès le premier jour, nous avions accès à des audiences authentiques et engagées qui se connectaient vraiment à notre message et nos valeurs de marque.', role: 'Directeur Partenariats', company: 'LEON' },
      { quote: 'Octo Media a apporté une approche data-driven à nos campagnes influenceurs que nous n\'avions pas vue auparavant. Les métriques de rétention se sont améliorées sur chaque canal qu\'ils géraient.', detail: 'Leurs insights stratégiques et leur optimisation continue ont maintenu nos campagnes à une efficacité maximale tout au long de l\'année.', role: 'Responsable Croissance', company: 'MELBET' },
      { quote: 'S\'associer à Octo Media nous a donné accès à un réseau curé de streamers à fort impact. La performance des campagnes a constamment dépassé nos benchmarks.', detail: 'Nous avons atteint un niveau de cohérence de performance de campagne qui nous a donné confiance pour augmenter le budget et nous étendre sur de nouveaux marchés.', role: 'Responsable Acquisition', company: 'STAKE' },
      { quote: 'L\'intégration transparente et le professionnalisme qu\'Octo Media a apportés à nos campagnes les distinguent. Leur focus sur la rétention des joueurs a livré un ROI exceptionnel.', detail: 'Contrairement aux autres agences, ils se soucient vraiment du succès du partenariat à long terme et de la valeur vie des joueurs, pas seulement des gains rapides.', role: 'Responsable Croissance', company: 'TRUSTDICE' },
    ],
  },
  markets: {
    items: [
      { title: 'Casinos en Ligne', description: 'Casinos traditionnels, crypto-casinos, casinos Bitcoin, casinos en direct' },
      { title: 'Paris Sportifs', description: 'Paris football, paris esports, plateformes multi-sports' },
      { title: 'Jeux de Hasard Gaming', description: 'CS2 gambling, Rust gambling, paris adjacents aux jeux' },
      { title: 'Salles de Poker', description: 'Poker en ligne, tournois' },
    ],
  },
  contact: {
    title: 'Prendre',
    titleHighlight: 'Contact',
    subtitle: 'Prêt à transformer votre budget marketing en vrais joueurs déposants ? Envoyez-nous un message ou réservez une consultation gratuite.',
    formTitle: 'Envoyer un Message',
    namePlaceholder: 'Votre Nom',
    emailPlaceholder: 'Adresse E-mail',
    messagePlaceholder: 'Votre Message',
    sendButton: 'Envoyer le Message',
    businessEmail: 'E-mail Professionnel',
    businessEmailDesc: 'Pour les partenariats et demandes professionnelles',
    telegramSupport: 'Support Telegram',
    telegramDesc: 'Réponses rapides et support en temps réel',
    bookTitle: 'Réserver une Consultation Gratuite',
    bookDesc: 'Planifiez un appel de 30 minutes pour discuter de votre stratégie de marketing influenceurs.',
    discussLabel: 'Ce que nous allons discuter',
    scheduleButton: 'Planifier Votre Appel',
    topics: [
      'Votre stratégie actuelle d\'acquisition de joueurs',
      'Comment le marketing influenceurs vérifié s\'adapte à vos objectifs',
      'ROI attendu de la campagne démo',
      'Proposition de campagne personnalisée pour votre marque',
    ],
    responseTime: 'Temps de Réponse',
    responseTimeValue: 'Répond généralement en 15-30 minutes',
    availability: 'Disponibilité',
    availabilityValue: 'Actif : 7 jours sur 7',
    supportType: 'Type de Support',
    supportTypeValue: 'Demandes streamers, planification campagnes, partenariats',
  },
  finalCta: {
    badge: 'Disponibilité Limitée',
    title1: 'Vos Concurrents Scalent Déjà',
    title2: 'Avec Nous',
    subtitle: 'Chaque jour que vous attendez est un autre jour de dépenses publicitaires gaspillées sur des influenceurs non vérifiés avec de faux abonnés.',
    body: 'Nous n\'acceptons qu\'un nombre limité de marques par trimestre pour garantir une exécution de qualité. Assurez votre place avant vos concurrents.',
    cta: 'Obtenir Votre Plan de Croissance Gratuit',
    guarantees: ['Pas de contrats long terme', 'Suivi 100% transparent', 'Résultats en 2 semaines', 'Account manager dédié'],
  },
  demo: {
    badge: 'Zéro Risque',
    title1: 'Pas Encore Convaincu ?',
    title2: 'Voyez-Nous en Action',
    subtitle: 'Donnez-nous 10 000$ et deux semaines. Si nous ne livrons pas de résultats mesurables, vous le saurez avant de vous engager sur un budget plus important.',
    steps: [
      { title: 'Investissement de 10 000$', description: 'Coût fixe, sans frais cachés. Vous savez exactement ce que vous payez.' },
      { title: 'Campagne de 2 Semaines', description: '5-10 streamers vérifiés passent en direct pour promouvoir votre marque.' },
      { title: 'Résultats Mesurables', description: 'Rapport de performance complet avec données ROI et plan de scaling.' },
    ],
    whatsIncluded: 'Ce qui est Inclus',
    includes: [
      'Streamers vérifiés triés sur le volet correspondant à votre marque',
      '10-15 heures de contenu streamer live',
      'Accès au dashboard de suivi en temps réel',
      'Rapport ROI & performance détaillé',
      'Recommandation de scaling sans obligation',
    ],
    noContract: 'Aucun contrat long terme requis. Les résultats parlent d\'eux-mêmes.',
    pilotLabel: 'Campagne pilote de 2 semaines',
    cta: 'Planifier Votre Appel Démo',
  },
  streamersSection: {
    badge: 'Pour les Streamers',
    title: 'Développez Votre',
    titleHighlight: 'Carrière de Streaming',
    subtitle: 'Rejoignez notre réseau de 750+ streamers vérifiés et soyez mis en relation avec les meilleures marques iGaming. Nous gérons le côté commercial pour que vous puissiez vous concentrer sur la création de contenu.',
    benefits: [
      'Accès aux meilleures marques iGaming premium',
      'Taux de commission compétitifs',
      'Paiements fiables et ponctuels',
      'Manager partenariat dédié',
      'Bonus de performance et offres exclusives',
      'Support multi-plateforme (Twitch, YouTube, Kick)',
    ],
    cta: 'Postuler Maintenant',
    verifiedStreamers: 'Streamers Vérifiés',
    avgEarnings: 'Revenus mensuels moyens',
    avgEarningsValue: '2 000$ - 15 000$',
    platforms: 'Plateformes supportées',
    platformsValue: 'Twitch, YT, Kick',
    paymentSchedule: 'Calendrier de paiement',
    paymentScheduleValue: 'Bihebdomadaire',
    markets: 'Marchés disponibles',
    marketsValue: '25+ pays',
  },
  streamersPage: {
    hero: {
      badge: 'Pour les Streamers & Créateurs',
      title1: 'Arrêtez de Chasser les Deals.',
      title2: 'Commencez à Être',
      titleHighlight: 'Payé',
      subtitle: 'Le réseau de streamers iGaming qui connecte les créateurs vérifiés avec les meilleures marques casino et crypto pour des sponsorings continus.',
      subtitleSmall: 'Meilleurs tarifs. Paiements plus rapides. Zéro tracas.',
      cta: 'Postuler Maintenant',
    },
    benefits: {
      badge: 'Écosystème de Partenariat Complet',
      title: 'Pourquoi',
      titleHighlight: 'Travailler Avec Nous',
      subtitle: 'Plus que de simples deals de marque. Un écosystème complet conçu pour maximiser votre potentiel de revenus et protéger vos intérêts à chaque étape.',
      commissionNote: '10% de commission sur les deals que nous concluons pour vous',
      commissionSub: 'Facturé uniquement après réception de votre paiement. Zéro risque, transparence maximale.',
      items: [
        { title: 'Manager Personnel 24h/24', desc: 'Votre account manager dédié est disponible en permanence pour gérer toutes vos questions, négociations et coordination de campagnes.' },
        { title: 'Aucune Exclusivité Requise', desc: 'Vous avez trouvé un meilleur deal vous-même ? Allez-y ! Nous offrons des consultations gratuites pour que vous connaissiez votre vraie valeur sur le marché.' },
        { title: 'Zéro Frais Initiaux', desc: 'Pas de frais d\'abonnement ni de frais cachés. Nous prenons un forfait de 10% uniquement après réception de votre paiement de campagne. Simple et transparent.' },
        { title: 'Marques Vérifiées Uniquement', desc: 'Plus de fraudes ou de paiements retardés. Travailler aujourd\'hui, être payé aujourd\'hui. Directement sur votre compte bancaire ou portefeuille crypto.' },
        { title: 'Structures de Deals Flexibles', desc: 'Vous préférez le solde brut, les frais fixes ou le partage de revenus à vie ? Nous adaptons les deals selon vos préférences et votre style de contenu.' },
        { title: 'Pas de Contrats Long Terme', desc: 'Vous faites une pause ou rencontrez des problèmes ? Partez à tout moment. Aucune pénalité, aucune question. Nous avons votre dos.' },
        { title: 'Support Construction de Marque', desc: 'Au-delà des deals, nous vous aidons à construire votre marque personnelle avec la création de site web, la stratégie réseaux sociaux et des conseils de contenu professionnel.' },
        { title: 'Accès Événements Exclusifs', desc: 'Invitation à des rassemblements offline dans le monde entier. Nous vous volons avec tous les frais pris en charge. Réseautez avec les meilleurs streamers et leaders du secteur.' },
        { title: 'Innovation Continue', desc: 'Notre plateforme évolue avec de nouvelles fonctionnalités, outils et opportunités. Rejoignez-nous pour façonner l\'avenir de la monétisation des créateurs.' },
      ],
    },
    howItWorks: {
      title: 'Comment Ça',
      titleHighlight: 'Marche',
      subtitle: 'De la candidature au paiement en quatre étapes simples',
      step: 'ÉTAPE',
      steps: [
        { title: 'Postuler', desc: 'Remplissez une courte candidature avec les infos de votre chaîne, plateforme et taille d\'audience.' },
        { title: 'Être Vérifié', desc: 'Notre équipe examine la qualité de votre contenu, l\'authenticité de l\'audience et les métriques d\'engagement.' },
        { title: 'Être Mis en Relation', desc: 'Nous vous associons aux marques iGaming et crypto-casino qui correspondent à votre niche, audience et style de contenu pour des résultats maximaux.' },
        { title: 'Créer & Être Payé', desc: 'Streamez du contenu iGaming sponsorisé et recevez des paiements rapides et fiables directement sur votre compte.' },
      ],
    },
    faq: {
      title: 'Questions',
      titleHighlight: 'Fréquentes',
      subtitle: 'Questions courantes des streamers rejoignant notre réseau',
      items: [
        { q: 'Combien puis-je gagner ?', a: 'Les revenus varient selon la taille de votre audience, l\'engagement et la qualité du contenu. Nos streamers gagnent généralement entre 500$ et 15 000$+ par mois grâce aux deals de marque via notre réseau.' },
        { q: 'Quelles plateformes supportez-vous ?', a: 'Nous travaillons avec des streamers sur Twitch, YouTube, Kick et d\'autres grandes plateformes de streaming. Si vous avez une audience active sur une plateforme de streaming, nous voulons avoir de vos nouvelles.' },
        { q: 'Et si j\'ai moins de 5 000 abonnés ?', a: 'Nous travaillons occasionnellement avec de petits créateurs qui ont des taux d\'engagement exceptionnels. Postulez quand même et notre équipe examinera votre profil. La qualité de l\'audience importe plus que les chiffres bruts.' },
        { q: 'Quel type de contenu devrai-je créer ?', a: 'Des streams sponsorisés présentant des marques iGaming et crypto-casino. Le format spécifique et les exigences varient selon la marque, mais nous travaillons toujours avec vous pour que le contenu soit naturel et authentique.' },
        { q: 'Quelle est la durée des contrats ?', a: 'La plupart des deals sont mensuels sans engagement long terme. Certains partenariats premium peuvent durer 3-6 mois, mais vous connaîtrez toujours les termes à l\'avance avant de vous engager.' },
        { q: 'Prenez-vous une commission ?', a: 'Nous sommes payés par les marques, pas par vous. Le tarif que nous négocions pour vous est ce que vous recevez. Il n\'y a pas de frais cachés ni de déductions de vos revenus.' },
        { q: 'Puis-je travailler avec d\'autres agences simultanément ?', a: 'Oui. Nous n\'avons aucune exigence d\'exclusivité. Vous êtes libre de travailler avec d\'autres agences et de prendre des deals directs. Nous demandons seulement que vous honoriez les engagements de campagnes actives.' },
        { q: 'Combien de temps dure le processus de candidature ?', a: 'Généralement 2-5 jours ouvrés. Nous examinons votre chaîne, vérifions vos métriques d\'audience, et si vous êtes approuvé, vous pourriez recevoir votre premier deal de marque dans la semaine.' },
      ],
    },
    form: {
      title: 'Postuler',
      titleHighlight: 'Maintenant',
      subtitle: 'Remplissez le formulaire ci-dessous et notre équipe examinera votre candidature',
      fullName: 'Nom Complet *',
      emailAddress: 'Adresse E-mail *',
      primaryPlatform: 'Plateforme Principale *',
      followerCount: 'Nombre d\'Abonnés *',
      profileUrl: 'URL Profil / Chaîne *',
      telegramHandle: 'Pseudo Telegram (optionnel)',
      describeContent: 'Décrivez Votre Contenu *',
      selectPlatform: 'Sélectionner la plateforme',
      selectRange: 'Sélectionner la fourchette',
      namePlaceholder: 'Votre nom',
      contentPlaceholder: 'Parlez-nous de votre contenu, de votre audience et des types de deals de marque qui vous intéressent...',
      submitButton: 'Soumettre la Candidature',
      successTitle: 'Candidature Envoyée',
      successBody: 'Votre client e-mail a été ouvert avec les détails de votre candidature. Envoyez l\'e-mail pour finaliser votre soumission. Nous examinerons votre profil et vous répondrons dans les 2-5 jours ouvrés.',
      submitAnother: 'Soumettre une Autre Candidature',
    },
    whyJoin: {
      title: 'Pourquoi Rejoindre Notre',
      titleHighlight: 'Réseau',
      subtitle: 'Nous l\'avons créé pour les créateurs fatigués des deals peu fiables et des offres dérisoires',
      items: [
        { title: 'Deals Réguliers', desc: 'Des sponsorings iGaming récurrents mensuels pour que vous ayez toujours des deals de marque casino. Plus de chasse aux campagnes ponctuelles.' },
        { title: 'Meilleurs Tarifs', desc: 'Nous négocions des tarifs premium en votre nom grâce à notre effet de réseau. Gagnez plus par heure de contenu qu\'en solo.' },
        { title: 'On Gère les Affaires', desc: 'Contrats, facturation, négociations, conformité. Nous gérons la paperasse pour que vous puissiez vous concentrer sur le streaming.' },
        { title: 'Paiements Rapides', desc: 'Soyez payé en 7-14 jours. Sans courir après les marques pendant des mois. Nous garantissons des paiements ponctuels et fiables.' },
        { title: 'Marques Gaming-Friendly', desc: 'Travaillez avec des marques réputées de iGaming et casino crypto, des plateformes de paris et des entreprises de jeux qui correspondent à votre audience.' },
        { title: 'Sans Engagement', desc: 'Travaillez avec nous selon vos conditions. Pas de contrats d\'exclusivité. Vous êtes libre de collaborer avec d\'autres agences et marques.' },
      ],
    },
    whatYouGet: {
      badge: 'Fonctionnalités Clés',
      title: 'L\'',
      titleHighlight: 'Avantage Octo',
      subtitle: 'Tout ce dont vous avez besoin pour monétiser votre contenu professionnellement et développer votre activité de créateur',
      items: [
        { title: 'Partenariats Récurrents', desc: 'Des accords de marque à long terme qui fournissent des revenus stables et prévisibles mois après mois.' },
        { title: 'Tarifs Premium', desc: 'Notre volume et notre réputation nous permettent de négocier des CPM et des tarifs fixes plus élevés que vous ne pourriez obtenir seul.' },
        { title: 'Service Complet', desc: 'Manager de partenariat dédié, gestion des contrats, briefs créatifs et support conformité.' },
        { title: 'Paiements Rapides', desc: 'Cycles de paiement de 7-14 jours. Sans attendre 60-90 jours. Nous payons à temps, à chaque fois.' },
        { title: 'Matching Ciblé de Marques', desc: 'Soyez mis en relation avec des marques iGaming et casino crypto qui résonnent avec votre audience spécifique.' },
        { title: 'Flexibilité', desc: 'Pas d\'exclusivité. Travaillez avec plusieurs marques et agences. Montez ou descendez en gamme selon vos conditions.' },
      ],
    },
    eligibility: {
      title: 'Conditions',
      titleHighlight: 'd\'Éligibilité',
      subtitle: 'Assurez-vous de remplir les conditions de base avant de postuler',
      items: [
        { title: '5 000+ Abonnés', desc: 'Nombre minimum d\'abonnés sur votre plateforme de streaming principale.' },
        { title: 'Contenu Gaming / Gambling', desc: 'Votre contenu doit être lié au gaming ou au gambling pour correspondre à nos partenaires de marque.' },
        { title: 'Présence sur Plateforme Principale', desc: 'Actif sur Twitch, YouTube, Kick ou d\'autres grandes plateformes de streaming.' },
        { title: 'Engagement Authentique', desc: 'Vrais spectateurs et interactions genuines. Nous vérifions la qualité de l\'engagement, pas seulement les chiffres.' },
        { title: 'Disponibilité Mondiale', desc: 'Nous travaillons avec des streamers du monde entier. Toutes les régions et langues sont bienvenues.' },
        { title: 'Planning Régulier', desc: 'Planning de streaming régulier avec production de contenu fiable et fidélisation de l\'audience.' },
      ],
    },
    comparison: {
      badge: 'Le Choix Évident',
      title: 'Agences Traditionnelles vs',
      titleHighlight: 'Octo Media',
      subtitle: 'Découvrez pourquoi des milliers de streamers quittent les agences traditionnelles pour notre plateforme créateur-first',
      traditionalLabel: 'Traditionnel',
      traditionalAgency: 'Agence Traditionnelle',
      octoMedia: 'Octo Media',
      metrics: [
        { label: 'Taux de Commission', traditional: '20-40%', us: '10%' },
        { label: 'Délai de Paiement', traditional: '60-90 jours', us: 'Même jour' },
        { label: 'Durée du Contrat', traditional: '12-24 mois', us: 'Sans engagement' },
        { label: 'Valeur Moyenne du Deal', traditional: '$2-5K/mois', us: '$8-15K/mois' },
      ],
      features: [
        { category: 'Exclusivité', traditional: 'Requise - Impossible de travailler avec d\'autres agences', us: 'Optionnelle - Travaillez librement avec plusieurs partenaires' },
        { category: 'Frais Initiaux', traditional: 'Frais de configuration, abonnements mensuels', us: 'Zéro frais initiaux ou cachés' },
        { category: 'Vérification des Marques', traditional: 'Screening minimal, retards de paiement fréquents', us: '100% marques vérifiées, paiements garantis' },
        { category: 'Support Personnel', traditional: 'Manager partagé pour 50+ créateurs', us: 'Manager personnel dédié 24h/24' },
        { category: 'Flexibilité des Deals', traditional: 'Packages standard uniquement', us: 'Deals personnalisés selon vos préférences' },
        { category: 'Sortie du Contrat', traditional: 'Pénalités et préavis', us: 'Partez quand vous voulez, sans pénalités' },
        { category: 'Support Carrière', traditional: 'Limité au courtage de deals', us: 'Support complet construction de marque et croissance' },
      ],
      highlights: ['Commission Réduite', 'Paiements Plus Rapides', 'Gains Plus Élevés'],
    },
  },
  whyUsPage: {
    hero: {
      badge: 'POURQUOI OCTOMEDIA',
      title: 'Fondé par des Initiés Casino,\nPas des Outsiders Marketing',
      subtitle: 'OctoMedia a été fondé par huit vétérans iGaming qui ont passé des années à l\'intérieur de vrais casinos et de plateformes crypto-casino — gérant les acquisitions, la rétention, les lancements et la conformité. La seule agence marketing iGaming qui combine le focus spécifique aux streamers, la spécialisation crypto-casino et une équipe fondatrice d\'ex-opérateurs. Nous comprenons les FTD, le LTV et la rétention parce que nous avons été mesurés sur eux.',
      point1: 'Professionnels Ex-Casino & Crypto-Casino',
      point2: 'Spécialistes Marketing Streamers iGaming',
      point3: 'Scaling Conforme aux Réglementations',
    },
    differentiators: {
      title: 'Ce Qui Nous Différencie',
      subtitle: 'OctoMedia n\'est pas juste une autre agence marketing. Nous sommes construits différemment parce que nous venons de l\'intérieur du secteur.',
      items: [
        { title: 'Mentalité d\'Opérateur', description: 'Nous pensons comme des opérateurs casino parce que nous étions des opérateurs casino. Chaque décision est filtrée par des KPI du monde réel et des contraintes opérationnelles.' },
        { title: 'Focus FTD, LTV & Rétention', description: 'Nous optimisons pour les métriques qui comptent : premiers dépôts, valeur vie, taux de seconds dépôts et rétention à long terme des joueurs.' },
        { title: 'Marketing Influenceurs Data-Driven', description: 'Zéro métriques de vanité. Nous suivons les taux de conversion, coût par FTD et qualité d\'audience pour chaque streamer et créateur de contenu.' },
        { title: 'Scaling Conforme aux Réglementations', description: 'Stratégies de croissance construites avec une conscience réglementaire. Nous savons quels marchés nécessitent des messages prudents et quels influenceurs présentent des risques de conformité.' },
        { title: 'Accès Réseau Sectoriel', description: 'Relations directes avec les streamers de premier plan, réseaux affiliés et acheteurs médias qui comprennent vraiment l\'iGaming et les crypto-casinos.' },
        { title: 'Valeur de Marque Long Terme', description: 'Nous équilibrons une acquisition agressive avec une construction de marque durable. Des gains à court terme sans dommages à long terme.' },
      ],
    },
    foundingStory: {
      title: 'Comment Nous Avons Commencé',
      body1: 'Nous nous sommes rencontrés dans différents rôles casino — responsables d\'acquisition, leads rétention, managers affiliés, stratèges conformité. Certains d\'entre nous ont lancé des crypto-casinos de zéro. D\'autres ont fait évoluer des marques établies sur plusieurs GEO.',
      body2: 'La frustration commune ? Des agences marketing qui ne comprenaient pas vraiment l\'iGaming.',
      body3: 'Elles vendaient la "notoriété" et "l\'engagement" alors que nous étions mesurés sur les premiers dépôts, les taux de seconds dépôts et la valeur vie. Elles ne parlaient pas le langage des deals CPA, de la protection contre les abus de bonus ou du risque réglementaire.',
      body4: 'Alors nous avons créé OctoMedia — une agence dirigée par des gens qui ont déjà été du côté opérateur. Nous savons ce qui fonctionne parce que nous avons déployé des budgets, géré des campagnes influenceurs et optimisé des funnels sous vraie pression.',
      closing: 'Nous ne devinons pas. Nous l\'avons déjà fait.',
      cards: [
        { heading: 'D\'où Nous Venons', text: 'Nous nous sommes rencontrés dans différents rôles casino — responsables d\'acquisition, leads rétention, managers affiliés, stratèges conformité. Certains ont lancé des crypto-casinos de zéro.' },
        { heading: 'La Frustration', text: 'Des agences marketing qui ne comprenaient pas vraiment l\'iGaming. Elles vendaient la "notoriété" et "l\'engagement" alors que nous étions mesurés sur les premiers dépôts et la valeur vie.' },
        { heading: 'Le Gap Que Nous Avons Vu', text: 'Elles ne parlaient pas le langage des deals CPA, de la protection contre les abus de bonus ou du risque réglementaire. Personne ne comblait l\'écart entre le marketing influenceurs et les KPI réels des opérateurs.' },
        { heading: 'Pourquoi Nous Avons Créé OctoMedia', text: 'Une agence dirigée par des gens qui ont déjà été du côté opérateur. Nous savons ce qui fonctionne parce que nous avons déployé des budgets et optimisé des funnels sous vraie pression.' },
      ],
    },
    foundingTeam: {
      title: 'Rencontrer l\'Équipe Fondatrice',
      subtitle: 'Huit vétérans casino qui ont construit leur carrière à l\'intérieur du secteur, pas en dehors.',
      yearsLabel: 'Ans',
      exLabel: 'Ex :',
      strengthLabel: 'Force :',
    },
    closing: {
      badge: 'LA DIFFÉRENCE EST CLAIRE',
      title: 'Nous Avons Déjà Été\nÀ l\'Intérieur de l\'iGaming',
      subtitle: 'OctoMedia a été fondé par des gens qui ont géré les acquisitions casino et crypto-casino, piloté des campagnes influenceurs iGaming à plusieurs millions, et optimisé des funnels de rétention sous vraie pression. Nous ne comprenons pas seulement le marketing streamers iGaming — nous l\'avons vécu.',
      cta1: 'Explorer les Partenariats Streamers',
      cta2: 'Prendre Contact',
      stat1Value: '8',
      stat1Label: 'Vétérans Fondateurs',
      stat2Value: '62',
      stat2Label: 'Années d\'Expérience Cumulées',
      stat3Value: '100%',
      stat3Label: 'Ex-Professionnels Casino',
    },
  },
  servicesPage: {
    badge: 'NOS SERVICES',
    heroBadge: 'Services Marketing iGaming',
    heroTitle: 'Marketing Performance Conçu pour les',
    heroTitleHighlight: 'Opérateurs iGaming',
    heroSubtitle: 'Trois canaux d\'acquisition éprouvés — campagnes streamers, programmes affiliés et marketing influenceurs — gérés de bout en bout par des ex-opérateurs casino.',
    tab1: 'Marketing Streamers',
    tab2: 'Marketing Affiliés',
    tab3: 'Marketing Influenceurs',
    howItWorksLabel: 'Comment Ça Marche',
    whatYouGetLabel: 'Ce que Vous Obtenez',
    inlineCta1: 'Vous voulez voir les résultats streamers avant de vous engager sur un budget complet ?',
    inlineCta2: 'Prêt à construire un programme affiliés conforme et à haute conversion ?',
    inlineCtaNote: 'Aucun engagement à long terme requis. Voyez les résultats avant de scaler.',
    inlineCtaBtn: 'Réserver un Appel Stratégie Gratuit',
    closingBadge: 'Zéro Engagement Long Terme',
    trustSignals: ['Pas de contrats long terme', '100% transparence des dépenses', 'Résultats en 2 semaines', 'Account manager dédié'],
    stats: [
      { value: '25+', label: 'Marchés Couverts' },
      { value: '750+', label: 'Streamers Vérifiés' },
      { value: '3–5x', label: 'ROI Moyen' },
      { value: '2 Semaines', label: 'Premiers Résultats' },
    ],
    streamerSection: {
      badge: 'Marketing Streamers Casino',
      title: 'Streamers Vérifiés.',
      titleHighlight: 'Dépôts Prouvés.',
      subtitle: 'Twitch · YouTube · Kick — 25+ Marchés',
      positioning: 'Chaque streamer de notre réseau est sélectionné manuellement dans les niches iGaming, audité pour son vrai engagement d\'audience et associé uniquement aux marques pour lesquelles il convertit déjà. Nous assurons l\'exécution end-to-end — du briefing conformité aux rapports ROI hebdomadaires.',
      accordion1Label: 'Ce qui est inclus dans une Campagne Streamer',
      accordion1Items: [
        'Streamers casino vérifiés sur Twitch, YouTube et Kick',
        'Campagnes influenceurs casino conformes aux standards jeu responsable',
        'Exécution basée sur les KPI : FTD, dépôts, rétention joueurs & coût par acquisition',
        'Rapports ROI hebdomadaires par streamer — transparence totale dépenses vs résultats',
        'Expertise marques crypto-casino, casino en ligne & paris sportifs',
        'Couverture sur 25+ marchés — Europe, LATAM, Amérique du Nord, Océanie & APAC',
      ],
      accordion2Label: 'Plateformes & Conformité',
      accordion2Items: [
        'Campagnes live streaming sur Twitch, YouTube Live & Kick simultanément',
        'Sélection streamers géo-ciblée pour vos marchés sous licence',
        'Disclaimers jeu responsable intégrés dans chaque brief de campagne',
        'Filtres de vérification d\'âge audience appliqués avant le lancement',
        'Contenu vérifié contre les standards réglementaires UK, MGA, Curaçao & locaux',
      ],
      steps: [
        { num: '01', title: 'Briefing & Brand Match', desc: 'Nous analysons vos GEOs cibles, profil joueur et exigences conformité pour construire un brief créateur précis.' },
        { num: '02', title: 'Sourcing Streamers', desc: 'Sélectionnés à la main dans notre réseau vérifié — matchés par niche, géographie d\'audience et historique conversion dépôts.' },
        { num: '03', title: 'Exécution Campagne Live', desc: 'Les streamers passent en live avec gameplay structuré, contenu brand-safe et promotion authentique vers des joueurs à haute intention.' },
        { num: '04', title: 'Tracking Temps Réel', desc: 'Accès dashboard + rapports hebdomadaires : FTD, dépôts, coût par joueur, rétention et décomposition ROI complète.' },
        { num: '05', title: 'Scaler & Retenir', desc: 'Doubler sur les top performers, activer les mécaniques de rétention et s\'étendre sur les marchés adjacents.' },
      ],
      featureTexts: [
        'Audiences sans bots — vérifiées manuellement avant onboarding',
        'Exécution KPI-driven : FTD, dépôts & cost-per-acquisition',
        'Rapports ROI hebdomadaires par streamer, dépenses vs résultats',
        '25+ marchés — Europe, LATAM, Amérique du Nord, APAC & Océanie',
        'Briefing compliance-first aligné sur les lois jeu responsable',
        'Multi-plateforme : Twitch, YouTube & Kick simultanément',
      ],
    },
    affiliateSection: {
      badge: 'Marketing Affiliés iGaming',
      title: 'Programmes Affiliés',
      titleHighlight: 'Qui Convertissent Vraiment.',
      subtitle: 'CPA · Partage de Revenus · Hybride — Construit par des Opérateurs',
      positioning: 'Construits par des personnes ayant géré des canaux affiliés du côté opérateur. Nous concevons des structures de commission autour de l\'économie réelle du joueur — pas des comptages de clics gonflés — et gérons chaque partenariat avec tracking live et reporting transparent coût par FTD.',
      accordion1Label: 'Ce qui est inclus dans la Gestion Affiliés',
      accordion1Items: [
        'Modèles de commission affiliés CPA, partage de revenus & hybrides basés sur la performance',
        'Créatifs conformes au jeu et pages d\'atterrissage géo-ciblées',
        'Développement de communauté et stratégies d\'engagement pour la rétention long terme',
        'Suivi affiliés temps réel et rapports de conversion transparents',
        'Gestion de programme affiliés iGaming conforme aux réglementations',
        'Infrastructure affiliés évolutive du startup à la marque casino enterprise',
      ],
      accordion2Label: 'Reporting & Transparence',
      accordion2Items: [
        'Accès dashboard temps réel pour tous les partenariats affiliés actifs',
        'Décompositions hebdomadaires : clics, inscriptions, FTD, volume dépôts & CPA',
        'Segmentation par affilié et par GEO',
        'Détection fraude et monitoring qualité du trafic',
        'Revue stratégique mensuelle et appels d\'optimisation du programme',
      ],
      featureTexts: [
        'Modèles CPA, partage revenus & hybrides conçus autour de l\'économie opérateur réelle',
        'Créatifs conformes et pages d\'atterrissage géo-ciblées',
        'Tracking conversion temps réel et reporting transparent',
        'Stratégies community building pour rétention joueurs long terme',
        'Infrastructure évolutive des opérateurs en démarrage à l\'enterprise',
        'Gestion programme affiliés par d\'anciens responsables acquisition casino',
      ],
    },
    influencerSection: {
      badge: 'Marketing Influenceurs Jeux',
      title: 'Joueurs High-LTV',
      titleHighlight: 'De Créateurs de Confiance.',
      subtitle: 'YouTube · TikTok · Twitch · Kick — Performance-First',
      positioning: 'Nous associons les marques iGaming et crypto-casino avec des influenceurs jeux vérifiés dont les audiences interagissent déjà avec le contenu casino. Chaque campagne est orientée vers de vrais joueurs déposants — pas des impressions vanity — avec tracking complet des conversions du premier clic au deuxième dépôt.',
      accordion1Label: 'Ce qui est inclus dans les Campagnes Influenceurs',
      accordion1Items: [
        'Réseau d\'influenceurs jeux vérifiés sur YouTube, TikTok, Twitch & Kick',
        'Gestion campagne influenceurs iGaming de bout en bout du brief au rapport ROI',
        'Modèles notoriété marque et acquisition joueurs pour casino & paris sportifs',
        'Sélection créateurs matchée à l\'audience par géo, niche & historique contenu iGaming',
        'Briefings influenceurs conformes aux réglementations jeu responsable',
        'Tracking conversion complet : FTD, dépôts, LTV & coût par joueur acquis',
      ],
      accordion2Label: 'Processus de Vetting Créateurs',
      accordion2Items: [
        'Audit manuel de la démographie audience, taux d\'engagement & distribution géo',
        'Revue de performance historique : données conversion campagnes iGaming passées',
        'Screening bots et faux-followers via outils d\'analyse tiers',
        'Vérification d\'alignement marque : style contenu, ton et intention audience',
        'Revue historique conformité avant toute présentation marque',
      ],
      featureTexts: [
        'Réseau vérifié sur YouTube, TikTok, Twitch & Kick',
        'Sélection créateurs matchée par géo, niche & historique iGaming',
        'Briefings influenceurs conformes aux réglementations jeu',
        'Tracking conversion complet : FTD, LTV & coût par joueur',
        'Modèles notoriété marque + acquisition directe disponibles',
        'Management end-to-end du brief à l\'analyse post-campagne',
      ],
    },
    title: 'Services Marketing Influenceurs iGaming',
    subtitle: 'Marketing streamers casino orienté performance, campagnes influenceurs jeux et programmes affiliés iGaming — construits par des initiés du secteur pour les marques crypto-casino, casino en ligne et paris sportifs dans le monde entier.',
    services: [
      {
        id: 'streamer-marketing',
        title: 'Marketing Streamers iGaming',
        description: 'Notre service phare de marketing streamers casino connecte les marques iGaming, crypto-casino et paris sportifs avec des streamers de jeux vérifiés et hautement performants sur Twitch, YouTube et Kick. Contrairement aux agences influenceurs génériques, chaque streamer de notre réseau est vétérifié manuellement pour son engagement d\'audience réel, son ciblage géographique et son historique prouvé de génération de premiers dépôts (FTD) dans l\'espace iGaming. Nous gérons la campagne de bout en bout — du sourcing streamer et briefing conformité à l\'exécution de contenu live et aux rapports ROI hebdomadaires.',
        cta: 'Obtenir un Plan de Croissance Gratuit',
        features: ['Streamers casino Twitch vérifiés, influenceurs jeux YouTube & streamers Kick', 'Campagnes influenceurs casino conformes aux standards jeu responsable', 'Exécution basée sur les KPI : FTD, dépôts, rétention joueurs & coût par acquisition', 'Rapports ROI hebdomadaires par streamer — transparence totale dépenses vs résultats', 'Expertise marques crypto-casino, casino en ligne & paris sportifs', 'Couverture sur 25+ marchés — Europe, LATAM, Amérique du Nord, Océanie & APAC'],
      },
      {
        id: 'affiliate-marketing',
        title: 'Marketing Affiliés iGaming',
        description: 'Nous construisons et gérons des programmes de marketing affiliés basés sur la performance pour les marques iGaming incluant les crypto-casinos, casinos en ligne et plateformes de paris sportifs. Notre approche affiliés iGaming est ancrée dans l\'expérience opérateur réelle — nous concevons des modèles de commission CPA, partage de revenus et hybrides qui génèrent une acquisition durable de joueurs à un coût par FTD maîtrisé. Chaque partenariat affilié est géré avec des créatifs conformes, un suivi des conversions en temps réel et des rapports transparents.',
        cta: 'Discuter Stratégie Affiliés',
        features: ['Modèles de commission affiliés CPA, partage de revenus & hybrides basés sur la performance', 'Créatifs conformes au jeu et pages d\'atterrissage géo-ciblées', 'Développement de communauté et stratégies d\'engagement pour la rétention long terme', 'Suivi affiliés en temps réel et rapports de conversion transparents', 'Gestion de programme affiliés iGaming conforme aux réglementations', 'Infrastructure affiliés évolutive du startup à la marque casino enterprise'],
      },
      {
        id: 'influencer-marketing',
        title: 'Marketing Influenceurs iGaming',
        description: 'Campagnes de marketing influenceurs jeux stratégiques spécialement conçues pour les plateformes iGaming et crypto-casino. Nous connectons les marques avec des influenceurs casino vérifiés, des chaînes jeux YouTube, des créateurs casino TikTok et des streamers Kick avec des audiences authentiques engagées dans le gaming en ligne et la crypto — livrant une notoriété de marque mesurable, une acquisition de joueurs et une rétention LTV élevée grâce à des relations créateurs de confiance. Notre stratégie est orientée performance dès le premier jour : chaque campagne est conçue pour livrer de vrais joueurs déposants.',
        cta: 'Planifier une Campagne Influenceurs',
        features: ['Réseau d\'influenceurs jeux vérifiés sur YouTube, TikTok, Twitch & Kick', 'Gestion de campagne influenceurs iGaming de bout en bout du brief au rapport ROI', 'Modèles de notoriété et acquisition joueurs pour casino & paris sportifs', 'Sélection créateurs correspondant à l\'audience par géo, niche & historique contenu iGaming', 'Briefings influenceurs conformes aux réglementations jeu responsable', 'Suivi conversion complet : FTD, dépôts, LTV & coût par joueur acquis'],
      },
    ],
    whatsIncluded: 'Ce qui est Inclus :',
    closing: {
      title: 'Prêt à Scaler Votre Acquisition de Joueurs iGaming ?',
      body: 'Réservez un appel stratégie gratuit de 30 minutes. Nous examinerons votre stratégie d\'acquisition de joueurs actuelle et vous montrerons exactement comment notre marketing influenceurs casino et campagnes streamers jeux peuvent générer de vrais joueurs déposants à un ROI mesurable.',
      cta1: 'Planifier Appel Stratégie Gratuit',
      cta2: 'Engager des Streamers Casino',
    },
  },
  resourcesPage: {
    badge: 'Ressources Marketing iGaming',
    title: 'Guides Marketing Influenceurs iGaming',
    subtitle: 'Ressources approfondies sur la stratégie marketing influenceurs casino, la conformité publicitaire jeux, la mesure du ROI et les tendances marketing crypto-casino — rédigées par des initiés du secteur iGaming.',
    readTime: 'min de lecture',
    ctaTitle: 'Prêt à Appliquer ces Stratégies ?',
    ctaBody: 'Notre équipe marketing iGaming implémente ces stratégies chaque jour pour des marques crypto-casino et casino en ligne. Réservez une consultation gratuite de 30 minutes.',
    ctaButton: 'Réserver Appel Stratégie Gratuit',
    articles: [
      { badge: 'Stratégie', title: 'ROI du Marketing Influenceurs iGaming : Ce que les Marques Obtiennent Vraiment', description: 'Une analyse data-driven des vrais métriques ROI, benchmarks coût par FTD et mesure de performance de campagne pour le marketing influenceurs casino.', readTime: 8 },
      { badge: 'Conformité', title: 'Conformité Marketing Influenceurs Jeux : UK, Malte, Curaçao & USA', description: 'Vue région par région des réglementations pub casino, exigences jeu responsable et cadres de campagne conformes.', readTime: 10 },
      { badge: 'Comparaison', title: 'Affiliés vs Marketing Influenceurs pour l\'iGaming : Lequel Génère Meilleur ROI ?', description: 'Comparaison directe programmes affiliés iGaming vs campagnes influenceurs — structures de coûts, taux de conversion et cas d\'usage.', readTime: 7 },
      { badge: 'Tendances', title: 'Tendances Marketing Crypto-Casino 2026 : Streamers, Web3 & Acquisition Joueurs', description: 'Les dernières tendances façonnant le marketing crypto-casino et jeux blockchain — des streamers Twitch aux campagnes influenceurs Web3-natives.', readTime: 9 },
      { badge: 'Guide Plateforme', title: 'Marketing Casino Twitch : Le Guide Complet des Marques pour 2026', description: 'Comment mener des sponsorings casino Twitch efficaces — trouver des streamers jeux, structurer les deals, considérations conformité et suivi ROI.', readTime: 11 },
      { badge: 'Stratégie', title: 'Stratégie Marketing Influenceurs Paris Esports pour les Bookmakers', description: 'Comment les marques paris sportifs et esports peuvent exploiter les influenceurs gaming, streamers esports et créateurs de contenu.', readTime: 8 },
    ],
  },
  faq: {
    title: 'Questions',
    titleHighlight: 'Fréquentes',
    subtitle: 'Tout ce que vous devez savoir sur l\'achat média influenceurs vérifié',
    items: [
      { q: 'Qu\'est-ce qui vous différencie des autres agences ?', a: 'La plupart des agences vendent de la portée. Nous livrons des streamers vérifiés, de vrais joueurs et un ROI mesurable. Chaque campagne est construite autour des dépôts, de la rétention et du LTV — pas des métriques de vanité.' },
      { q: 'Comment vérifiez-vous les streamers ?', a: 'Les streamers sont triés sur le volet et vérifiés manuellement pour leur engagement réel, géo d\'audience et performances iGaming passées. Nous ne travaillons qu\'avec des créateurs qui ont déjà prouvé qu\'ils peuvent générer des dépôts.' },
      { q: 'Qu\'est-ce qui est inclus dans la démo à 10 000$ ?', a: 'Un pilote de 2 semaines avec 5-10 streamers vérifiés, 10-15 heures de contenu live et un rapport de performance ROI complet. Vous obtenez la preuve avant de scaler — aucun engagement long terme requis.' },
      { q: 'Quels marchés servez-vous ?', a: 'Nous opérons en Europe, Amérique latine, Amérique du Nord et Océanie, couvrant 25+ marchés et 15+ langues. Les streamers sont toujours associés selon la géo, le comportement d\'audience et l\'adéquation à la marque.' },
      { q: 'Avec quelles plateformes travaillez-vous ?', a: 'Nous gérons des campagnes sur Twitch, YouTube, Kick et des environnements de streaming natifs aux plateformes. L\'exécution multi-plateforme garantit portée, fréquence et meilleure efficacité de conversion.' },
      { q: 'Comment suivez-vous les résultats ?', a: 'Chaque campagne est suivie de bout en bout avec des rapports de performance hebdomadaires. Vous voyez les dépenses, FTD, dépôts, rétention et ROI — décomposés streamer par streamer.' },
      { q: 'Quel est votre modèle tarifaire ?', a: 'Nous proposons des pilots démo fixes et des retainers mensuels évolutifs, selon votre stade de croissance. Aucuns frais cachés, aucun tarif vague — tout est aligné sur la livraison de performance.' },
      { q: 'Comment démarrer ?', a: 'Réservez une consultation gratuite de 30 minutes pour examiner vos objectifs et votre stratégie d\'acquisition actuelle. S\'il y a un fit, nous lançons une démo et prouvons les résultats avant de scaler.' },
      { q: 'Comment fonctionne le marketing streamers crypto-casino ?', a: 'Nous connectons les marques crypto-casino avec des streamers vérifiés qui ont des audiences prouvées dans l\'espace iGaming. Les streamers créent du contenu live authentique présentant votre plateforme, générant de vrais joueurs.' },
      { q: 'Quel est le ROI du marketing influenceurs iGaming ?', a: 'Nos clients voient généralement un ROI de 3-5x sur les campagnes streamers iGaming, avec un coût par FTD significativement inférieur aux canaux d\'acquisition traditionnels.' },
      { q: 'Comment trouvez-vous et vérifiez-vous les streamers casino ?', a: 'Chaque streamer de notre réseau est vérifié manuellement pour l\'authenticité de l\'audience, la qualité de l\'engagement, la portée géographique et les performances de conversion iGaming passées.' },
      { q: 'Travaillez-vous avec des marques crypto-casino ?', a: 'Oui. Les marques crypto-casino et Bitcoin casino sont un focus central. Nous nous spécialisons dans la mise en relation des plateformes de jeu crypto avec des streamers dont les audiences sont déjà engagées dans les crypto et le gaming en ligne.' },
      { q: 'Quels marchés et géographies couvrez-vous ?', a: 'Nous couvrons 25+ marchés à Dubaï, en Europe (UK, Allemagne, Malte), Amérique du Nord (Canada, USA), Océanie (Australie, Nouvelle-Zélande), Asie-Pacifique (Taïwan) et marchés LATAM émergents.' },
      { q: 'Combien coûte le marketing streamers iGaming ?', a: 'Nous offrons un pilot démo à 10 000$ pour les marques souhaitant tester notre approche sans engagement long terme. Les retainers mensuels évolutifs démarrent à partir de là.' },
    ],
  },
  lang: {
    switcher: 'Langue',
    en: 'English',
    ru: 'Русский',
    es: 'Español',
    uk: 'Українська',
    sv: 'Svenska',
    de: 'Deutsch',
    fr: 'Français',
  },
};

export default fr;
