import type { Translations } from './en';

const sv: Translations = {
  meta: {
    home: {
      title: 'Bästa iGaming Influencer-marknadsföringsbyrå 2026 | Octo Media',
      description: 'Ledande iGaming influencer-byrå. Verifierade streamers på Twitch, YouTube och Kick. Bevisad ROI för kryptokasino-varumärken. Boka ett kostnadsfritt strategisamtal.',
    },
    services: {
      title: 'iGaming Marknadsföringstjänster | Octo Media 2026',
      description: 'Expert-marknadsföring för kasinoinfluerare, spelstreamer-kampanjer och iGaming-affiliate-tjänster. Bevisad spelarförvärv för kryptokasino och sportbörsvarumärken.',
    },
    streamers: {
      title: 'Anlita Kasinostreamers på Twitch, YouTube & Kick | Octo Media',
      description: 'Gå med i det ledande iGaming-streamer-nätverket. Konsekventa spelsponsringar, bättre tariffer och snabbare betalningar. Kasinostreamers på Twitch, YouTube och Kick — ansök idag.',
    },
    whyUs: {
      title: 'Expert iGaming-byrå — Byggd av Kasinoinsiders',
      description: 'Octo Media Group: 8 iGaming-veteraner med bevisade FTD-resultat, fullständig ROI-transparens och resultatansvar.',
    },
    resources: {
      title: 'iGaming Marknadsföringsresurser & Guider | Octo Media Group',
      description: 'Expertguider för iGaming influencer-marknadsföring: regelefterlevnad, ROI-riktmärken, Twitch-kasinostrategi, kryptokasino-trender och mer.',
    },
    privacy: {
      title: 'Integritetspolicy | Octo Media Group',
      description: 'Octo Media Groups integritetspolicy. Lär dig hur vi samlar in, använder och skyddar din personliga information.',
    },
    terms: {
      title: 'Användarvillkor | Octo Media Group',
      description: 'Octo Media Groups användarvillkor. Läs villkoren som styr din användning av vår webbplats och tjänster.',
    },
    cookies: {
      title: 'Cookie-policy | Octo Media Group',
      description: 'Octo Media Groups cookie-policy. Lär dig hur vi använder cookies och liknande tekniker på vår webbplats.',
    },
  },
  nav: {
    home: 'Hem',
    services: 'Tjänster',
    ourStory: 'Vår Historia',
    forStreamers: 'För Streamers',
    faq: 'Frågor',
    contact: 'Kontakt',
    blog: 'Blogg',
    caseStudies: 'Fallstudier',
    whyJoin: 'Varför Gå Med',
    howItWorks: 'Hur Det Fungerar',
    apply: 'Ansök',
    ctaGrowthPlan: 'Gratis Tillväxtplan',
    ctaApplyNow: 'Ansök Nu',
    ctaGetInTouch: 'Kontakta Oss',
  },
  footer: {
    description: 'Den ledande iGaming influencer-marknadsföringsbyrån. Resultatdrivna kasinostreamer-kampanjer och spelinfluencer-marknadsföring för kryptokasino, onlinekasino och sportbörsvarumärken världen över.',
    quickLinks: 'Snabblänkar',
    ourServices: 'Våra Tjänster',
    legal: 'Juridisk Information',
    contact: 'Kontakt',
    links: {
      agency: 'iGaming Marknadsföringsbyrå',
      services: 'iGaming Marknadsföringstjänster',
      whyOcto: 'Varför Octo Media',
      hireStreamers: 'Anlita Kasinostreamers',
      faq: 'Frågor',
      contact: 'Kontakt',
    },
    serviceLinks: {
      streamer: 'Kasinostreamer-marknadsföring',
      affiliate: 'iGaming Affiliate-marknadsföring',
      influencer: 'Spelinfluencer-marknadsföring',
    },
    legalLinks: {
      privacy: 'Integritetspolicy',
      terms: 'Användarvillkor',
      cookies: 'Cookie-policy',
    },
    telegram: '@OctoMediaGroup på Telegram',
    bottomText1: 'Octo Media Group är en specialiserad iGaming influencer-marknadsföringsbyrå som erbjuder kasinostreamer-marknadsföring, spelinfluencer-marknadsföring och iGaming affiliate-marknadsföring för kryptokasino, onlinekasino och sportbörsvarumärken. Vi driver också ett dedikerat nätverk för Twitch-, YouTube- och Kick-kasinostreamers som söker konsekventa spelsponsringar.',
    bottomText2: 'Genom att använda denna webbplats godkänner du våra Användarvillkor, Integritetspolicy och Cookie-policy. Fortsatt användning innebär acceptans av dessa policyer.',
    copyright: 'Alla rättigheter förbehållna. EU GDPR-kompatibel.',
  },
  hero: {
    headline1: 'iGaming-spelarförvärv',
    headline2: 'Optimerat för',
    headline3: 'Högt LTV-utbyte',
    subheadline: 'Den dedikerade marknadsföringsbyrån för kryptokasinostreamers som ledande iGaming-varumärken världen över litar på. Resultatdriven streamer- och influencer-marknadsföring för iGaming och kryptokasino.',
    stat1Value: '$10M+',
    stat1Label: 'Intäkter Genererade',
    stat2Value: 'Helhetslösning',
    stat2Label: 'Kampanjhantering',
    stat3Value: 'Förvärv',
    stat3Label: 'och Retention',
    ctaPrimary: 'Gratis 30-Min Konsultation',
    ctaSecondary: 'Utforska Tjänster',
    badge: 'Byggt av iGaming-veteraner',
  },
  problem: {
    badge: 'Branschproblemet',
    title: 'iGaming Influencer-marknadsföringens Problem',
    titleHighlight: 'som Vi Löser',
    subtitle: 'iGaming-varumärken slösar miljoner på influencer-kampanjer som levererar tomma mätvärden istället för riktiga spelare. Så här ser branschen ut utan oss:',
    items: [
      { stat: '70%', title: 'Bortkastad Budget', description: 'av influencer-marknadsföringsbudgetar inom iGaming spenderas på skapare med falska eller irrelevanta målgrupper' },
      { stat: '< 0.5%', title: 'Konverteringsgrad', description: 'är den genomsnittliga konverteringsgraden från generiska influencer-kampanjer — knappt en droppe av riktiga insättande spelare' },
      { stat: 'INGEN', title: 'Ansvarsskyldighet', description: 'Ingen ansvarsskyldighet för kvalitet och kvantitet på resultat. Ingen förutsägbarhet. De flesta byråer erbjuder noll transparent spårning eller garantier' },
    ],
    realityCheck: 'Verklighetscheck',
    typicalMetrics: 'Typiska Kampanjmätvärden',
    typicalSubtitle: 'Vad som händer när du arbetar med standardbyråer',
    spent: 'Spenderat på kampanj',
    signUps: 'Registreringar mottagna',
    ftds: 'FTD:er konverterade',
    costPerFtd: 'Kostnad per FTD',
    secondDepositors: 'Andra gångens insättare',
    noRetention: 'Ingen retention',
  },
  solution: {
    badge: 'Vad Vi Gör Bäst',
    title: 'Vår iGaming-marknadsföring',
    titleHighlight: 'Expertis',
    subtitle: 'Täcker Dubai, Europa, LATAM, Nordamerika, Oceanien och Asien-Stillahavsregionen med verifierade streamers. Vi hanterar både spelarförvärv och retention för kasino- och kryptokasino-varumärken.',
    services: [
      { title: 'Streamer-marknadsföring', description: 'Skaparupptäckt, KPI-baserad exekvering, multiplattformstäckning över Twitch, YouTube och Kick för både nytt spelarförvärv och långsiktig retention', tag1: 'Förvärv', tag2: 'Retention', link: 'Läs Mer' },
      { title: 'Affiliate-marknadsföring', description: 'Marknadsriktade kreativa material, community-byggande och prestandabaserade affiliate-partnerskap som driver både spelarförvärv och retention', tag1: 'Förvärv', tag2: 'Retention', link: 'Läs Mer' },
      { title: 'Influencer-marknadsföring', description: 'Strategiska partnerskap med high-impact influencers för varumärkeskännedom, spelarförvärv och löpande engagemang genom autentiskt innehåll', tag1: 'Förvärv', tag2: 'Retention', link: 'Läs Mer' },
    ],
  },
  howWeSolve: {
    badge: 'Vår Process',
    title: 'Hur Vår iGaming Streamer-marknadsföring',
    titleHighlight: 'Fungerar',
    subtitle: 'Ett rigoröst femstegssystem som omvandlar influencer-utgifter till mätbara, skalbara intäkter',
    fiveStep: 'femstegssystem',
    scalable: 'mätbara, skalbara intäkter',
    cta: 'Se Det i Aktion',
    steps: [
      { title: 'Enbart Handplockade, Beprövade Streamers', description: 'Vi bjuder in och onboardar streamers manuellt — enbart från iGaming-nischer med verifierade tidigare resultat, riktiga målgrupper och bevisad insättningsprestanda.', highlight: 'Manuellt Verifierade' },
      { title: 'Rigorös Granskning & Varumärkesmatchning', description: 'Varje streamer granskas för engagemangsautenticitet, målgruppsdemografi och historisk prestanda, och matchas sedan enbart med de varumärken de redan konverterar för.', highlight: '100% Autentisk' },
      { title: 'Kontrollerade Liveampanjer med Hög Avsikt', description: 'Streamers spelar live med strukturerat gameplay, varumärkessäker presentation och autentisk marknadsföring — utformad för att attrahera riktiga spelare med hög avsikt, inte tomma visningar.', highlight: 'Enbart Hög Avsikt' },
      { title: 'Full ROI-transparens', description: 'Detaljerade veckovisa prestandarapporter som bryter ned varje spenderad dollar — streamerkostnader, FTD:er, insättningar, retention och ROI — tydliga och ansvarsskyldiga.', highlight: 'Veckorapporter' },
      { title: 'Skala Det som Fungerar, Behåll Det som Konverterar', description: 'Vi fördubblar insatsen på vinnande streamers och aktiverar retentionsmekaniker — topplistor, bonusar och community-incitament — för att driva upprepade insättningar och högre LTV.', highlight: 'Bevisad Skalning' },
    ],
  },
  comparison: {
    badge: 'Skillnaden',
    title: 'Varför iGaming-varumärken Väljer Oss Framför',
    titleHighlight: 'Standardmarknadsföringsbyråer',
    subtitle: 'Mätbara mätvärden som bevisar ett fundamentalt annorlunda tillvägagångssätt för iGaming-marknadsföring',
    standardAgency: 'Standardbyrå',
    metrics: [
      { label: 'Retention' },
      { label: 'Konverteringsgrad' },
      { label: 'Tid till Första Resultat' },
      { label: 'Utgiftstransparens & Effektivitet' },
    ],
    features: [
      { category: 'Streamergranskning', standard: 'Overifierade, blandade målgrupper', octo: '100% botfria verifierade målgrupper' },
      { category: 'Kampanjsupport', standard: 'Månatliga PDF-rapporter', octo: 'Detaljerade veckorapporter + dedikerad chef' },
      { category: 'Marknadstäckning', standard: '1-2 regioner', octo: '25+ marknader, 15+ språk' },
      { category: 'Retentionsstrategi', standard: 'Ingår inte', octo: 'Fullständiga retentions- och communityprogram' },
      { category: 'Plattformstäckning', standard: 'Enfokusfokus på plattform', octo: 'Twitch, YouTube, Kick & mer' },
    ],
    highlights: ['Bättre Kontroll', 'Utmärkt Exekvering', 'Exceptionella Resultat'],
  },
  pricing: {
    title: 'Kampanj',
    titleHighlight: 'Paket',
    subtitle: 'Från en riskfri demo till fullskalig marknadsdomination. Välj den nivå som matchar dina mål.',
    mostPopular: 'Mest Populär',
    footerNote: 'Alla paket inkluderar fullständig prestandaspårning, dedikerat stöd och transparent rapportering.',
    tiers: [
      { name: 'Demokampanj', price: '$10,000', period: 'engångskostnad', tagline: 'Bevis innan åtagande', cta: 'Starta Demo', features: ['5-10 verifierade streamers', '10-15 timmars liveinnehåll', 'Fullständig prestandaspårning', 'Detaljerad ROI-rapport', 'Skalningsrekommendation'] },
      { name: 'Starter', price: '$25-50K', period: '/månad', tagline: 'För växande varumärken som går in på nya marknader', cta: 'Begär Offert', features: ['15-20 stora streamers', '30-50 timmars innehåll/månad', 'Veckovisa prestandarapporter', 'Kampanjoptimering', 'Dedikerad kontoansvarig'] },
      { name: 'Tillväxt', price: '$50-75K', period: '/månad', tagline: 'För varumärken redo att skalas aggressivt', cta: 'Begär Offert', features: ['50+ mikro- och makrostreamers', '100+ timmars innehåll/månad', 'Realtids prestandadashboard', 'Multiplattformstäckning', 'Prioritetsstöd & strategisk rådgivning', 'Högkonverterande SEO-webbplatspartnerskap'] },
      { name: 'Enterprise', price: '$100K+', period: '/månad', tagline: 'För stora operatörer som dominerar marknader', cta: 'Kontakta Oss', features: ['100+ verifierade streamers', 'Obegränsat liveinnehåll', 'Exklusiva streamerpartnerskap', 'White-label-alternativ', 'Dedikerat team av specialister', 'Anpassad rapportering & analys', '5x SEO-webbplatspartnerskap'] },
    ],
  },
  socialProof: {
    badge: 'Litat på Världen Över',
    title: 'Litat på av Ledande',
    titleHighlight: 'iGaming',
    titleEnd: 'Varumärken',
    subtitle: 'Branschledare förlitar sig på vårt nätverk för att driva förvärv, retention och tillväxt',
    stats: [
      { value: '15+', label: 'Varumärkespartners' },
      { value: '$2.5M', label: 'Budget Spenderad' },
      { value: '20+', label: 'Marknader Täckta' },
      { value: '98%', label: 'Kundretention' },
    ],
    testimonials: [
      { quote: 'Octo Medias streamerstrategi hjälpte oss att snabbt skala på nyckelmarknader. Deras exekvering och transparens är förstklassig.', detail: 'Vi såg en omedelbar förbättring i målgruppsengagemang och konverteringsgrader på alla streamingkanaler under den första månaden.', role: 'Varumärkeschef', company: 'BC.GAME' },
      { quote: 'Att arbeta med Octo Media transformerade vår pipeline för spelarförvärv. Deras djupa förståelse för iGaming-målgruppen levererade mätbara resultat från dag ett.', detail: 'Deras riktade tillvägagångssätt för streamurval och innehållsstrategi resulterade i leads av högre kvalitet och bättre långsiktigt spelarvärde.', role: 'Marknadsföringschef', company: 'BET365' },
      { quote: 'Kvaliteten på streamers och innehåll som Octo Media hittar är oöverträffad. Vår varumärkessynlighet på konkurrensutsatta marknader växte avsevärt inom veckor.', detail: 'Från dag ett hade vi tillgång till autentiska, engagerade målgrupper som genuint kopplade till vårt varumärkes budskap och värderingar.', role: 'Partnerskapsdirektör', company: 'LEON' },
      { quote: 'Octo Media tog ett datadrivet tillvägagångssätt till våra influencer-kampanjer som vi inte hade sett tidigare. Retentionsmätvärden förbättrades på varje kanal de hanterade.', detail: 'Deras strategiska insikter och kontinuerlig optimering höll våra kampanjer på toppnivå under hela året.', role: 'Tillväxtledare', company: 'MELBET' },
      { quote: 'Att samarbeta med Octo Media gav oss tillgång till ett kurerat nätverk av high-impact streamers. Kampanjprestandan överskred konsekvent våra riktmärken.', detail: 'Vi uppnådde en nivå av kampanjprestanda som gav oss förtroende att öka budget och expandera till nya marknader.', role: 'Förvärvsansvarig', company: 'STAKE' },
      { quote: 'Den sömlösa integrationen och professionalismen som Octo Media förde till våra kampanjer utmärker dem. Deras fokus på spelarretention levererade exceptionell ROI.', detail: 'Till skillnad från andra byråer bryr de sig genuint om långsiktigt partnersskaps framgång och spelares livstidsvärde, inte bara snabba vinster.', role: 'Tillväxtledare', company: 'TRUSTDICE' },
    ],
  },
  markets: {
    items: [
      { title: 'Onlinekasino', description: 'Traditionella kasinon, kryptokasino, Bitcoin-kasino, kasino med livecroupierer' },
      { title: 'Sportsbetting', description: 'Fotbollsbetting, esportsbetting, multisportplattformar' },
      { title: 'Gaming Gambling', description: 'CS2 gambling, Rust gambling, spelrelaterat betting' },
      { title: 'Pokerrum', description: 'Online-poker, turneringar' },
    ],
  },
  contact: {
    title: 'Ta',
    titleHighlight: 'Kontakt',
    subtitle: 'Redo att omvandla din marknadsföringsbudget till riktiga insättande spelare? Skicka oss ett meddelande eller boka en gratis konsultation.',
    formTitle: 'Skicka ett Meddelande',
    namePlaceholder: 'Ditt Namn',
    emailPlaceholder: 'E-postadress',
    messagePlaceholder: 'Ditt Meddelande',
    sendButton: 'Skicka Meddelande',
    businessEmail: 'Affärs-e-post',
    businessEmailDesc: 'För partnerskap och professionella förfrågningar',
    telegramSupport: 'Telegram-support',
    telegramDesc: 'Snabba svar och realtidssupport',
    bookTitle: 'Boka en Gratis Konsultation',
    bookDesc: 'Schemalägg ett 30-minuters samtal för att diskutera din influencer-marknadsföringsstrategi.',
    discussLabel: 'Vad vi kommer att diskutera',
    scheduleButton: 'Schemalägg Ditt Samtal',
    topics: [
      'Din nuvarande spelarförvärvstorategi',
      'Hur verifierad influencer-marknadsföring passar dina mål',
      'Förväntad ROI från demokampanj',
      'Anpassat kampanjförslag för ditt varumärke',
    ],
    responseTime: 'Svarstid',
    responseTimeValue: 'Svarar vanligtvis inom 15-30 minuter',
    availability: 'Tillgänglighet',
    availabilityValue: 'Aktiv: 7 dagar i veckan',
    supportType: 'Supporttyp',
    supportTypeValue: 'Streamerförfrågningar, kampanjplanering, partnerskap',
  },
  finalCta: {
    badge: 'Begränsad Tillgänglighet',
    title1: 'Dina Konkurrenter Skalar Redan',
    title2: 'med Oss',
    subtitle: 'Varje dag du väntar är ännu en dag med bortslösad annonsutgift på overifierade influencers med fejkade följare.',
    body: 'Vi tar bara ett begränsat antal varumärken per kvartal för att säkerställa kvalitetsexekvering. Säkra din plats innan dina konkurrenter gör det.',
    cta: 'Hämta Din Gratis Tillväxtplan',
    guarantees: ['Inga långtidskontrakt', '100% transparent spårning', 'Resultat inom 2 veckor', 'Dedikerad kontoansvarig'],
  },
  demo: {
    badge: 'Noll Risk',
    title1: 'Inte Övertygad?',
    title2: 'Se Oss i Aktion',
    subtitle: 'Ge oss $10 000 och två veckor. Om vi inte levererar mätbara resultat vet du det innan du förbinder dig till en större budget.',
    steps: [
      { title: '$10 000 Investering', description: 'Fast kostnad, inga dolda avgifter. Du vet exakt vad du betalar.' },
      { title: '2-veckors Kampanj', description: '5-10 verifierade streamers spelar live och marknadsför ditt varumärke.' },
      { title: 'Mätbara Resultat', description: 'Fullständig prestandarapport med ROI-data och skalningsplan.' },
    ],
    whatsIncluded: 'Vad som Ingår',
    includes: [
      'Handplockade verifierade streamers matchade till ditt varumärke',
      '10-15 timmars livestreamerinnehåll',
      'Tillgång till realtids spårningsdashboard',
      'Detaljerad ROI & prestandarapport',
      'Skalningsrekommendation utan åtagande',
    ],
    noContract: 'Inget långtidskontrakt krävs. Resultaten talar för sig själva.',
    pilotLabel: '2-veckors pilotkampanj',
    cta: 'Schemalägg Ditt Demosamtal',
  },
  streamersSection: {
    badge: 'För Streamers',
    title: 'Väx Din',
    titleHighlight: 'Streamingkarriär',
    subtitle: 'Gå med i vårt nätverk av 750+ verifierade streamers och matchas med ledande iGaming-varumärken. Vi hanterar affärssidan så att du kan fokusera på att skapa innehåll.',
    benefits: [
      'Tillgång till premium iGaming-varumärken',
      'Konkurrenskraftiga provisionsgrader',
      'Pålitliga och punktliga betalningar',
      'Dedikerad partnerskapsansvarig',
      'Prestandabonusar och exklusiva erbjudanden',
      'Multiplattformsstöd (Twitch, YouTube, Kick)',
    ],
    cta: 'Ansök Nu',
    verifiedStreamers: 'Verifierade Streamers',
    avgEarnings: 'Genomsnittliga månatliga inkomster',
    avgEarningsValue: '$2 000 - $15 000',
    platforms: 'Plattformar som stöds',
    platformsValue: 'Twitch, YT, Kick',
    paymentSchedule: 'Betalningsschema',
    paymentScheduleValue: 'Varannan vecka',
    markets: 'Tillgängliga marknader',
    marketsValue: '25+ länder',
  },
  streamersPage: {
    hero: {
      badge: 'För Streamers & Skapare',
      title1: 'Sluta Jaga Deals.',
      title2: 'Börja Bli',
      titleHighlight: 'Betald',
      subtitle: 'iGaming-streamer-nätverket som kopplar verifierade skapare med ledande kasino- och kryptovarumärken för löpande sponsringar.',
      subtitleSmall: 'Bättre tariffer. Snabbare betalningar. Noll krångel.',
      cta: 'Ansök Nu',
    },
    benefits: {
      badge: 'Komplett Partnerskapsekosystem',
      title: 'Varför',
      titleHighlight: 'Arbeta med Oss',
      subtitle: 'Mer än bara varumärkesdeals. Ett komplett ekosystem designat för att maximera din inkomstpotential och skydda dina intressen vid varje steg.',
      commissionNote: '10% provision på deals vi stänger för dig',
      commissionSub: 'Debiteras bara efter att du fått betalt. Noll risk, maximal transparens.',
      items: [
        { title: 'Personlig Manager 24/7', desc: 'Din dedikerade kontoansvarige är tillgänglig dygnet runt för att hantera alla dina frågor, förhandlingar och kampanjkoordinering.' },
        { title: 'Ingen Exklusivitet Krävs', desc: 'Hittade ett bättre deal själv? Kör på! Vi ger gratis rådgivning så att du vet ditt verkliga värde på marknaden.' },
        { title: 'Noll Uppfronstskostnader', desc: 'Inga prenumerationsavgifter eller dolda kostnader. Vi tar en fast 10% bara efter att du fått betalt för din kampanj. Enkelt och transparent.' },
        { title: 'Endast Granskade Varumärken', desc: 'Inte mer bedrägerier eller försenade betalningar. Arbeta idag, få betalt idag. Direkt till ditt bankkonto eller kryptoplånbok.' },
        { title: 'Flexibla Dealstrukturer', desc: 'Föredrar du rensaldo, fasta avgifter eller livstids intäktsdelning? Vi skräddarsyr deals efter dina preferenser och innehållsstil.' },
        { title: 'Inga Långtidskontrakt', desc: 'Tar en paus eller har problem? Gå när som helst. Inga böter, inga frågor. Vi har din rygg.' },
        { title: 'Varumärkesbyggande Stöd', desc: 'Utöver deals hjälper vi dig bygga ditt personliga varumärke med webbplatsinställning, strategi för sociala medier och professionell innehållsvägledning.' },
        { title: 'Exklusiv Evenemangstillgång', desc: 'Inbjudan till offline-sammankomster världen över. Vi flyger dig dit, alla kostnader betalade. Nätverka med toppstreamers och branschledare.' },
        { title: 'Kontinuerlig Innovation', desc: 'Vår plattform utvecklas med nya funktioner, verktyg och möjligheter. Gå med för att forma framtiden för skaparmonetisering.' },
      ],
    },
    howItWorks: {
      title: 'Hur Det',
      titleHighlight: 'Fungerar',
      subtitle: 'Från ansökan till utbetalning i fyra enkla steg',
      step: 'STEG',
      steps: [
        { title: 'Ansök', desc: 'Fyll i en snabb ansökan med information om din kanal, plattform och målgruppsstorlek.' },
        { title: 'Bli Verifierad', desc: 'Vårt team granskar din innehållskvalitet, målgruppsautenticitet och engagemangsmätvärden.' },
        { title: 'Bli Matchad', desc: 'Vi parar ihop dig med iGaming- och kryptokasino-varumärken som passar din nisch, målgrupp och innehållsstil för maximala resultat.' },
        { title: 'Skapa & Bli Betald', desc: 'Streama sponsrat iGaming-innehåll och ta emot snabba, pålitliga betalningar direkt till ditt konto.' },
      ],
    },
    faq: {
      title: 'Vanliga',
      titleHighlight: 'Frågor',
      subtitle: 'Vanliga frågor från streamers som går med i vårt nätverk',
      items: [
        { q: 'Hur mycket kan jag tjäna?', a: 'Inkomster varierar baserat på din målgruppsstorlek, engagemang och innehållskvalitet. Våra streamers tjänar vanligtvis mellan $500 och $15 000+ per månad från varumärkesdeals via vårt nätverk.' },
        { q: 'Vilka plattformar stöder ni?', a: 'Vi arbetar med streamers på Twitch, YouTube, Kick och andra stora streamingplattformar. Om du har en aktiv målgrupp på någon streamingplattform vill vi höra från dig.' },
        { q: 'Vad händer om jag har färre än 5 000 följare?', a: 'Vi arbetar ibland med mindre skapare som har exceptionella engagemangsgrader. Ansök ändå och vårt team granskar din profil. Målgruppskvalitet spelar större roll än råa siffror.' },
        { q: 'Vilket slags innehåll behöver jag skapa?', a: 'Sponsrade streams med iGaming och kryptokasino-varumärken. Det specifika formatet och kraven varierar per varumärke, men vi arbetar alltid med dig för att säkerställa att innehållet känns naturligt och autentiskt.' },
        { q: 'Hur långa är kontrakten?', a: 'De flesta deals är månad-till-månad utan långsiktig inlåsning. Vissa premiumpartnerskap kan löpa i 3-6 månader, men du vet alltid villkoren i förväg innan du förbinder dig.' },
        { q: 'Tar ni provision?', a: 'Vi betalas av varumärkena, inte av dig. Den taxa vi förhandlar för din räkning är vad du tar emot. Det finns inga dolda avgifter eller avdrag från dina inkomster.' },
        { q: 'Kan jag arbeta med andra byråer samtidigt?', a: 'Ja. Vi har inga exklusivitetskrav. Du är fri att arbeta med andra byråer och ta direkta deals. Vi ber bara att du hedrar aktiva kampanjåtaganden.' },
        { q: 'Hur lång tid tar ansökningsprocessen?', a: 'Vanligtvis 2-5 arbetsdagar. Vi granskar din kanal, verifierar dina målgruppsmätvärden och om du godkänns kan du ta emot din första varumärkesdeal inom en vecka.' },
      ],
    },
    form: {
      title: 'Ansök',
      titleHighlight: 'Nu',
      subtitle: 'Fyll i formuläret nedan så granskar vårt team din ansökan',
      fullName: 'Fullständigt Namn *',
      emailAddress: 'E-postadress *',
      primaryPlatform: 'Primär Plattform *',
      followerCount: 'Antal Följare *',
      profileUrl: 'Profil / Kanal-URL *',
      telegramHandle: 'Telegram-handtag (valfritt)',
      describeContent: 'Beskriv Ditt Innehåll *',
      selectPlatform: 'Välj plattform',
      selectRange: 'Välj intervall',
      namePlaceholder: 'Ditt namn',
      contentPlaceholder: 'Berätta om ditt innehåll, målgrupp och vilken typ av varumärkesdeals du är intresserad av...',
      submitButton: 'Skicka Ansökan',
      successTitle: 'Ansökan Skickad',
      successBody: 'Din e-postklient har öppnats med dina ansökningsuppgifter. Skicka e-postmeddelandet för att slutföra din inskickning. Vi granskar din profil och återkommer till dig inom 2-5 arbetsdagar.',
      submitAnother: 'Skicka En Till Ansökan',
    },
    whyJoin: {
      title: 'Varför Gå Med i Vårt',
      titleHighlight: 'Nätverk',
      subtitle: 'Vi byggde det för skapare som är trötta på opålitliga deals och låga erbjudanden',
      items: [
        { title: 'Kontinuerliga Deals', desc: 'Månadsvis återkommande iGaming-sponsringar så att du alltid har kasino-varumärkesdeals på plats. Ingen mer jakt på engångskampanjer.' },
        { title: 'Bättre Tariffer', desc: 'Vi förhandlar premiumtariffer för din räkning med vår nätverkshävstång. Tjäna mer per timme innehåll än ensam.' },
        { title: 'Vi Sköter Affärerna', desc: 'Kontrakt, fakturering, förhandlingar, efterlevnad. Vi hanterar pappersarbetet så att du kan fokusera på streaming.' },
        { title: 'Snabba Betalningar', desc: 'Bli betald inom 7-14 dagar. Ingen jakt på varumärken i månader. Vi garanterar punktliga, pålitliga utbetalningar.' },
        { title: 'Gaming-Vänliga Varumärken', desc: 'Arbeta med välrenommerade iGaming- och kryptokasino-varumärken, sportsbetting-plattformar och spelföretag som passar din målgrupp.' },
        { title: 'Ingen Bindning', desc: 'Arbeta med oss på dina villkor. Inga exklusivitetskontrakt. Du är fri att samarbeta med andra byråer och varumärken.' },
      ],
    },
    whatYouGet: {
      badge: 'Kärnfunktioner',
      title: 'Octo-',
      titleHighlight: 'Fördelen',
      subtitle: 'Allt du behöver för att professionellt monetarisera ditt innehåll och skala ditt skaparföretag',
      items: [
        { title: 'Återkommande Partnerskap', desc: 'Långsiktiga varumärkesdeals som ger stabila, förutsägbara inkomster månad efter månad.' },
        { title: 'Premium-tariffer', desc: 'Vår volym och rykte låter oss förhandla högre CPM och fasta tariffer än du kunde ensam.' },
        { title: 'Fullständig Service', desc: 'Dedikerad partnernskapsansvarig, kontraktshantering, kreativa briefs och compliancestöd.' },
        { title: 'Snabba Betalningar', desc: '7-14 dagars betalningscykler. Ingen väntan 60-90 dagar. Vi betalar i tid, varje gång.' },
        { title: 'Riktad Varumärkesmatchning', desc: 'Bli matchad med iGaming- och kryptokasino-varumärken som resonerar med din specifika målgrupp.' },
        { title: 'Flexibilitet', desc: 'Ingen exklusivitet. Arbeta med flera varumärken och byråer. Skala upp eller ner på dina villkor.' },
      ],
    },
    eligibility: {
      title: 'Behörighets-',
      titleHighlight: 'krav',
      subtitle: 'Se till att du uppfyller grundkraven innan du ansöker',
      items: [
        { title: '5 000+ Följare', desc: 'Minsta antal följare på din primära streamingplattform.' },
        { title: 'Gaming / Gambling-innehåll', desc: 'Ditt innehåll bör vara gaming- eller gambling-relaterat för att passa våra varumärkespartners.' },
        { title: 'Närvaro på Stor Plattform', desc: 'Aktiv på Twitch, YouTube, Kick eller liknande stora streamingplattformar.' },
        { title: 'Autentiskt Engagemang', desc: 'Riktiga tittare och genuina interaktioner. Vi verifierar engagemangskvalitet, inte bara siffror.' },
        { title: 'Global Tillgänglighet', desc: 'Vi arbetar med streamers världen över. Alla regioner och språk är välkomna.' },
        { title: 'Konsekvent Schema', desc: 'Regelbundet streamingschema med pålitlig innehållsproduktion och målgruppsretention.' },
      ],
    },
    comparison: {
      badge: 'Det Självklara Valet',
      title: 'Traditionella Byråer vs',
      titleHighlight: 'Octo Media',
      subtitle: 'Se varför tusentals streamers byter från traditionella talangbyråer till vår skapar-first plattform',
      traditionalLabel: 'Traditionell',
      traditionalAgency: 'Traditionell Byrå',
      octoMedia: 'Octo Media',
      metrics: [
        { label: 'Provisionssats', traditional: '20-40%', us: '10%' },
        { label: 'Betalningstid', traditional: '60-90 dagar', us: 'Samma dag' },
        { label: 'Kontraktstid', traditional: '12-24 månader', us: 'Ingen bindning' },
        { label: 'Genomsnittligt Dealvärde', traditional: '$2-5K/mån', us: '$8-15K/mån' },
      ],
      features: [
        { category: 'Exklusivitet', traditional: 'Krävs - Kan inte arbeta med andra byråer', us: 'Valfri - Arbeta fritt med flera partners' },
        { category: 'Uppfrontskostnader', traditional: 'Inställningsavgifter, månatliga prenumerationer', us: 'Noll uppfrontskostnader eller dolda avgifter' },
        { category: 'Varumärkesgranskning', traditional: 'Minimal granskning, betalningsförseningar vanliga', us: '100% granskade varumärken, garanterade betalningar' },
        { category: 'Personlig Support', traditional: 'Delad manager för 50+ skapare', us: 'Dedikerad 24/7 personlig manager' },
        { category: 'Deal-flexibilitet', traditional: 'Endast standardpaket', us: 'Anpassade deals efter dina preferenser' },
        { category: 'Kontraktsutgång', traditional: 'Böter och uppsägningstider', us: 'Gå när som helst, inga böter' },
        { category: 'Karriärstöd', traditional: 'Begränsat till deal-mäkleri', us: 'Fullständigt varumärkesbyggande och tillväxtstöd' },
      ],
      highlights: ['Lägre Provision', 'Snabbare Betalningar', 'Högre Inkomster'],
    },
  },
  whyUsPage: {
    hero: {
      badge: 'VARFÖR OCTOMEDIA',
      title: 'Byggd av Kasinoinsiders,\nInte Marknadsföringsoutsiders',
      subtitle: 'OctoMedia grundades av åtta iGaming-veteraner som tillbringade år inom riktiga kasinon och kryptokasino-plattformar — med att hantera förvärv, retention, lanseringar och regelefterlevnad. Den enda iGaming-marknadsföringsbyrån som kombinerar streamer-specifikt fokus, kryptokasino-specialisering och ett grundarteam av ex-operatörer. Vi förstår FTD:er, LTV och retention eftersom vi har mätts på dem.',
      point1: 'Ex-Kasino & Kryptokasino Proffs',
      point2: 'iGaming Streamer-marknadsföringsspecialister',
      point3: 'Regelmedveten Skalning',
    },
    differentiators: {
      title: 'Vad Som Gör Oss Annorlunda',
      subtitle: 'OctoMedia är inte bara ännu en marknadsföringsbyrå. Vi är byggda annorlunda eftersom vi kommer inifrån branschen.',
      items: [
        { title: 'Operatörsmindset', description: 'Vi tänker som kasinooperatörer eftersom vi var kasinooperatörer. Varje beslut filtreras genom verkliga KPI:er och operationella begränsningar.' },
        { title: 'FTD-, LTV- & Retentionsfokus', description: 'Vi optimerar för mätvärden som spelar roll: förstadepositioner, livstidsvärde, andragångsinsättningsgrader och långsiktig spelarretention.' },
        { title: 'Datadrivet Influencer-marknadsföring', description: 'Inga tomma mätvärden. Vi spårar konverteringsgrader, kostnad per FTD och målgruppskvalitet för varje streamer och innehållsskapare.' },
        { title: 'Regelmedveten Skalning', description: 'Tillväxtstrategier byggda med regelmedvetenhet. Vi vet vilka marknader som kräver varsamt budskap och vilka influencers som utgör regelefterlevnadsrisk.' },
        { title: 'Tillgång till Branschnätverk', description: 'Direkta relationer med toppstreamers, affiliatnätverk och medieköpare som verkligen förstår iGaming och kryptokasino.' },
        { title: 'Långsiktigt Varumärkesvärde', description: 'Vi balanserar aggressivt förvärv med hållbart varumärkesbyggande. Kortsiktiga vinster utan långsiktig skada.' },
      ],
    },
    foundingStory: {
      title: 'Hur Vi Startade',
      body1: 'Vi möttes i olika kasinoroller — förvärvsansvariga, retentionsledare, affiliate-chefer, regelefterlevnadsstrateger. Några av oss lanserade kryptokasino från noll. Andra skalade etablerade varumärken på flera GEO:er.',
      body2: 'Den gemensamma frustrationen? Marknadsföringsbyråer som inte riktigt förstod iGaming.',
      body3: 'De sålde "medvetenhet" och "engagemang" medan vi mättes på förstadepositioner, andragångsinsättningsgrader och livstidsvärde. De kunde inte tala språket för CPA-deals, bonusmissbruksskydd eller regelrisk.',
      body4: 'Så vi byggde OctoMedia — en byrå driven av människor som redan har varit på operatörssidan. Vi vet vad som fungerar eftersom vi har deployat budgetar, hanterat influencer-kampanjer och optimerat trattar under verklig press.',
      closing: 'Vi gissar inte. Vi har redan gjort det.',
      cards: [
        { heading: 'Var Vi Kom Ifrån', text: 'Vi möttes i olika kasinoroller — förvärvsansvariga, retentionsledare, affiliate-chefer, regelefterlevnadsstrateger. Några av oss lanserade kryptokasino från noll.' },
        { heading: 'Frustrationen', text: 'Marknadsföringsbyråer som inte riktigt förstod iGaming. De sålde "medvetenhet" och "engagemang" medan vi mättes på förstadepositioner och livstidsvärde.' },
        { heading: 'Gapet Vi Såg', text: 'De kunde inte tala språket för CPA-deals, bonusmissbruksskydd eller regelrisk. Ingen överbryggade gapet mellan influencer-marknadsföring och verkliga operatörs-KPI:er.' },
        { heading: 'Varför Vi Byggde OctoMedia', text: 'En byrå driven av människor som redan har varit på operatörssidan. Vi vet vad som fungerar eftersom vi har deployat budgetar och optimerat trattar under verklig press.' },
      ],
    },
    foundingTeam: {
      title: 'Möt Grundarteamet',
      subtitle: 'Åtta kasinoveteraner som byggde sina karriärer inuti branschen, inte utanför den.',
      yearsLabel: 'År',
      exLabel: 'Tidigare:',
      strengthLabel: 'Styrka:',
    },
    closing: {
      badge: 'SKILLNADEN ÄR TYDLIG',
      title: 'Vi Har Redan Varit\nInuti iGaming',
      subtitle: 'OctoMedia byggdes av människor som har drivit förvärv för kasino och kryptokasino, hanterat iGaming influencer-kampanjer för miljoner dollar och optimerat retentionsträttar under verklig press. Vi förstår inte bara iGaming streamer-marknadsföring — vi har levt det.',
      cta1: 'Utforska Streamerpartnerskap',
      cta2: 'Ta Kontakt',
      stat1Value: '8',
      stat1Label: 'Grundarveteraner',
      stat2Value: '62',
      stat2Label: 'Kombinerade Års Erfarenhet',
      stat3Value: '100%',
      stat3Label: 'Ex-Kasinoproffsar',
    },
  },
  servicesPage: {
    badge: 'VÅRA TJÄNSTER',
    heroBadge: 'iGaming Marknadsföringstjänster',
    heroTitle: 'Performance-marknadsföring Byggd för',
    heroTitleHighlight: 'iGaming-operatörer',
    heroSubtitle: 'Tre beprövade förvärvningskanaler — streamerkampanjer, affiliateprogram och influencer-marknadsföring — hanterade end-to-end av ex-kasinooperatörer.',
    tab1: 'Streamer-marknadsföring',
    tab2: 'Affiliate-marknadsföring',
    tab3: 'Influencer-marknadsföring',
    howItWorksLabel: 'Hur det Fungerar',
    whatYouGetLabel: 'Vad Du Får',
    inlineCta1: 'Vill du se streamerresultat innan du åtar dig en full budget?',
    inlineCta2: 'Redo att bygga ett regelefterlevande, högkonverterande affiliateprogram?',
    inlineCtaNote: 'Inget långsiktigt åtagande krävs. Se resultat innan du skalar.',
    inlineCtaBtn: 'Boka ett Gratis Strategisamtal',
    closingBadge: 'Noll Långsiktigt Åtagande',
    trustSignals: ['Inga långsiktiga kontrakt', '100% utgiftstransparens', 'Resultat inom 2 veckor', 'Dedikerad account manager'],
    stats: [
      { value: '25+', label: 'Täckta Marknader' },
      { value: '750+', label: 'Verifierade Streamers' },
      { value: '3–5x', label: 'Genomsnittlig ROI' },
      { value: '2 Veckor', label: 'Första Resultaten' },
    ],
    streamerSection: {
      badge: 'Kasinostreamer-marknadsföring',
      title: 'Verifierade Streamers.',
      titleHighlight: 'Bevisade Insättningar.',
      subtitle: 'Twitch · YouTube · Kick — 25+ Marknader',
      positioning: 'Varje streamer i vårt nätverk väljs manuellt från iGaming-nischer, granskas för verkligt målgruppsengagemang och matchas endast med varumärken de redan konverterar för. Vi hanterar end-to-end-exekvering — från compliance-briefing till veckovisa ROI-rapporter.',
      accordion1Label: 'Vad som ingår i en Streamerkampanj',
      accordion1Items: [
        'Verifierade kasinostreamers på Twitch, YouTube och Kick',
        'Regelefterlevande kampanjer med ansvarsfulla spelstandarder',
        'KPI-baserad exekvering: FTD:er, insättningar, spelarretention & kostnad per förvärv',
        'Veckovisa ROI-rapporter per streamer — fullständig utgifts- vs resultattransparens',
        'Kryptokasino-, onlinekasino- & sportbörsvarumärkesexpertis',
        'Täckning på 25+ marknader — Europa, LATAM, Nordamerika, Oceanien & APAC',
      ],
      accordion2Label: 'Plattformar & Regelefterlevnad',
      accordion2Items: [
        'Livestreamingkampanjer på Twitch, YouTube Live & Kick samtidigt',
        'Geo-inriktad streamurval för dina licensierade marknader',
        'Ansvarsfulla spel-disclaimers inbäddade i varje kampanjbriefing',
        'Ålderverifieringsfilter för målgrupper tillämpas före lansering',
        'Innehåll granskat mot UK, MGA, Curaçao & lokala regelstandarder',
      ],
      steps: [
        { num: '01', title: 'Briefing & Varumärkesmatch', desc: 'Vi kartlägger dina mål-GEOs, spelarprofil och compliancekrav för att bygga en exakt skaparbriefing.' },
        { num: '02', title: 'Streamersökning', desc: 'Handplockade från vårt verifierade nätverk — matchade efter nisch, målgruppsgeografi och insättningskonverteringshistorik.' },
        { num: '03', title: 'Live Kampanjexekvering', desc: 'Streamers går live med strukturerat gameplay, varumärkessäkert innehåll och autentisk marknadsföring till högintensusspelaren.' },
        { num: '04', title: 'Realtidsspårning', desc: 'Dashboard-åtkomst + veckovisa rapporter: FTD:er, insättningar, kostnad per spelare, retention och fullständig ROI-uppdelning.' },
        { num: '05', title: 'Skala & Behåll', desc: 'Dubbla satsningen på topprestörer, aktivera retentionsmekanismer och expandera till angränsande marknader.' },
      ],
      featureTexts: [
        'Botfria målgrupper — manuellt verifierade före onboarding',
        'KPI-driven exekvering: FTD:er, insättningar & kostnad per förvärv',
        'Veckovisa ROI-rapporter per streamer, utgifter vs resultat',
        '25+ marknader — Europa, LATAM, Nordamerika, APAC & Oceanien',
        'Compliance-first briefing i linje med ansvarsfulla spelregler',
        'Multi-plattform: Twitch, YouTube & Kick samtidigt',
      ],
    },
    affiliateSection: {
      badge: 'iGaming Affiliate-marknadsföring',
      title: 'Affiliateprogram',
      titleHighlight: 'Som Faktiskt Konverterar.',
      subtitle: 'CPA · Intäktsdelning · Hybrid — Operatörsbyggt',
      positioning: 'Byggda av människor som hanterat affiliatekanaler från operatörssidan. Vi designar provisionsstrukturer runt verklig spelarekonomi — inte uppblåsta klickräkningar — och hanterar varje partnerskap med live-spårning och transparent kostnad-per-FTD-rapportering.',
      accordion1Label: 'Vad som ingår i Affiliatehantering',
      accordion1Items: [
        'Prestandabaserade CPA-, intäktsdelnings- & hybridprovisionmodeller',
        'Spellagstiftningskompatibla kreativa resurser och geo-inriktade landningssidor',
        'Community-byggande och engagemangsstrategier för långsiktig spelarretention',
        'Realtids affiliatspårning och transparent konverteringsrapportering',
        'Regelmedveten iGaming affiliate-programhantering',
        'Skalbar affiliatinfrastruktur från startup till enterprise kasinovarumärken',
      ],
      accordion2Label: 'Rapportering & Transparens',
      accordion2Items: [
        'Realtids dashboard-åtkomst för alla aktiva affiliatpartnerskap',
        'Veckovisa uppdelningar: klick, registreringar, FTD:er, insättningsvolym & CPA',
        'Segmentering per affiliat och per GEO',
        'Bedrägeridetektering och trafikvalitetsövervakning',
        'Månatlig strategigenomgång och programoptimeringssamtal',
      ],
      featureTexts: [
        'CPA-, intäktsdelnings- & hybridmodeller designade runt verklig operatörsekonomi',
        'Regelefterlevande kreativa resurser och geo-inriktade landningssidor',
        'Realtids konverteringsspårning och transparent rapportering',
        'Community building-strategier för långsiktig spelarretention',
        'Skalbar infrastruktur från tidiga operatörer till enterprise',
        'Affiliateprogramhantering av ex-kasinoanskaffningschefer',
      ],
    },
    influencerSection: {
      badge: 'Spelinfluencer-marknadsföring',
      title: 'High-LTV-spelare',
      titleHighlight: 'Från Betrodda Skapare.',
      subtitle: 'YouTube · TikTok · Twitch · Kick — Performance-First',
      positioning: 'Vi kopplar iGaming- och kryptokasino-varumärken med verifierade spelinfluencers vars målgrupper redan interagerar med kasinoinnehåll. Varje kampanj är inriktad på riktiga insättande spelare — inte vanity-visningar — med fullständig konverteringsspårning från första klick till andra insättning.',
      accordion1Label: 'Vad som ingår i Influencer-kampanjer',
      accordion1Items: [
        'Verifierat spelinfluencer-nätverk på YouTube, TikTok, Twitch & Kick',
        'End-to-end iGaming influencer-kampanjhantering från briefing till ROI-rapport',
        'Varumärkeskännedom och spelarförvärvsmodeller för kasino & sportbörs',
        'Målgruppsmatched skaparurval efter geo, nisch & iGaming-innehållshistorik',
        'Regelefterlevande influencer-briefings i linje med ansvarsfulla spelregler',
        'Fullständig konverteringsspårning: FTD:er, insättningar, LTV & kostnad per förvärvad spelare',
      ],
      accordion2Label: 'Skapargranskningsprocess',
      accordion2Items: [
        'Manuell granskning av målgruppsdemografi, engagemangsgrader & geo-distribution',
        'Historisk prestandagranskning: tidigare iGaming-kampanjkonverteringsdata',
        'Bot- och falsk-följare-screening via tredjepartsanalysverktyg',
        'Varumärkesalignementskontroll: innehållsstil, ton och målgruppsintention',
        'Compliancehistorikgranskning före varumärkespresentation',
      ],
      featureTexts: [
        'Verifierat nätverk på YouTube, TikTok, Twitch & Kick',
        'Målgruppsmatched skaparurval efter geo, nisch & iGaming-historia',
        'Regelefterlevande influencer-briefings enligt spelreglering',
        'Fullständig konverteringsspårning: FTD:er, LTV & kostnad per spelare',
        'Varumärkeskännedom + direkta förvärvsmodeller tillgängliga',
        'End-to-end management från brief till post-kampanjanalys',
      ],
    },
    title: 'iGaming Influencer-marknadsföringstjänster',
    subtitle: 'Resultatdriven kasinostreamer-marknadsföring, spelinfluencer-kampanjer och iGaming affiliate-program — byggda av branschinsiders för kryptokasino, onlinekasino och sportbörsvarumärken världen över.',
    services: [
      {
        id: 'streamer-marketing',
        title: 'iGaming Streamer-marknadsföring',
        description: 'Vår flaggskepps-kasinostreamer-marknadsföringstjänst kopplar iGaming-, kryptokasino- och sportbörsvarumärken med verifierade, högpresterande spelstreamers på Twitch, YouTube och Kick. Till skillnad från generiska influencer-byråer granskas varje streamer i vårt nätverk manuellt för verkligt målgruppsengagemang, geografisk inriktning och en bevisad meritlista av att driva förstadepositioner (FTD:er) i iGaming-utrymmet. Vi hanterar end-to-end kampanjhantering — från streamersökning och regelefterlevnadsbriefing till liveinnehållsexekvering och veckovisa ROI-rapporter.',
        cta: 'Hämta Gratis Tillväxtplan',
        features: ['Verifierade Twitch-kasinostreamers, YouTube-spelinfluencers & Kick-streamers', 'Regelefterlevande kasinoinfluencer-kampanjer med ansvarsfulla spelstandarder', 'KPI-baserad exekvering: FTD:er, insättningar, spelarretention & kostnad per förvärv', 'Veckovisa ROI-rapporter per streamer — fullständig utgifts- vs. resultattransparens', 'Kryptokasino-, onlinekasino- & sportbörsvarumärkesexpertis', 'Täckning på 25+ marknader — Europa, LATAM, Nordamerika, Oceanien & APAC'],
      },
      {
        id: 'affiliate-marketing',
        title: 'iGaming Affiliate-marknadsföring',
        description: 'Vi bygger och hanterar prestandabaserade affiliate-marknadsföringsprogram för iGaming-varumärken inklusive kryptokasino, onlinekasino och sportbettingplattformar. Vår iGaming-affiliateansats är grundad i verklig operatörsupplevelse — vi designar CPA-, intäktsdelnings- och hybridprovisionmodeller som driver hållbart spelarförvärv till kontrollerad kostnad per FTD. Varje affiliatpartnerskap hanteras med regelefterlevande kreativa resurser, realtids konverteringsspårning och transparent rapportering.',
        cta: 'Diskutera Affiliatstrategi',
        features: ['Prestandabaserade CPA-, intäktsdelnings- & hybridprovisionmodeller', 'Spellagstiftningskompatibla kreativa resurser och geo-inriktade landningssidor', 'Community-byggande och engagemangsstrategier för långsiktig spelarretention', 'Realtids affiliatspårning och transparent konverteringsrapportering', 'Regelmedveten iGaming affiliate-programhantering', 'Skalbar affiliatinfrastruktur från startup till enterprise kasinovarumärken'],
      },
      {
        id: 'influencer-marketing',
        title: 'iGaming Influencer-marknadsföring',
        description: 'Strategiska spelinfluencer-marknadsföringskampanjer speciellt byggda för iGaming och kryptokasino-plattformar. Vi kopplar varumärken med verifierade kasinoinfluencers, YouTube-spelkanaler, TikTok-kasinoskapare och Kick-streamers som har autentiska målgrupper engagerade i online-gaming och krypto — och levererar mätbar varumärkeskännedom, spelarförvärv och hög-LTV-retention. Vår strategi är prestationsdriven från dag ett: varje kampanj är utformad för att leverera riktiga insättande spelare, inte tomma visningar.',
        cta: 'Planera en Influencer-kampanj',
        features: ['Verifierat spelinfluencer-nätverk på YouTube, TikTok, Twitch & Kick', 'End-to-end iGaming influencer-kampanjhantering från briefing till ROI-rapport', 'Varumärkeskännedom och spelarförvärvsmodeller för kasino & sportbörs', 'Målgruppsmatched skaparurval efter geo, nisch & iGaming-innehållshistorik', 'Regelefterlevande influencer-briefings i linje med ansvarsfulla spelregler', 'Fullständig konverteringsspårning: FTD:er, insättningar, LTV & kostnad per förvärvad spelare'],
      },
    ],
    whatsIncluded: 'Vad som Ingår:',
    closing: {
      title: 'Redo att Skala Ditt iGaming-spelarförvärv?',
      body: 'Boka ett gratis 30-minuters strategisamtal. Vi granskar din nuvarande spelarförvärvsstrategi och visar dig exakt hur vår kasinoinfluencer-marknadsföring och spelstreamer-kampanjer kan driva riktiga insättande spelare med mätbar ROI.',
      cta1: 'Schemalägg Gratis Strategisamtal',
      cta2: 'Anlita Kasinostreamers',
    },
  },
  resourcesPage: {
    badge: 'iGaming Marknadsföringsresurser',
    title: 'iGaming Influencer-marknadsföringsguider',
    subtitle: 'Djupgående resurser om kasinoinfluencer-marknadsföringsstrategi, spelreklamsefterlevnad, ROI-mätning och kryptokasino-marknadsföringstrender — skrivna av iGaming-branschinsiders.',
    readTime: 'min läsning',
    ctaTitle: 'Redo att Tillämpa Dessa Strategier?',
    ctaBody: 'Vårt iGaming-marknadsföringsteam implementerar dessa strategier varje dag för kryptokasino och onlinekasino-varumärken. Boka en gratis 30-minuterskonsultation.',
    ctaButton: 'Boka Gratis Strategisamtal',
    articles: [
      { badge: 'Strategi', title: 'ROI för iGaming Influencer-marknadsföring: Vad Varumärken Faktiskt Får', description: 'En datadrivet analys av verkliga ROI-mätvärden, kostnad-per-FTD-riktmärken och hur man mäter kampanjprestanda.', readTime: 8 },
      { badge: 'Regelefterlevnad', title: 'Regelefterlevnad för Spelinfluencer-marknadsföring: UK, Malta, Curacao & USA', description: 'Region-för-region uppdelning av kasino-reklamregler, krav på ansvarsfullt spel och kompatibla kampanjramverk.', readTime: 10 },
      { badge: 'Jämförelse', title: 'Affiliate vs. Influencer-marknadsföring för iGaming: Vilket Ger Bättre ROI?', description: 'En direkt jämförelse av iGaming affiliate-program vs. influencer-kampanjer — kostnadsstrukturer, konverteringsgrader och när man ska använda vardera.', readTime: 7 },
      { badge: 'Trender', title: 'Kryptokasino Marknadsföringstrender 2026: Streamers, Web3 & Spelarförvärv', description: 'De senaste trenderna som formar kryptokasino och blockchain-spelmarknadsföring — från Twitch-streamers till Web3-nativa influencer-kampanjer.', readTime: 9 },
      { badge: 'Plattformsguide', title: 'Twitch Kasinomarknadsföring: Den Kompletta Varumärkesguiden för 2026', description: 'Hur man kör effektiva Twitch-kasinosponsringar — hitta spelstreamers, strukturera deals, regelefterlevnadshänsyn och spåra ROI.', readTime: 11 },
      { badge: 'Strategi', title: 'Esports Betting Influencer-marknadsföringsstrategi för Sportbörs', description: 'Hur sportbörs- och esportsbettingvarumärken kan utnyttja spelinfluencers, esportsstreamers och innehållsskapare för att driva insättande spelare.', readTime: 8 },
    ],
  },
  faq: {
    title: 'Vanliga',
    titleHighlight: 'Frågor',
    subtitle: 'Allt du behöver veta om verifierat influencer-medieköp',
    items: [
      { q: 'Vad gör er annorlunda från andra byråer?', a: 'De flesta byråer säljer räckvidd. Vi levererar verifierade streamers, riktiga spelare och mätbar ROI. Varje kampanj är byggd kring insättningar, retention och LTV — inte tomma mätvärden.' },
      { q: 'Hur verifierar ni streamers?', a: 'Streamers handplockas och granskas manuellt för verkligt engagemang, målgruppsgeo och tidigare iGaming-prestanda. Vi arbetar bara med skapare som redan bevisat att de kan driva insättningar.' },
      { q: 'Vad ingår i $10 000-demon?', a: 'En 2-veckors pilot med 5-10 verifierade streamers, 10-15 timmars liveinnehåll och en fullständig ROI-prestandarapport. Du får bevis innan skalning — utan långtidsåtagande.' },
      { q: 'Vilka marknader betjänar ni?', a: 'Vi verkar i Europa, LATAM, Nordamerika och Oceanien, täcker 25+ marknader och 15+ språk. Streamers matchas alltid baserat på geo, målgruppsbeteende och varumärkespassform.' },
      { q: 'Vilka plattformar arbetar ni med?', a: 'Vi kör kampanjer på Twitch, YouTube, Kick och plattformsnativa streamingemiljöer. Multiplattformsexekvering säkerställer räckvidd, frekvens och högre konverteringseffektivitet.' },
      { q: 'Hur spårar ni resultat?', a: 'Varje kampanj spåras end-to-end med veckovisa prestandarapporter. Du ser utgifter, FTD:er, insättningar, retention och ROI — uppdelat streamer för streamer.' },
      { q: 'Vad är er prismodell?', a: 'Vi erbjuder fasta demopilots och skalbara månatliga retainers, beroende på din tillväxtfas. Inga dolda avgifter, inga vaga priser — allt är alignat med prestandaleverans.' },
      { q: 'Hur kommer jag igång?', a: 'Boka en gratis 30-minuterskonsultation för att granska dina mål och nuvarande förvärvssstrategi. Om det passar startar vi en demo och bevisar resultat innan skalning.' },
      { q: 'Hur fungerar marknadsföring av kryptokasinostreamers?', a: 'Vi kopplar kryptokasino-varumärken med verifierade streamers som har bevisade målgrupper i iGaming-utrymmet. Streamers skapar autentiskt liveinnehåll som visar upp din plattform.' },
      { q: 'Vad är ROI för iGaming influencer-marknadsföring?', a: 'Våra kunder ser vanligtvis 3-5x ROI på iGaming streamer-kampanjer, med kostnad per FTD avsevärt lägre än traditionella förvärvskanaler. Vi ger fullständig transparens med veckorapporter.' },
      { q: 'Hur hittar och verifierar ni kasinostreamers?', a: 'Varje streamer i vårt nätverk granskas manuellt för målgruppsautenticitet, engagemangskvalitet, geografisk räckvidd och tidigare iGaming-konverteringsprestanda.' },
      { q: 'Arbetar ni med kryptokasino-varumärken?', a: 'Ja. Kryptokasino och Bitcoin-kasino-varumärken är ett kärnfokus. Vi specialiserar oss på att koppla kryptospelplattformar med streamers som har målgrupper redan engagerade i kryptovaluta och online-gaming.' },
      { q: 'Vilka marknader och geo:er täcker ni?', a: 'Vi täcker 25+ marknader i Dubai, Europa (UK, Tyskland, Malta), Nordamerika (Kanada, USA), Oceanien (Australien, Nya Zeeland), Asien-Stillahavsregionen (Taiwan) och framväxande LATAM-marknader.' },
      { q: 'Hur mycket kostar iGaming streamer-marknadsföring?', a: 'Vi erbjuder en $10 000 demopilot för varumärken som vill testa vårt tillvägagångssätt utan långtidsåtagande. Skalbara månatliga retainers börjar därifrån.' },
    ],
  },
  lang: {
    switcher: 'Språk',
    en: 'English',
    ru: 'Русский',
    es: 'Español',
    uk: 'Українська',
    sv: 'Svenska',
    de: 'Deutsch',
    fr: 'Français',
  },
};

export default sv;
